/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrerequisiteTree } from '../../models/prerequisite-tree';

export interface ListPrerequisites$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * down for the prerequisites, the default; up for the dependents
 */
  direction?: 'down' | 'up';

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;
}

export function listPrerequisites(http: HttpClient, rootUrl: string, params: ListPrerequisites$Params, context?: HttpContext): Observable<StrictHttpResponse<PrerequisiteTree>> {
  const rb = new RequestBuilder(rootUrl, listPrerequisites.PATH, 'get');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.query('direction', params.direction, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PrerequisiteTree>;
    })
  );
}

listPrerequisites.PATH = '/api/v1/tenants/{tenant}/projects/{project}/tickets/{number}/prerequisites';
