/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InterestList } from '../../models/interest-list';

export interface ListInterest$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;

/**
 * The weak `ETag` of a list the client holds; an unchanged list answers 304 (docs/adr/0054 D7)
 */
  'If-None-Match'?: string;
}

export function listInterest(http: HttpClient, rootUrl: string, params: ListInterest$Params, context?: HttpContext): Observable<StrictHttpResponse<InterestList>> {
  const rb = new RequestBuilder(rootUrl, listInterest.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
    rb.header('If-None-Match', params['If-None-Match'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InterestList>;
    })
  );
}

listInterest.PATH = '/api/v1/teams/{team}/projects/{project}/tickets/{number}/interest';
