/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Ticket } from '../../models/ticket';
import { TicketBodyReplace } from '../../models/ticket-body-replace';

export interface ReplaceTicketBody$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * The `ETag` of the version the client read. Required on overwriting writes:
 * without it the answer is 428, with a stale one 412 (docs/adr/0050 D3).
 */
  'If-Match'?: string;
      body: TicketBodyReplace
}

export function replaceTicketBody(http: HttpClient, rootUrl: string, params: ReplaceTicketBody$Params, context?: HttpContext): Observable<StrictHttpResponse<Ticket>> {
  const rb = new RequestBuilder(rootUrl, replaceTicketBody.PATH, 'put');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Ticket>;
    })
  );
}

replaceTicketBody.PATH = '/api/v1/teams/{team}/projects/{project}/tickets/{number}/body';
