/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LinkType } from '../../models/link-type';

export interface UnlinkTickets$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * The link's type, the ticket in the path its source (docs/adr/0012 D1)
 */
  type: LinkType;

/**
 * The other end's key, <PROJECT>-<number>; a link never leaves the tenant (docs/adr/0012 D2)
 */
  other: string;
}

export function unlinkTickets(http: HttpClient, rootUrl: string, params: UnlinkTickets$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, unlinkTickets.PATH, 'delete');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.path('type', params.type, {});
    rb.path('other', params.other, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

unlinkTickets.PATH = '/api/v1/teams/{team}/projects/{project}/tickets/{number}/links/{type}/{other}';
