/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditAction } from '../../models/audit-action';

export interface ListAudit$Csv$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * A person's id
 */
  actor?: string;

/**
 * A token's id
 */
  token?: string;
  action?: Array<AuditAction>;
  entity_type?: string;

/**
 * Inclusive lower bound of the time
 */
  from?: string;

/**
 * Exclusive upper bound of the time
 */
  to?: string;

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;

/**
 * A numbered page, from 1 (docs/adr/0048 D2); not with cursor
 */
  page?: number;
  per_page?: 25 | 50 | 100;
}

export function listAudit$Csv(http: HttpClient, rootUrl: string, params: ListAudit$Csv$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, listAudit$Csv.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.query('actor', params.actor, {});
    rb.query('token', params.token, {});
    rb.query('action', params.action, {"style":"form","explode":true});
    rb.query('entity_type', params.entity_type, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
    rb.query('per_page', params.per_page, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

listAudit$Csv.PATH = '/api/v1/teams/{team}/audit';
