/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Member } from '../../models/member';
import { MemberGrantSet } from '../../models/member-grant-set';

export interface SetMemberGrant$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * A person's id
 */
  person_id: string;
      body: MemberGrantSet
}

export function setMemberGrant(http: HttpClient, rootUrl: string, params: SetMemberGrant$Params, context?: HttpContext): Observable<StrictHttpResponse<Member>> {
  const rb = new RequestBuilder(rootUrl, setMemberGrant.PATH, 'put');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('person_id', params.person_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Member>;
    })
  );
}

setMemberGrant.PATH = '/api/v1/teams/{team}/members/{person_id}/grant';
