/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Team } from '../../models/team';
import { TeamPatch } from '../../models/team-patch';

export interface UpdateTeam$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The `ETag` of the version the client read. Required on overwriting writes:
 * without it the answer is 428, with a stale one 412 (docs/adr/0050 D3).
 */
  'If-Match'?: string;
      body: TeamPatch
}

export function updateTeam(http: HttpClient, rootUrl: string, params: UpdateTeam$Params, context?: HttpContext): Observable<StrictHttpResponse<Team>> {
  const rb = new RequestBuilder(rootUrl, updateTeam.PATH, 'patch');
  if (params) {
    rb.path('team', params.team, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Team>;
    })
  );
}

updateTeam.PATH = '/api/v1/teams/{team}';
