/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocalLoginRequest } from '../../models/local-login-request';
import { LocalLoginResult } from '../../models/local-login-result';

export interface LoginLocal$Params {
      body: LocalLoginRequest
}

export function loginLocal(http: HttpClient, rootUrl: string, params: LoginLocal$Params, context?: HttpContext): Observable<StrictHttpResponse<LocalLoginResult>> {
  const rb = new RequestBuilder(rootUrl, loginLocal.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LocalLoginResult>;
    })
  );
}

loginLocal.PATH = '/auth/local';
