/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Problem } from '../../models/problem';

export interface OidcCallback$Params {

/**
 * The authorization code
 */
  code?: string;

/**
 * The `state` of the login, as the issuer returns it
 */
  state?: string;

/**
 * The issuer's error, sent instead of `code` (RFC 6749 4.1.2.1)
 */
  error?: string;
  error_description?: string;
}

export function oidcCallback(http: HttpClient, rootUrl: string, params?: OidcCallback$Params, context?: HttpContext): Observable<StrictHttpResponse<Problem>> {
  const rb = new RequestBuilder(rootUrl, oidcCallback.PATH, 'get');
  if (params) {
    rb.query('code', params.code, {});
    rb.query('state', params.state, {});
    rb.query('error', params.error, {});
    rb.query('error_description', params.error_description, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/problem+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Problem>;
    })
  );
}

oidcCallback.PATH = '/auth/callback';
