/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenCreate } from '../../models/token-create';
import { TokenCreated } from '../../models/token-created';

export interface CreateMyToken$Params {

/**
 * A UUID the client generates per act and repeats on every retry of it; an
 * agent's POST requires one (docs/adr/0045 D3, D4).
 */
  'Idempotency-Key'?: string;
      body: TokenCreate
}

export function createMyToken(http: HttpClient, rootUrl: string, params: CreateMyToken$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenCreated>> {
  const rb = new RequestBuilder(rootUrl, createMyToken.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenCreated>;
    })
  );
}

createMyToken.PATH = '/api/v1/me/tokens';
