/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InboxList } from '../../models/inbox-list';

export interface ListMyInbox$Params {

/**
 * Narrows a person-level list to one of the person's teams (docs/adr/0023 D2); a slug that names
 * none of them is `404 not_found`, whether or not the team exists. Where the list takes the
 * deprecated `tenant` as well, not together with it (`400 validation_failed`)
 */
  team?: string;

/**
 * Deprecated: replaced by `team`, which it means, kept in /api/v1 for one release and removed in a
 * later one (docs/adr/0005 D1, docs/adr/0046 D7). Not together with `team`
 * (`400 validation_failed`)
 *
 * @deprecated
 */
  tenant?: string;

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;

/**
 * The weak `ETag` of a list the client holds; an unchanged list answers 304 (docs/adr/0054 D7)
 */
  'If-None-Match'?: string;
}

export function listMyInbox(http: HttpClient, rootUrl: string, params?: ListMyInbox$Params, context?: HttpContext): Observable<StrictHttpResponse<InboxList>> {
  const rb = new RequestBuilder(rootUrl, listMyInbox.PATH, 'get');
  if (params) {
    rb.query('team', params.team, {});
    rb.query('tenant', params.tenant, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
    rb.header('If-None-Match', params['If-None-Match'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InboxList>;
    })
  );
}

listMyInbox.PATH = '/api/v1/me/inbox';
