/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DecisionList } from '../../models/decision-list';

export interface ListMyDecisions$Params {

/**
 * Narrows a person-level list to one of the person's tenants (docs/adr/0023 D2); a slug that names
 * none of them is `404 not_found`, whether or not the tenant exists
 */
  tenant?: string;

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;
}

export function listMyDecisions(http: HttpClient, rootUrl: string, params?: ListMyDecisions$Params, context?: HttpContext): Observable<StrictHttpResponse<DecisionList>> {
  const rb = new RequestBuilder(rootUrl, listMyDecisions.PATH, 'get');
  if (params) {
    rb.query('tenant', params.tenant, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DecisionList>;
    })
  );
}

listMyDecisions.PATH = '/api/v1/me/decisions';
