/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InboxState } from '../../models/inbox-state';

export interface MarkNotificationRead$Params {

/**
 * The notification's id
 */
  notification: string;
}

export function markNotificationRead(http: HttpClient, rootUrl: string, params: MarkNotificationRead$Params, context?: HttpContext): Observable<StrictHttpResponse<InboxState>> {
  const rb = new RequestBuilder(rootUrl, markNotificationRead.PATH, 'put');
  if (params) {
    rb.path('notification', params.notification, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InboxState>;
    })
  );
}

markNotificationRead.PATH = '/api/v1/me/inbox/{notification}/read';
