/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InboxReadThrough } from '../../models/inbox-read-through';
import { InboxState } from '../../models/inbox-state';

export interface MarkMyInboxRead$Params {

/**
 * Narrows a person-level list to one of the person's tenants (docs/adr/0023 D2); a slug that names
 * none of them is `404 not_found`, whether or not the tenant exists
 */
  tenant?: string;
      body: InboxReadThrough
}

export function markMyInboxRead(http: HttpClient, rootUrl: string, params: MarkMyInboxRead$Params, context?: HttpContext): Observable<StrictHttpResponse<InboxState>> {
  const rb = new RequestBuilder(rootUrl, markMyInboxRead.PATH, 'put');
  if (params) {
    rb.query('tenant', params.tenant, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InboxState>;
    })
  );
}

markMyInboxRead.PATH = '/api/v1/me/inbox/read';
