/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditAction } from '../models/audit-action';
import { Person } from '../models/person';
import { TokenMark } from '../models/token-mark';
export interface Activity {
  action: AuditAction;
  actor: (Person | null);
  actor_system: (string | null);

  /**
   * The changed fields after the act; null when redacted
   */
  after: ({
} | null);
  agent: (string | null);
  at: string;

  /**
   * The changed fields before the act; null when redacted
   */
  before: ({
} | null);
  entity_id: (string | null);
  entity_type: string;
  explained_by_comment: (string | null);
  id: string;
  note: (string | null);
  reason: (string | null);

  /**
   * The act names a ticket the caller cannot see; its payload, reason and note are withheld
   */
  redacted: boolean;

  /**
   * The token the act came through; null for a person's own browser session (docs/adr/0036 D6)
   */
  token: (TokenMark | null);
}
