/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Activity } from '../models/activity';
export interface ActivityList {
  items: Array<Activity>;
  next_cursor: (string | null);
}
