/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Attachment } from '../models/attachment';
export interface AttachmentList {
  items: Array<Attachment>;
  next_cursor: (string | null);
}
