/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DanglingAttachment } from '../models/dangling-attachment';
import { OrphanedObject } from '../models/orphaned-object';
import { OrphanRemovalRecord } from '../models/orphan-removal-record';

/**
 * The tenant's latest consistency check of its attachments (docs/adr/0059 D4): the files whose
 * metadata is there and whose bytes the bucket lacks — dangling — and the objects under the
 * tenant's prefix that no metadata names — orphans —, with the counts exact and each list at most
 * 1000 entries long. `check_id` is null, and everything else empty, while no check has run in the
 * tenant.
 */
export interface AttachmentConsistency {

  /**
   * The files whose bytes are missing and whose loss an administrator accepted
   */
  accepted: number;

  /**
   * The check's id, which a removal of its orphans or an acceptance of its missing files names
   */
  check_id: (string | null);
  checked_at: (string | null);

  /**
   * The files whose bytes are missing and whose loss nobody accepted
   */
  dangling: number;

  /**
   * The missing files, those nobody accepted first, at most 1000
   */
  dangling_attachments: Array<DanglingAttachment>;

  /**
   * The orphans' sizes, summed
   */
  orphan_bytes: number;

  /**
   * The removal of this check's orphans an administrator confirmed; null before
   */
  orphan_removal: (OrphanRemovalRecord | null);

  /**
   * The orphans in key order, at most 1000; empty once their removal was confirmed
   */
  orphaned_objects: Array<OrphanedObject>;

  /**
   * The objects no metadata names; 0 once their removal was confirmed
   */
  orphans: number;
}
