/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditEvent } from '../models/audit-event';
export interface AuditList {
  items: Array<AuditEvent>;
  next_cursor: (string | null);
}
