/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type AuditAction = 'created' | 'updated' | 'transitioned' | 'linked' | 'unlinked' | 'commented' | 'edited' | 'withdrawn' | 'assigned' | 'interest' | 'ranked' | 'overridden' | 'asked' | 'answered' | 'booked' | 'voided' | 'locked' | 'uploaded' | 'downloaded' | 'exported' | 'deleted' | 'restored' | 'purged' | 'revoked' | 'refused' | 'archived' | 'confidential_set' | 'confidential_lifted' | 'expired' | 'logged_in' | 'logged_out' | 'login_failed' | 'unlocked' | 'password_changed' | 'password_reset' | 'deactivated' | 'reactivated' | 'read' | 'merged' | 'closed' | 'reopened' | 'accepted';

