/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlockKind } from '../models/block-kind';
import { TicketState } from '../models/ticket-state';
export interface Block {
  external_ref?: (string | null);
  from: TicketState;
  kind: BlockKind;
  reason: string;

  /**
   * The key of the ticket it waits on, when the caller can see that ticket
   */
  ticket?: (string | null);
}
