/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlockKind } from '../models/block-kind';

/**
 * What a ticket entering blocked waits on (docs/adr/0009 D2)
 */
export interface BlockSet {
  external_ref?: string;
  kind: BlockKind;

  /**
   * The ticket it waits on, which gets a blocks link to this one; required with kind ticket
   */
  ticket?: string;
}
