/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The person's decision on a call that waits for it
 */
export interface ChatConfirmation {

  /**
   * True runs the call as the model proposed it; false answers the model that the person skipped it
   */
  run: boolean;
  tool_call_id: string;
}
