/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The wire format of the configured provider (COWORK_CHAT_PROVIDER): OpenAI Chat Completions, which
 * OpenAI, LM Studio, Ollama and vLLM speak, or the Anthropic Messages API (docs/adr/0076)
 */
export type ChatProvider = 'openai' | 'anthropic';

