/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from '../models/capability';

/**
 * The capabilities the chat's requests hold (docs/adr/0043 D5): what the chat may do beyond the
 * baseline, as the person chose it
 */
export interface ChatCapabilities {
  capabilities: Array<Capability>;

  /**
   * The person chose the set; false is the default, every capability but decide, close, drop and
   * record-answer
   */
  chosen: boolean;
}
