/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Whom a message of the chat is from — the person, the model, or a tool answering the model
 */
export type ChatRole = 'user' | 'assistant' | 'tool';

