/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatProviderKind } from './chat-provider-kind';

/**
 * Each possible value of `ChatProviderKind`
 */
export const CHAT_PROVIDER_KIND: ChatProviderKind[] = [
  'openai',
  'anthropic'
];