/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Why the chat is not available — the installation configures no provider
 */
export type ChatUnavailableReason = 'not_configured';

