/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatToolArguments } from '../models/chat-tool-arguments';

/**
 * The data of a chat turn's event `confirm`, a call that waits for the person's decision
 */
export interface ChatConfirmEvent {
  arguments: ChatToolArguments;

  /**
   * The act in words, for the person who decides it
   */
  description: string;

  /**
   * The call's id, which the decision names
   */
  id: string;

  /**
   * The tool's name
   */
  name: string;
}
