/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatUiAction } from './chat-ui-action';

/**
 * Each possible value of `ChatUiAction`
 */
export const CHAT_UI_ACTION: ChatUiAction[] = [
  'navigate'
];