/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatToolArguments } from '../models/chat-tool-arguments';

/**
 * A call of a tool the model made
 */
export interface ChatToolCall {
  arguments: ChatToolArguments;

  /**
   * The call's id, which the tool message answering it names
   */
  id: string;

  /**
   * The tool's name
   */
  name: string;
}
