/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatProviderId } from '../models/chat-provider-id';
import { ChatProviderKind } from '../models/chat-provider-kind';

/**
 * A provider the operator configured (COWORK_CHAT_PROVIDERS): what the person picks in the panel.
 * Its address and key are never shown
 */
export interface ChatProvider {
  id: ChatProviderId;
  kind: ChatProviderKind;

  /**
   * The model by the name its provider knows it (COWORK_CHAT_<ID>_MODEL)
   */
  model: string;

  /**
   * The provider's name for the person (COWORK_CHAT_<ID>_NAME)
   */
  name: string;
}
