/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatTurnEnd } from './chat-turn-end';

/**
 * Each possible value of `ChatTurnEnd`
 */
export const CHAT_TURN_END: ChatTurnEnd[] = [
  'answered',
  'step_limit',
  'stopped',
  'error'
];