/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatRole } from '../models/chat-role';
import { ChatToolCall } from '../models/chat-tool-call';

/**
 * One message of a conversation, in the neutral model the backend translates for its provider. A
 * `user` message carries `text`, what the person wrote; an `assistant` message `text`, what the model
 * said, and `tool_calls`, the calls it made — at least one of the two; a `tool` message
 * `tool_call_id`, the call it answers, `ok`, and `text`, the answer the model read. There is no
 * system message: the backend writes the model's instructions on every turn (docs/adr/0076).
 */
export interface ChatMessage {

  /**
   * On a tool message, whether the call succeeded; a refusal of the API is a failure the model reads
   */
  ok?: boolean;
  role: ChatRole;
  text?: string;
  tool_call_id?: string;
  tool_calls?: Array<ChatToolCall>;
}
