/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A tool call's arguments as the model gave them, a JSON object; the tool's schema decides what they mean
 */
export interface ChatToolArguments {

  [key: string]: any;
}
