/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatProvider } from '../models/chat-provider';
import { ChatUnavailableReason } from '../models/chat-unavailable-reason';
export interface ChatAvailability {

  /**
   * The members of the tenant may hold a conversation (POST …/chat)
   */
  available: boolean;

  /**
   * The configured providers in the configured order, the first the default of a turn; empty without one
   */
  providers: Array<ChatProvider>;

  /**
   * Why the chat is not available; null when it is
   */
  reason: (ChatUnavailableReason | null);
}
