/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The page the person is on as they send the turn: the model's instructions name it, and a short
 * key the model uses resolves against its project
 */
export interface ChatPageContext {

  /**
   * The page's path in this UI, without query or fragment, such as /t/acme/p/COW/board
   */
  path?: string;

  /**
   * The key of the project the page shows
   */
  project?: string;

  /**
   * The short key of the ticket the page shows, <PROJECT>-<number>
   */
  ticket?: string;
}
