/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatUiAction } from '../models/chat-ui-action';

/**
 * The data of a chat turn's event `ui`
 */
export interface ChatUiEvent {
  action: ChatUiAction;

  /**
   * The page to show, a path of this UI in the turn's team: /t/<team>/tickets/<PROJECT>-<number>,
   * /t/<team>/p/<PROJECT>/backlog or /t/<team>/p/<PROJECT>/board
   */
  path: string;
}
