/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Comment } from '../models/comment';
export interface CommentList {
  items: Array<Comment>;
  next_cursor: (string | null);
}
