/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * What an acceptance of the missing files did
 */
export interface DanglingAcceptance {

  /**
   * The files whose loss was accepted now
   */
  accepted: number;
}
