/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Tile 7, lead time: the median time from filing to done (`opened_at` to `done_at`) of the
 * tickets done in the thirty days that end with the period's last day — done now, their
 * `done_at` in that window, as throughput counts them; the median of an even count is the mean
 * of the middle two. `median_seconds` is `null` while no ticket was done in the window.
 */
export interface DashboardLeadTime {

  /**
   * The tickets the median is taken over
   */
  done: number;

  /**
   * The window's first day
   */
  from: string;

  /**
   * Whole seconds, rounded
   */
  median_seconds: (number | null);

  /**
   * The window's last day, the period's
   */
  to: string;
}
