/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketState } from '../models/ticket-state';
export interface DashboardStateCount {
  count: number;

  /**
   * The project's key
   */
  project: string;
  state: TicketState;
}
