/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlockKind } from '../models/block-kind';
export interface DashboardBlock {

  /**
   * The canonical key, <team>/<PROJECT>-<number>
   */
  key: string;
  kind: BlockKind;

  /**
   * When the ticket entered blocked
   */
  since: string;
  title: string;
}
