/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Decision } from '../models/decision';
export interface DecisionList {
  items: Array<Decision>;
  next_cursor: (string | null);
}
