/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeletedTicket } from '../models/deleted-ticket';
export interface DeletedTicketList {
  items: Array<DeletedTicket>;
  next_cursor: (string | null);
}
