/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One attachment of `attachments.json` — its metadata and URL, never its bytes (docs/adr/0016 D5)
 */
export interface ExportAttachment {
  name: string;
  size: number;

  /**
   * The ticket's key
   */
  ticket: string;

  /**
   * The stored content type
   */
  type: string;

  /**
   * The path of its bytes, `…/attachments/{attachment}/content`
   */
  url: string;
}
