/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExportManifestProject } from '../models/export-manifest-project';

/**
 * `manifest.json` of an export archive (docs/adr/0051 D4)
 */
export interface ExportManifest {

  /**
   * The confidential tickets of these projects the exporter cannot see, which the archive leaves out
   * — "n confidential tickets not included" (docs/adr/0065 D5)
   */
  confidential_not_included: number;
  exported_at: string;

  /**
   * The exporter as grammar v1 writes a person, `Name <identity>` (docs/adr/0044 D1)
   */
  exported_by: string;
  format: 'cowork export v1';

  /**
   * The project of a project export; every project the caller sees, by key, of a tenant export
   */
  projects: Array<ExportManifestProject>;

  /**
   * The tenant's slug
   */
  tenant: string;

  /**
   * The documents the archive holds
   */
  tickets: number;
}
