/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';

/**
 * The tenant's GitHub webhook secret as its administrators read it — never the secret itself
 */
export interface GitHubSecret {

  /**
   * When it was made or last rotated
   */
  created_at: string;
  created_by: Person;
}
