/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GitHubSecret } from '../models/git-hub-secret';
export interface GitHubIntegration {

  /**
   * The events to choose in GitHub's webhook settings; every other is taken and passed over
   */
  events: Array<string>;

  /**
   * The secret's metadata; null while the tenant has none, and then the endpoint answers like an unknown tenant
   */
  secret: (GitHubSecret | null);

  /**
   * The endpoint's path, which GitHub posts to under the installation's `COWORK_BASE_URL`
   */
  webhook_path: string;
}
