/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
export interface GitHubSecretCreated {
  created_at: string;
  created_by: Person;

  /**
   * A secret existed and is replaced; a delivery signed with it is refused from now on
   */
  replaced: boolean;

  /**
   * The new secret, 64 hexadecimal characters, shown in this answer only: give it to GitHub as the
   * webhook's secret. cowork keeps it sealed and never shows it again (docs/adr/0071 D1)
   */
  secret: string;
}
