/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface GroupMapping {
  created_at: string;

  /**
   * The group's name, matched exactly and case-sensitively against the groups claim (docs/adr/0029 D2)
   */
  group: string;
  id: string;

  /**
   * The calling person's groups, as of their last login or groups refresh,
   * include the group: changing or removing the mapping changes their own
   * role (docs/adr/0030 D2)
   */
  includes_caller: boolean;
  role: Role;
  updated_at: string;
  version: number;
}
