/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface GroupMappingCreate {

  /**
   * The group's name as the identity provider's claim carries it, case and all, with no white space at either end
   */
  group: string;
  role: Role;
}
