/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The ticket's horizon, a planning category a person or an agent sets in whatever state the ticket
 * is, and nothing else changes (docs/adr/0010 D3): now, to be worked on now; release, to be in the
 * next release; next, taken up when now is empty; later, maybe some day; icebox, frozen until what
 * it waits for changes
 */
export type Horizon = 'now' | 'release' | 'next' | 'later' | 'icebox';

