/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportFile } from '../models/import-file';
import { ImportStatus } from '../models/import-status';
import { ImportSummary } from '../models/import-summary';
import { Person } from '../models/person';

/**
 * An import job on a project (docs/adr/0051 D1): a dry run's report until it is executed or
 * twenty-four hours pass, then the report of the execution
 */
export interface ImportJob {
  created_at: string;
  created_by: Person;
  executed_at: (string | null);
  executed_by: (Person | null);

  /**
   * When the dry run is gone; null once it is executed
   */
  expires_at: (string | null);

  /**
   * Every file of the upload, in the order the upload carried them. Once a ticket the execution
   * created is purged, its file is no longer listed, and `summary` still counts it
   * (docs/adr/0024 D2)
   */
  files: Array<ImportFile>;
  id: string;

  /**
   * The project's key
   */
  project: string;
  status: ImportStatus;
  summary: ImportSummary;
}
