/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportFormat } from './import-format';

/**
 * Each possible value of `ImportFormat`
 */
export const IMPORT_FORMAT: ImportFormat[] = [
  'repository',
  'export',
  'plain'
];