/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlockKind } from '../models/block-kind';
import { TicketState } from '../models/ticket-state';

/**
 * The block a correction to the state `blocked` gives the ticket (docs/adr/0009 D2)
 */
export interface ImportBlockCorrection {
  from?: TicketState;
  kind: BlockKind;
  reason: string;
}
