/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LinkType } from '../models/link-type';

/**
 * A link the import creates, read from this file's end (docs/adr/0012)
 */
export interface ImportLink {

  /**
   * Outgoing when this file's ticket is the link's source
   */
  direction: 'outgoing' | 'incoming';

  /**
   * The other end's canonical key: a ticket of the upload or the project, or of another project or
   * team the importing person reads (docs/adr/0012 D2, docs/adr/0051 D9)
   */
  key: string;

  /**
   * Where the import read the link
   */
  source: 'blocked-by' | 'filed-from' | 'links.json';
  type: LinkType;
}
