/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImportMessage {

  /**
   * The frontmatter key, or the part of the file — `file`, `body`, `Q<n>`, `links.json` — the
   * message is about
   */
  field: (string | null);

  /**
   * The line of the file, from 1, where one applies
   */
  line: (number | null);
  message: string;
}
