/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
export interface ImportAssignee {

  /**
   * The member it is: the identity resolved — `local:<username>`, or `oidc:<issuer>#<subject>` of the
   * configured issuer — to a member who can see the project. Null when it resolves to nobody, never
   * guessed by the name: the ticket is then imported without an assignee, unless a correction names
   * one (docs/adr/0044 D1)
   */
  person: (Person | null);

  /**
   * The assignee as the file writes it, `Name <identity>` (docs/adr/0044 D1)
   */
  source: string;
}
