/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * What happens to a file of the upload. `create`: the execution creates its ticket. `conflict`: its
 * number is a ticket of the project already, deleted ones in the bin included, or was one that was
 * purged — a repeated import is a duplicate, not an update, and a number is never handed out twice
 * (docs/adr/0064 D3, docs/adr/0007 D4). `error`: it cannot be imported as it stands, `errors` says
 * why (docs/adr/0051 D2). `skip`: it is no ticket file, or it is a manifest of an export the import
 * reads beside the tickets (docs/adr/0063 D5). `exclude`: a correction left it out
 * (docs/adr/0063 D1). `created`: the execution created its ticket. A dry run is not executed while
 * a file it would import is `conflict` or `error`: exclude the file, or correct the source and make
 * a new dry run
 */
export type ImportOutcome = 'create' | 'conflict' | 'error' | 'skip' | 'exclude' | 'created';

