/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Activity } from '../models/activity';
import { InboxReason } from '../models/inbox-reason';
import { TeamRef } from '../models/team-ref';
import { TicketRef } from '../models/ticket-ref';
export interface InboxEntry {
  act: Activity;

  /**
   * For `blocker_closed`, the ticket that blocked this one and reached done or dropped, as it is now; null otherwise
   */
  blocker: (TicketRef | null);
  created_at: string;
  id: string;
  read: boolean;
  reason: InboxReason;
  team: TeamRef;

  /**
   * Deprecated, replaced by `team`, which it repeats; kept in /api/v1 for one release and removed in a later one (docs/adr/0005 D1, docs/adr/0046 D7)
   *
   * @deprecated
   */
  tenant: TeamRef;
  ticket: TicketRef;

  /**
   * The comment or question the act is on has been withdrawn since
   */
  withdrawn: boolean;
}
