/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InboxReason } from './inbox-reason';

/**
 * Each possible value of `InboxReason`
 */
export const INBOX_REASON: InboxReason[] = [
  'assigned',
  'asked',
  'answered',
  'state_changed',
  'blocker_closed',
  'commented',
  'urgent'
];