/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InterestWeight } from '../models/interest-weight';
export interface InterestSet {

  /**
   * Expected for need and urgent
   */
  note?: string;
  weight: InterestWeight;
}
