/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Interest } from '../models/interest';
export interface InterestList {
  items: Array<Interest>;
  next_cursor: (string | null);
}
