/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InterestWeight } from '../models/interest-weight';
import { Person } from '../models/person';
import { TokenMark } from '../models/token-mark';
export interface Interest {

  /**
   * The agent mark of the write that set the stake as it stands, in the person's name (docs/adr/0036 D6)
   */
  agent: (string | null);
  note: string;
  person: Person;

  /**
   * The ticket is done or dropped; the stake stays on record (docs/adr/0013 D5)
   */
  settled: boolean;
  since: string;

  /**
   * The token that write came through; null for the person's own browser session (docs/adr/0036 D6)
   */
  token: (TokenMark | null);
  updated_at: string;
  weight: InterestWeight;
}
