/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LinkType } from '../models/link-type';
import { Person } from '../models/person';
import { TicketRef } from '../models/ticket-ref';
export interface Link {
  created_at: string;
  created_by: Person;

  /**
   * Outgoing when the ticket read is the link's source; relates-to is stored once
   */
  direction: 'outgoing' | 'incoming';
  id: string;

  /**
   * The link read from this ticket: blocks, blocked by, relates to, duplicates, duplicated by, found in, found here
   */
  name: string;
  ticket: TicketRef;
  type: LinkType;
}
