/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LinkType } from './link-type';

/**
 * Each possible value of `LinkType`
 */
export const LINK_TYPE: LinkType[] = [
  'blocks',
  'relates-to',
  'duplicates',
  'found-in'
];