/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocalLoginRequest {
  password: string;

  /**
   * Trimmed and lower-cased by the server; a value that cannot be a username is a failed login like any other
   */
  username: string;
}
