/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Membership } from '../models/membership';
export interface Me {
  display_name: string;

  /**
   * The person is a global administrator: they create teams and hold no role
   * in any of them until they grant themselves one (docs/adr/0004 D4,
   * docs/adr/0034 D2)
   */
  global_admin: boolean;
  id: string;

  /**
   * The person has a local account, a password of their own (docs/adr/0033)
   */
  local: boolean;
  memberships: Array<Membership>;

  /**
   * The account's password is temporary: a session can do nothing but change
   * it, read this answer and log out until it has (docs/adr/0033 D4)
   */
  password_change_required: boolean;
  username?: (string | null);
}
