/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MemberToken } from '../models/member-token';
export interface MemberTokenList {
  items: Array<MemberToken>;

  /**
   * The cursor of the next page; null at the end, and on a numbered page
   */
  next_cursor: (string | null);
  page?: number;
  per_page?: number;

  /**
   * With page and per_page only
   */
  total?: number;
}
