/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipSource } from './membership-source';

/**
 * Each possible value of `MembershipSource`
 */
export const MEMBERSHIP_SOURCE: MembershipSource[] = [
  'mapping',
  'grant'
];