/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Member } from '../models/member';
export interface MemberList {
  items: Array<Member>;
  next_cursor: (string | null);
}
