/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipSource } from '../models/membership-source';
import { Role } from '../models/role';
export interface MembershipOrigin {
  role: Role;
  source: MembershipSource;
}
