/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
import { TenantRef } from '../models/tenant-ref';
export interface Membership {
  role: Role;
  tenant: TenantRef;
}
