/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from '../models/capability';
import { Person } from '../models/person';
import { Scope } from '../models/scope';
import { TokenState } from '../models/token-state';

/**
 * A member's token that can act in the team, as its administrators see it (docs/adr/0035 D5):
 * its person and its metadata, never its secret, hash or prefix
 */
export interface MemberToken {

  /**
   * The agent flag; every request of the token is an agent's (docs/adr/0036 D2)
   */
  agent: boolean;
  capabilities: Array<Capability>;
  created_at: string;
  expires_at: string;
  id: string;

  /**
   * The last day it was used, wherever; for an unrestricted token possibly in another team
   */
  last_used_on: (string | null);

  /**
   * The name its person gave it, free text that may say more than what it is for
   */
  name: string;
  person: Person;

  /**
   * The key of the project of this team the token is restricted to; null for none
   */
  restricted_project: (string | null);

  /**
   * This team's slug for a token restricted to it; null for an unrestricted token, which reaches
   * every team its person belongs to, so revoking it ends it in all of them
   */
  restricted_team: (string | null);

  /**
   * Deprecated, replaced by `restricted_team`, which it repeats; kept in /api/v1 for one release and removed in a later one (docs/adr/0005 D1, docs/adr/0046 D7)
   *
   * @deprecated
   */
  restricted_tenant: (string | null);
  revoked_at: (string | null);
  scope: Scope;
  state: TokenState;
}
