/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipOrigin } from '../models/membership-origin';
import { Role } from '../models/role';
import { TenantRef } from '../models/tenant-ref';
export interface Membership {

  /**
   * Where the role comes from, each source with its own role; `role` is the
   * higher of them (docs/adr/0030 D4)
   */
  origins: Array<MembershipOrigin>;
  role: Role;
  tenant: TenantRef;
}
