/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipOrigin } from '../models/membership-origin';
import { Role } from '../models/role';
import { TeamRef } from '../models/team-ref';
export interface Membership {

  /**
   * Where the role comes from, each source with its own role; `role` is the
   * higher of them (docs/adr/0030 D4)
   */
  origins: Array<MembershipOrigin>;
  role: Role;
  team: TeamRef;

  /**
   * Deprecated, replaced by `team`, which it repeats; kept in /api/v1 for one release and removed in a later one (docs/adr/0005 D1, docs/adr/0046 D7)
   *
   * @deprecated
   */
  tenant: TeamRef;
}
