/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
import { Role } from '../models/role';
export interface Member {
  person: Person;
  role: Role;
}
