/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Project } from '../models/project';
import { TeamRef } from '../models/team-ref';

/**
 * A project of one of the person's teams, with its team (docs/adr/0023 D2)
 */
export interface MyProject {
  project: Project;
  team: TeamRef;
}
