/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantRef } from '../models/tenant-ref';
import { Ticket } from '../models/ticket';
export interface MyTicket {
  tenant: TenantRef;
  ticket: Ticket;
}
