/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
export interface OrphanRemovalRecord {

  /**
   * The orphans that had gained metadata by then and were kept
   */
  kept: number;

  /**
   * The orphans whose removal was confirmed and tried
   */
  removed: number;
  removed_at: string;
  removed_by: Person;
}
