/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Person {
  display_name: string;
  id: string;

  /**
   * The local identity's username, `local:<username>` (docs/adr/0033 D2)
   */
  username?: (string | null);
}
