/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
import { TicketState } from '../models/ticket-state';

/**
 * A ticket of a prerequisite tree, or of its upward reading, the dependents (docs/adr/0012 D6)
 */
export interface PrerequisiteNode {
  assignee: (Person | null);

  /**
   * The state a blocked ticket came from; null unless it is blocked (docs/adr/0009 D2)
   */
  blocked_from: (TicketState | null);

  /**
   * 1 for a ticket next to the one asked about — blocking it, or blocked by it read upward
   */
  depth: number;

  /**
   * The canonical key; a ticket of another project names it
   */
  key: string;

  /**
   * The implementation stage as the ticket shows it (docs/adr/0017 D2, D3)
   */
  progress: number;

  /**
   * The stages are derived from the ticket's children
   */
  progress_derived: boolean;
  progress_refinement: number;
  progress_review: number;

  /**
   * The ticket stands in the tree in full under another ticket; here it is shown without what lies behind it
   */
  repeated: boolean;

  /**
   * Done or dropped (docs/adr/0012 D6)
   */
  settled: boolean;
  state: TicketState;
  title: string;
}
