/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PrerequisiteNode } from '../models/prerequisite-node';
export interface PrerequisiteTree {
  items: Array<PrerequisiteNode>;
  next_cursor: (string | null);

  /**
   * The open tickets of the whole tree the caller can see, each counted once, on every page
   */
  open: number;
}
