/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NodeProgress } from '../models/node-progress';
import { Person } from '../models/person';
import { TicketHead } from '../models/ticket-head';
import { TicketState } from '../models/ticket-state';

/**
 * A ticket of a prerequisite tree, or of its upward reading, across teams (docs/adr/0012 D6 as
 * amended 2026-10-10), by its head. The walk goes on only from a ticket the reader reads: a head
 * and a placeholder are leaves, what lies behind them stays behind their team's membership
 * (docs/adr/0005 D3, docs/adr/0065 D5).
 */
export interface PrerequisiteHeadNode {

  /**
   * The assignee, of a ticket of the reader's own team they read; null otherwise and without one
   */
  assignee: (Person | null);

  /**
   * The state a blocked ticket came from; null unless it is blocked, and for a placeholder
   */
  blocked_from: (TicketState | null);

  /**
   * 1 for a ticket next to the one asked about — blocking it, or blocked by it read upward
   */
  depth: number;
  head: TicketHead;

  /**
   * The stages, of a ticket of the reader's own team they read; null otherwise
   */
  progress: (NodeProgress | null);

  /**
   * The ticket stands in the tree in full under another ticket; here it is shown without what lies behind it
   */
  repeated: boolean;

  /**
   * Done or dropped (docs/adr/0012 D6); null for a placeholder, whose state the reader may not read
   */
  settled: (boolean | null);
}
