/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectAccessRole } from '../models/project-access-role';
export interface ProjectAccessSet {
  role: ProjectAccessRole;
}
