/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WipLimits } from '../models/wip-limits';
export interface ProjectPatch {
  description?: string;
  name?: string;
  wip_limits?: WipLimits;
}
