/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectRankSorted {

  /**
   * How many of the open tickets the caller sees changed their place; 0 when the rank followed the score already
   */
  moved: number;

  /**
   * The version of the score function the rank was sorted by (docs/adr/0014 D4)
   */
  score_version: number;
}
