/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WipLimits } from '../models/wip-limits';
export interface Project {
  archived_at?: (string | null);
  created_at: string;
  description: string;
  id: string;
  key: string;
  name: string;

  /**
   * Visible to administrators and the people on its list only (docs/adr/0034 D3)
   */
  restricted: boolean;
  updated_at: string;
  version: number;
  wip_limits: WipLimits;
}
