/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The most a person on a restricted project's access list may do in it (docs/adr/0034 D3)
 */
export type ProjectAccessRole = 'viewer' | 'member';

