/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectAccessEntry } from '../models/project-access-entry';
export interface ProjectAccessList {
  items: Array<ProjectAccessEntry>;
  next_cursor: (string | null);
}
