/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProposalTeam {

  /**
   * The project key proposed for this team, free there (docs/adr/0066 D2)
   */
  key: string;
  name: string;
  slug: string;
}
