/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PullRequestKind } from './pull-request-kind';

/**
 * Each possible value of `PullRequestKind`
 */
export const PULL_REQUEST_KIND: PullRequestKind[] = [
  'pull_request',
  'commit'
];