/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PullRequestFoundIn } from './pull-request-found-in';

/**
 * Each possible value of `PullRequestFoundIn`
 */
export const PULL_REQUEST_FOUND_IN: PullRequestFoundIn[] = [
  'trailer',
  'body',
  'subject'
];