/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PullRequest } from '../models/pull-request';
export interface PullRequestList {
  items: Array<PullRequest>;
  next_cursor: (string | null);
}
