/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QuestionStatus } from './question-status';

/**
 * Each possible value of `QuestionStatus`
 */
export const QUESTION_STATUS: QuestionStatus[] = [
  'open',
  'answered',
  'withdrawn'
];