/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuestionPatch {
  asked_of?: (string | null);
  options?: string;
  question?: string;
  recommendation?: string;
}
