/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
import { QuestionStatus } from '../models/question-status';
export interface Question {

  /**
   * Markdown
   */
  answer: (string | null);
  answered_at: (string | null);

  /**
   * The person whose answer it is, also when an agent wrote it down
   */
  answered_by: (Person | null);
  asked_by: Person;

  /**
   * The agent mark of the request that asked
   */
  asked_by_agent: (string | null);

  /**
   * The person asked; null for a question open in the tenant
   */
  asked_of: (Person | null);
  created_at: string;
  id: string;

  /**
   * Stable within the ticket: Q<n> (docs/adr/0011 D4)
   */
  number: number;

  /**
   * Markdown: the context and the options
   */
  options: string;
  question: string;
  recommendation: string;

  /**
   * An agent wrote the person's answer down (docs/adr/0066 D8)
   */
  recorded_by_agent: boolean;
  status: QuestionStatus;
  updated_at: string;
  version: number;
  withdrawn_at: (string | null);
}
