/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Relation } from '../models/relation';
export interface RelationList {
  items: Array<Relation>;
  next_cursor: (string | null);
}
