/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RelationLink } from '../models/relation-link';
import { TicketHead } from '../models/ticket-head';

/**
 * A relation of a ticket — its parent, a child, a link in either direction — and the ticket at its
 * other end as the reader sees it, of any project or team (docs/adr/0005 D3, docs/adr/0008 D2,
 * docs/adr/0012 D2)
 */
export interface Relation {
  head: TicketHead;

  /**
   * The relation's id, by which a writer of the ticket removes it (docs/adr/0008 D2,
   * docs/adr/0012 D2 as amended 2026-10-10): a link's id, which `DELETE …/links/{link}` takes;
   * for a child an opaque handle, which `DELETE …/children/{child}` takes and which shows no id
   * of the child; null for the parent, which the update of `parent` removes
   */
  id: (string | null);
  kind: 'parent' | 'child' | 'link';

  /**
   * The link of a relation of the kind `link`; null for a parent and a child
   */
  link: (RelationLink | null);
}
