/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LookupRemote } from '../models/lookup-remote';
import { RepositoryBindingRef } from '../models/repository-binding-ref';
import { RepositoryProposal } from '../models/repository-proposal';
export interface RepositoryLookup {
  bindings: Array<RepositoryBindingRef>;
  proposal: (RepositoryProposal | null);

  /**
   * Why an unbound repository has no proposal, when it has none
   */
  proposal_unavailable: (string | null);
  remotes: Array<LookupRemote>;

  /**
   * One binding, several (a data error the person resolves, docs/adr/0066 D6), or none
   */
  status: 'bound' | 'ambiguous' | 'unbound';
}
