/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectRef } from '../models/project-ref';
import { TeamRef } from '../models/team-ref';

/**
 * A project that binds the repository
 */
export interface RepositoryBindingRef {

  /**
   * The project is archived and refuses new tickets (docs/adr/0006 D4)
   */
  archived: boolean;
  identity: string;
  path: string;
  project: ProjectRef;
  remote: string;
  team: TeamRef;

  /**
   * Deprecated, replaced by `team`, which it repeats; kept in /api/v1 for one release and removed in a later one (docs/adr/0005 D1, docs/adr/0046 D7)
   *
   * @deprecated
   */
  tenant: TeamRef;
}
