/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Repository } from '../models/repository';
export interface RepositoryList {
  items: Array<Repository>;
  next_cursor: (string | null);
}
