/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from '../models/capability';
export interface RequestMark {

  /**
   * The request is an agent's, by the token's flag or by the X-Cowork-Agent header (docs/adr/0036 D2, D3)
   */
  agent: boolean;

  /**
   * The agent its acts record — the header's value, or unknown-agent; null for a person's request
   */
  agent_mark: (string | null);

  /**
   * What an agent's request may do beyond the baseline: the token's set for a flagged token,
   * every capability for a plain token the header marks (docs/adr/0043 D4), the person's chat
   * capabilities for a session the header marks (D5); empty for a person's request, which the
   * capabilities do not bound
   */
  capabilities: Array<Capability>;
}
