/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The filter parameters of the ticket lists (docs/adr/0049 D1, D2) as a JSON object: each
 * repeatable parameter an array of its values — `!` negates one —, the bounds and the booleans
 * single values. What a list's query string would carry, without the paging.
 */
export interface SavedFilterParameters {
  assignee?: Array<string>;
  blocked?: boolean;
  done_after?: string;
  effort?: Array<string>;
  has_open_questions?: boolean;
  include_terminal?: boolean;
  interest?: Array<string>;
  opened_after?: string;
  opened_before?: string;
  parent?: Array<string>;
  progress_max?: number;
  progress_min?: number;
  project?: Array<string>;
  q?: string;
  reporter?: Array<string>;
  security?: Array<string>;
  severity?: Array<string>;
  state?: Array<string>;
  type?: Array<string>;
  updated_after?: string;
  updated_before?: string;
  urgency?: Array<string>;
}
