/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SavedFilterParameters } from '../models/saved-filter-parameters';
export interface SavedFilterCreate {
  name: string;
  parameters: SavedFilterParameters;
  shared?: boolean;
}
