/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SavedFilter } from '../models/saved-filter';
export interface SavedFilterList {
  items: Array<SavedFilter>;
  next_cursor: (string | null);
}
