/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Where a search hit matched (docs/adr/0025 D5): the ticket's key; its own text, the title and
 * the body; one of its comments; one of its questions; an attachment's file name
 */
export type SearchFoundIn = 'key' | 'ticket' | 'comment' | 'question' | 'attachment';

