/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityClass } from './security-class';

/**
 * Each possible value of `SecurityClass`
 */
export const SECURITY_CLASS: SecurityClass[] = [
  'live',
  'boundary',
  'hardening',
  'none'
];