/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Severity } from './severity';

/**
 * Each possible value of `Severity`
 */
export const SEVERITY: Severity[] = [
  'critical',
  'high',
  'medium',
  'low',
  'cosmetic'
];