/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SnippetPart {

  /**
   * The piece is a word the query found
   */
  match: boolean;

  /**
   * A piece of the matched text, as text
   */
  text: string;
}
