/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Team {
  created_at: string;

  /**
   * Members create projects; off, only administrators do (docs/adr/0034 D9)
   */
  members_create_projects: boolean;
  name: string;
  slug: string;

  /**
   * Time entries on or before this date cannot change (docs/adr/0017 D8)
   */
  time_locked_until?: (string | null);

  /**
   * Members see every time entry of the projects they see, not only their own (docs/adr/0034 D5)
   */
  time_visible_to_members: boolean;
  updated_at: string;
  version: number;
}
