/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface TenantSummary {
  name: string;

  /**
   * The role the caller holds in the tenant, the higher of their mapping and
   * their grant; null where they hold none (docs/adr/0034 D2)
   */
  role: (Role | null);
  slug: string;
}
