/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketType } from './ticket-type';

/**
 * Each possible value of `TicketType`
 */
export const TICKET_TYPE: TicketType[] = [
  'task',
  'bug',
  'feature',
  'decision',
  'question'
];