/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketState } from '../models/ticket-state';
export interface TicketRef {
  key: string;
  state: TicketState;
  title: string;
}
