/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TeamRef } from '../models/team-ref';
import { TicketState } from '../models/ticket-state';
import { TicketType } from '../models/ticket-type';

/**
 * A ticket at the other end of a relation — a parent, a child, a link — as the reader sees it
 * (docs/adr/0005 D3, docs/adr/0065 D5): its team, and its key, title, type and state, which is all
 * a reader who holds no role in its team, or to whom its project is restricted, reads of it
 * (docs/adr/0034 D4). A ticket the reader may not see is the placeholder, `<team> [Confidential]`:
 * its team and nothing else, the key, the title, the type and the state null — in another team
 * or in the reader's own.
 */
export interface TicketHead {

  /**
   * The canonical key, <team>/<PROJECT>-<number>; null for the placeholder
   */
  key: (string | null);

  /**
   * The reader may not see the ticket; it shows as `<team> [Confidential]`
   */
  placeholder: boolean;

  /**
   * The reader reads the ticket and may open it; a head they may not open is false
   */
  readable: boolean;
  state: (TicketState | null);
  team: TeamRef;
  title: (string | null);
  type: (TicketType | null);
}
