/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Effort } from '../models/effort';
import { Horizon } from '../models/horizon';
import { SecurityClass } from '../models/security-class';
import { Severity } from '../models/severity';
import { TicketType } from '../models/ticket-type';
import { Urgency } from '../models/urgency';
export interface TicketCreate {

  /**
   * The open ticket of the same horizon this one is filed directly after; not with before
   */
  after?: number;

  /**
   * A member of the tenant
   */
  assignee?: string;

  /**
   * The open ticket of the same horizon this one is filed directly before; not with after
   */
  before?: number;
  body?: string;
  effort: Effort;

  /**
   * The horizon the ticket is filed into; later when left out (docs/adr/0010 D3)
   */
  horizon?: Horizon;

  /**
   * A ticket key of the same project, short or full
   */
  parent?: string;
  security: SecurityClass;
  severity: Severity;
  threat?: string;
  title: string;
  type: TicketType;

  /**
   * The horizon under the name it had before (docs/adr/0010 D1); replaced by `horizon`, and with it
   * another value is 400 at `/horizon`; removed in a later release (docs/adr/0046 D7)
   *
   * @deprecated
   */
  urgency?: Urgency;
}
