/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Ticket } from '../models/ticket';
export interface TicketList {
  items: Array<Ticket>;
  next_cursor: (string | null);
  page?: number;
  per_page?: number;

  /**
   * With page and per_page only
   */
  total?: number;
}
