/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketBodyReplace {
  body: string;

  /**
   * A comment that explains this act, written with it; the act points at it (docs/adr/0015 D2)
   */
  comment?: string;
}
