/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Block } from '../models/block';
import { Effort } from '../models/effort';
import { Horizon } from '../models/horizon';
import { HorizonSet } from '../models/horizon-set';
import { Person } from '../models/person';
import { SecurityClass } from '../models/security-class';
import { Severity } from '../models/severity';
import { TicketState } from '../models/ticket-state';
import { TicketType } from '../models/ticket-type';
import { TokenMark } from '../models/token-mark';
import { Urgency } from '../models/urgency';
import { UrgencyOverride } from '../models/urgency-override';
export interface Ticket {
  assignee: (Person | null);
  block: (Block | null);

  /**
   * Markdown, the current state, replaced as a whole (docs/adr/0011 D1)
   */
  body: string;

  /**
   * Visible to the tenant's administrators, the assignee and the reporter only (docs/adr/0065)
   */
  confidential: boolean;
  created_at: string;
  decided_at: (string | null);
  done_at: (string | null);

  /**
   * Done by hand rather than by its three stages: the stages stay editable and the ticket stays
   * done until the done by hand is withdrawn (docs/adr/0009 D5). False while the ticket is not done.
   */
  done_by_hand: boolean;

  /**
   * The state the ticket was done from, while it is done (docs/adr/0009 D5)
   */
  done_from: (TicketState | null);
  effort: Effort;
  horizon: Horizon;

  /**
   * The horizon a person or an agent set; null for a ticket nobody placed, which stands in later
   */
  horizon_set: (HorizonSet | null);
  id: string;

  /**
   * The canonical key, <tenant>/<PROJECT>-<number> (docs/adr/0007 D2)
   */
  key: string;
  number: number;

  /**
   * The open tickets that block this one and that the caller can see (docs/adr/0012 D7,
   * docs/adr/0018 D1); a ticket the caller cannot see is never counted
   */
  open_prerequisites: number;
  opened_at: string;

  /**
   * The parent's key
   */
  parent: (string | null);

  /**
   * The implementation stage, the work of in-progress; derived from the children while there are any
   * (docs/adr/0017 D2, D3). Done leaves it as it is.
   */
  progress: number;

  /**
   * The three stages are derived from the children and take no manual value; such a ticket is never done by them
   */
  progress_derived: boolean;

  /**
   * The refinement stage, the work of filed and analysed; derived like progress (docs/adr/0017 D2, D3)
   */
  progress_refinement: number;

  /**
   * The review stage, the work of review; derived like progress (docs/adr/0017 D2, D3)
   */
  progress_review: number;

  /**
   * The project's key
   */
  project: string;
  reporter: Person;

  /**
   * The agent mark of the request that filed the ticket in the reporter's name (docs/adr/0036 D6)
   */
  reporter_agent: (string | null);

  /**
   * The token the ticket was filed through; null for a browser session (docs/adr/0036 D6)
   */
  reporter_token: (TokenMark | null);

  /**
   * The score at the moment of the read, to one decimal (docs/adr/0014 D3, D4): the weights of
   * the severity, the horizon and the `need` and `urgent` stakes, plus one for every thirty days
   * since `opened_at`. It warns where the facts disagree with the project's rank and orders the
   * person-level lists; it never moves the rank. Null for a done or dropped ticket, and for one a
   * release before the score filed until an input of it changes.
   */
  score: (number | null);

  /**
   * The version of the function that computed `score` (docs/adr/0014 D4); null with it
   */
  score_version: (number | null);
  security: SecurityClass;
  severity: Severity;
  state: TicketState;
  threat: (string | null);
  title: string;
  type: TicketType;
  updated_at: string;

  /**
   * The horizon under the name it had before (docs/adr/0010 D1): the same value as `horizon`, which
   * replaces it; removed in a later release (docs/adr/0046 D7)
   *
   * @deprecated
   */
  urgency: Urgency;

  /**
   * What rule set v2 derives, `later` for every ticket since nothing derives a horizon any more
   * (docs/adr/0010 D3); removed in a later release (docs/adr/0046 D7)
   *
   * @deprecated
   */
  urgency_derived: Urgency;

  /**
   * The set horizon under the name it had before (docs/adr/0010 D1): what `horizon_set` holds, which
   * replaces it; removed in a later release (docs/adr/0046 D7)
   *
   * @deprecated
   */
  urgency_override: (UrgencyOverride | null);

  /**
   * The rule that derived `urgency_derived`: v2:default for every ticket since 2026-10-04
   * (docs/adr/0010 D3); removed in a later release (docs/adr/0046 D7)
   *
   * @deprecated
   */
  urgency_rule: string;
  version: number;
}
