/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Effort } from '../models/effort';
import { SecurityClass } from '../models/security-class';
import { Severity } from '../models/severity';
import { TicketType } from '../models/ticket-type';
import { Urgency } from '../models/urgency';
export interface TicketCreate {

  /**
   * The open ticket of the same horizon this one is filed directly after; not with before
   */
  after?: number;

  /**
   * A member of the tenant
   */
  assignee?: string;

  /**
   * The open ticket of the same horizon this one is filed directly before; not with after
   */
  before?: number;
  body?: string;
  effort: Effort;

  /**
   * A ticket key of the same project, short or full
   */
  parent?: string;
  security: SecurityClass;
  severity: Severity;
  threat?: string;
  title: string;
  type: TicketType;
  urgency?: Urgency;
}
