/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeReport {

  /**
   * As asked; `tenant` is the deprecated name of `team` (docs/adr/0005 D1, docs/adr/0046 D7)
   */
  group_by: 'ticket' | 'project' | 'person' | 'team' | 'tenant';
  items: Array<{

/**
 * The ticket key, the project key, the person id, or `team` — `tenant` under the deprecated `group_by=tenant`
 */
'key': string;
'label': string;
'minutes': number;
}>;
  total_minutes: number;
}
