/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Person } from '../models/person';
export interface TimeEntry {
  author: Person;
  created_at: string;

  /**
   * The day worked
   */
  day: string;
  edited: boolean;
  id: string;
  minutes: number;
  note: string;
  person: Person;

  /**
   * The ticket's key
   */
  ticket: string;
  updated_at: string;
  version: number;

  /**
   * Kept and excluded from every sum (docs/adr/0017 D7)
   */
  voided: boolean;
  voided_at: (string | null);
}
