/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The personal access token an act came through (docs/adr/0036 D6): its id and its name as the act
 * recorded it, readable by whoever reads the act — never the token's secret, hash or prefix. A
 * revoked or expired token's acts keep its name.
 */
export interface TokenMark {
  id: string;

  /**
   * The token's name; null only on an act of the activity recorded before cowork kept the name,
   * which says that a token was used, not which one
   */
  name: (string | null);
}
