/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from '../models/capability';
import { Scope } from '../models/scope';
import { TokenState } from '../models/token-state';
export interface Token {

  /**
   * The agent flag; every request of the token is an agent's (docs/adr/0036 D2)
   */
  agent: boolean;
  capabilities: Array<Capability>;
  created_at: string;
  expires_at: string;
  id: string;
  last_used_on?: (string | null);
  name: string;

  /**
   * The key of the project the token is restricted to (docs/adr/0035 D3); null for a token
   * without a project restriction, and for one whose project the person no longer sees or
   * whose team they no longer belong to — such a token reaches nothing
   */
  restricted_project: (string | null);

  /**
   * The id of the project the token is restricted to. Replaced by `restricted_project`, which
   * names the project by its key, as a person knows it; kept in `/api/v1` for the clients that
   * read it, since taking a field away is a breaking change (docs/adr/0046 D7)
   *
   * @deprecated
   */
  restricted_project_id?: (string | null);

  /**
   * The slug of the team the token is restricted to
   */
  restricted_team?: (string | null);

  /**
   * Deprecated, replaced by `restricted_team`, which it repeats; kept in /api/v1 for one release and removed in a later one (docs/adr/0005 D1, docs/adr/0046 D7)
   *
   * @deprecated
   */
  restricted_tenant?: (string | null);
  revoked_at?: (string | null);
  scope: Scope;
  state: TokenState;
}
