/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from '../models/capability';
import { Scope } from '../models/scope';
import { TokenState } from '../models/token-state';
export interface Token {

  /**
   * The agent flag; every request of the token is an agent's (docs/adr/0036 D2)
   */
  agent: boolean;
  capabilities: Array<Capability>;
  created_at: string;
  expires_at: string;
  id: string;
  last_used_on?: (string | null);
  name: string;

  /**
   * The id of the project the token is restricted to
   */
  restricted_project_id?: (string | null);

  /**
   * The slug of the tenant the token is restricted to
   */
  restricted_tenant?: (string | null);
  revoked_at?: (string | null);
  scope: Scope;
  state: TokenState;
}
