/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Token } from '../models/token';

/**
 * A token as listed, and its plaintext in the answer that created it
 */
export type TokenCreated = Token & {

/**
 * The plaintext, `cwk_` and 43 base62 characters, shown once: cowork
 * keeps its SHA-256 only (docs/adr/0035 D1). An answer replayed for an
 * `Idempotency-Key` leaves it out.
 */
'token'?: string;
};

