/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Capability } from '../models/capability';
import { Scope } from '../models/scope';
export interface TokenCreate {

  /**
   * The agent flag; it cannot be changed afterwards (docs/adr/0036 D2)
   */
  agent?: boolean;

  /**
   * Only with `agent`; omitted, an agent token gets every capability, and an empty list gives it none, the baseline only (docs/adr/0043 D4)
   */
  capabilities?: Array<Capability>;

  /**
   * Days until the token expires; by default `COWORK_TOKEN_DEFAULT_LIFETIME`,
   * shortened to `COWORK_TOKEN_MAX_LIFETIME` when longer (docs/adr/0035 D4)
   */
  lifetime_days?: number;

  /**
   * Shown beside every act made through the token — in a ticket's activity, on its comments,
   * questions, answers, files and time — to whoever reads the act, and kept there after the token is
   * revoked (docs/adr/0036 D6)
   */
  name: string;

  /**
   * The key of the project of that tenant the token is restricted to; needs `tenant`
   */
  project?: string;
  scope: Scope;

  /**
   * The slug of the tenant the token is restricted to
   */
  tenant?: string;
}
