/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TokenState } from './token-state';

/**
 * Each possible value of `TokenState`
 */
export const TOKEN_STATE: TokenState[] = [
  'active',
  'expired',
  'revoked'
];