/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Urgency } from './urgency';

/**
 * Each possible value of `Urgency`
 */
export const URGENCY: Urgency[] = [
  'now',
  'release',
  'next',
  'later',
  'icebox'
];