/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Urgency } from '../models/urgency';

/**
 * The body of the deprecated `overrideUrgency`; replaced by `HorizonUpdate` and `setHorizon`, and
 * removed in a later release (docs/adr/0046 D7)
 *
 * @deprecated
 */
export interface UrgencyOverrideSet {

  /**
   * Optional for a person, required of an agent (docs/adr/0010 D3)
   */
  reason?: string;
  value: Urgency;
}
