/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Advisory work-in-progress limits per state; information, never a gate (docs/adr/0019 D3)
 */
export interface WipLimits {
  analysed?: number;
  blocked?: number;
  decided?: number;
  'in-progress'?: number;
}
