/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Advisory work-in-progress limits per state; information, never a gate (docs/adr/0019 D3). The
 * board's Refinement column, which holds filed and analysed, counts against the analysed limit.
 */
export interface WipLimits {
  analysed?: number;
  blocked?: number;
  decided?: number;
  'in-progress'?: number;
  review?: number;
}
