/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Repository } from '../../models/repository';
import { RepositoryBind } from '../../models/repository-bind';

export interface BindRepository$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * A UUID the client generates per act and repeats on every retry of it; an
 * agent's POST requires one (docs/adr/0045 D3, D4).
 */
  'Idempotency-Key'?: string;
      body: RepositoryBind
}

export function bindRepository(http: HttpClient, rootUrl: string, params: BindRepository$Params, context?: HttpContext): Observable<StrictHttpResponse<Repository>> {
  const rb = new RequestBuilder(rootUrl, bindRepository.PATH, 'post');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.path('project', params.project, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Repository>;
    })
  );
}

bindRepository.PATH = '/api/v1/tenants/{tenant}/projects/{project}/repositories';
