/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RepositoryLookup } from '../../models/repository-lookup';

export interface LookupRepository$Params {

/**
 * A git remote URL — SSH, scp-style, git or HTTP(S); repeatable, in order of preference
 */
  remote: Array<string>;

/**
 * The working directory relative to the repository root, for a monorepo's sub-directory bindings
 */
  path?: string;
}

export function lookupRepository(http: HttpClient, rootUrl: string, params: LookupRepository$Params, context?: HttpContext): Observable<StrictHttpResponse<RepositoryLookup>> {
  const rb = new RequestBuilder(rootUrl, lookupRepository.PATH, 'get');
  if (params) {
    rb.query('remote', params.remote, {"style":"form","explode":true});
    rb.query('path', params.path, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RepositoryLookup>;
    })
  );
}

lookupRepository.PATH = '/api/v1/me/repositories/lookup';
