/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UnbindRepository$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The binding's id
 */
  repository: string;
}

export function unbindRepository(http: HttpClient, rootUrl: string, params: UnbindRepository$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, unbindRepository.PATH, 'delete');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('repository', params.repository, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

unbindRepository.PATH = '/api/v1/teams/{team}/projects/{project}/repositories/{repository}';
