/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Attachment } from '../../models/attachment';

export interface GetAttachment$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * The attachment's id
 */
  attachment: string;
}

export function getAttachment(http: HttpClient, rootUrl: string, params: GetAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<Attachment>> {
  const rb = new RequestBuilder(rootUrl, getAttachment.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.path('attachment', params.attachment, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Attachment>;
    })
  );
}

getAttachment.PATH = '/api/v1/teams/{team}/projects/{project}/tickets/{number}/attachments/{attachment}';
