/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsistencyCheckRef } from '../../models/consistency-check-ref';
import { OrphanRemoval } from '../../models/orphan-removal';

export interface RemoveOrphanedObjects$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;
      body: ConsistencyCheckRef
}

export function removeOrphanedObjects(http: HttpClient, rootUrl: string, params: RemoveOrphanedObjects$Params, context?: HttpContext): Observable<StrictHttpResponse<OrphanRemoval>> {
  const rb = new RequestBuilder(rootUrl, removeOrphanedObjects.PATH, 'post');
  if (params) {
    rb.path('team', params.team, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrphanRemoval>;
    })
  );
}

removeOrphanedObjects.PATH = '/api/v1/teams/{team}/attachment-consistency/orphan-removal';
