/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Attachment } from '../../models/attachment';

export interface UploadAttachment$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * A UUID the client generates per act and repeats on every retry of it; an
 * agent's POST requires one (docs/adr/0045 D3, D4).
 */
  'Idempotency-Key'?: string;
  
    /**
     * Two parts and no other: `file`, the one file, whose `filename` in its `Content-Disposition`
     * becomes the attachment's `file_name`, sanitised (docs/adr/0016 D1); and `comment_id`,
     * optional, the id of a comment of the ticket the file belongs to.
     */
    body: {
'comment_id'?: string;
'file': Blob;
}
}

export function uploadAttachment(http: HttpClient, rootUrl: string, params: UploadAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<Attachment>> {
  const rb = new RequestBuilder(rootUrl, uploadAttachment.PATH, 'post');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Attachment>;
    })
  );
}

uploadAttachment.PATH = '/api/v1/teams/{team}/projects/{project}/tickets/{number}/attachments';
