/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface StreamEvents$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The id of the last event the client received
 */
  'Last-Event-ID'?: string;

/**
 * Carries the events of every team of the person and their unread count (docs/adr/0054 D1)
 */
  me?: boolean;
}

export function streamEvents(http: HttpClient, rootUrl: string, params: StreamEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, streamEvents.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.header('Last-Event-ID', params['Last-Event-ID'], {});
    rb.query('me', params.me, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/event-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

streamEvents.PATH = '/api/v1/teams/{team}/events';
