/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantSummaryList } from '../../models/tenant-summary-list';

export interface ListTenants$Params {

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;
}

export function listTenants(http: HttpClient, rootUrl: string, params?: ListTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantSummaryList>> {
  const rb = new RequestBuilder(rootUrl, listTenants.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantSummaryList>;
    })
  );
}

listTenants.PATH = '/api/v1/tenants';
