/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupMapping } from '../../models/group-mapping';
import { GroupMappingPatch } from '../../models/group-mapping-patch';

export interface UpdateGroupMapping$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The group mapping's id
 */
  mapping_id: string;

/**
 * The `ETag` of the version the client read. Required on overwriting writes:
 * without it the answer is 428, with a stale one 412 (docs/adr/0050 D3).
 */
  'If-Match'?: string;
      body: GroupMappingPatch
}

export function updateGroupMapping(http: HttpClient, rootUrl: string, params: UpdateGroupMapping$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupMapping>> {
  const rb = new RequestBuilder(rootUrl, updateGroupMapping.PATH, 'patch');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.path('mapping_id', params.mapping_id, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupMapping>;
    })
  );
}

updateGroupMapping.PATH = '/api/v1/tenants/{tenant}/group-mappings/{mapping_id}';
