/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeReport } from '../../models/time-report';

export interface TimeReport$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The first day of the period, inclusive
 */
  from?: string;

/**
 * The last day of the period, inclusive
 */
  to?: string;

/**
 * A project key
 */
  project?: string;

/**
 * A person id, or me
 */
  person?: string;
  group_by?: 'ticket' | 'project' | 'person' | 'tenant';
}

export function timeReport(http: HttpClient, rootUrl: string, params: TimeReport$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeReport>> {
  const rb = new RequestBuilder(rootUrl, timeReport.PATH, 'get');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('project', params.project, {});
    rb.query('person', params.person, {});
    rb.query('group_by', params.group_by, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeReport>;
    })
  );
}

timeReport.PATH = '/api/v1/tenants/{tenant}/time-report';
