/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface TimeReport$Csv$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The first day of the period, inclusive
 */
  from?: string;

/**
 * The last day of the period, inclusive
 */
  to?: string;

/**
 * A project key
 */
  project?: string;

/**
 * A person id, or me
 */
  person?: string;

/**
 * What the report sums by. `team` sums the whole team in one row, keyed `team`; `tenant` is its
 * deprecated name, kept in /api/v1 for one release, which keys the row `tenant` as before
 * (docs/adr/0005 D1, docs/adr/0046 D7)
 */
  group_by?: 'ticket' | 'project' | 'person' | 'team' | 'tenant';
}

export function timeReport$Csv(http: HttpClient, rootUrl: string, params: TimeReport$Csv$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, timeReport$Csv.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('project', params.project, {});
    rb.query('person', params.person, {});
    rb.query('group_by', params.group_by, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

timeReport$Csv.PATH = '/api/v1/teams/{team}/time-report';
