/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface VoidTimeEntry$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The ticket's number in its project
 */
  number: number;

/**
 * The time entry's id
 */
  entry: string;
}

export function voidTimeEntry(http: HttpClient, rootUrl: string, params: VoidTimeEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntry>> {
  const rb = new RequestBuilder(rootUrl, voidTimeEntry.PATH, 'put');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.path('project', params.project, {});
    rb.path('number', params.number, {});
    rb.path('entry', params.entry, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntry>;
    })
  );
}

voidTimeEntry.PATH = '/api/v1/tenants/{tenant}/projects/{project}/tickets/{number}/time-entries/{entry}/void';
