/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportExecution } from '../../models/import-execution';
import { ImportJob } from '../../models/import-job';

export interface ExecuteImport$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The import job's id
 */
  import: string;
      body: ImportExecution
}

export function executeImport(http: HttpClient, rootUrl: string, params: ExecuteImport$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportJob>> {
  const rb = new RequestBuilder(rootUrl, executeImport.PATH, 'post');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.path('project', params.project, {});
    rb.path('import', params.import, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportJob>;
    })
  );
}

executeImport.PATH = '/api/v1/tenants/{tenant}/projects/{project}/imports/{import}/execution';
