/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportJob } from '../../models/import-job';

export interface GetImport$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * The import job's id
 */
  import: string;
}

export function getImport(http: HttpClient, rootUrl: string, params: GetImport$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportJob>> {
  const rb = new RequestBuilder(rootUrl, getImport.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('project', params.project, {});
    rb.path('import', params.import, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportJob>;
    })
  );
}

getImport.PATH = '/api/v1/teams/{team}/projects/{project}/imports/{import}';
