/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SearchHitList } from '../../models/search-hit-list';

export interface SearchMyTenants$Params {

/**
 * The words to find (docs/adr/0025); a text matches when it holds every one of them. Its length
 * is capped by the server, and a query of white space alone is `validation_failed`
 */
  q: string;

/**
 * Narrows a person-level list to one of the person's tenants (docs/adr/0023 D2); a slug that names
 * none of them is `404 not_found`, whether or not the tenant exists
 */
  tenant?: string;

/**
 * The opaque cursor of the previous page's `next_cursor` (docs/adr/0048 D1)
 */
  cursor?: string;

/**
 * Items per page; the server caps it at its configured maximum
 */
  limit?: number;
}

export function searchMyTenants(http: HttpClient, rootUrl: string, params: SearchMyTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<SearchHitList>> {
  const rb = new RequestBuilder(rootUrl, searchMyTenants.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('tenant', params.tenant, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SearchHitList>;
    })
  );
}

searchMyTenants.PATH = '/api/v1/me/search';
