{{- if and .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cowork.fullname" . }}-database
  labels:
    {{- include "cowork.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.database.url | quote }}
{{- end }}
{{- if and (include "cowork.initContainerMigrates" .) .Values.database.owner.url (not .Values.database.owner.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cowork.fullname" . }}-database-owner
  labels:
    {{- include "cowork.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.database.owner.url | quote }}
{{- end }}
{{- if and (not .Values.localAdmin.existingSecret) .Values.localAdmin.username .Values.localAdmin.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cowork.fullname" . }}-local-admin
  labels:
    {{- include "cowork.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.localAdmin.username | quote }}
  password: {{ .Values.localAdmin.password | quote }}
{{- end }}
