/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SavedFilter } from '../../models/saved-filter';

export interface GetSavedFilter$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;

/**
 * The saved filter's id
 */
  filter: string;
}

export function getSavedFilter(http: HttpClient, rootUrl: string, params: GetSavedFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<SavedFilter>> {
  const rb = new RequestBuilder(rootUrl, getSavedFilter.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
    rb.path('filter', params.filter, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SavedFilter>;
    })
  );
}

getSavedFilter.PATH = '/api/v1/teams/{team}/filters/{filter}';
