/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GitHubIntegration } from '../../models/git-hub-integration';

export interface GetGitHubIntegration$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;
}

export function getGitHubIntegration(http: HttpClient, rootUrl: string, params: GetGitHubIntegration$Params, context?: HttpContext): Observable<StrictHttpResponse<GitHubIntegration>> {
  const rb = new RequestBuilder(rootUrl, getGitHubIntegration.PATH, 'get');
  if (params) {
    rb.path('tenant', params.tenant, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GitHubIntegration>;
    })
  );
}

getGitHubIntegration.PATH = '/api/v1/tenants/{tenant}/integrations/github';
