// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package writeq

import (
	"context"

	"github.com/google/uuid"
)

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO attachments (id, tenant_id, ticket_id, comment_id, file_name, size, sha256, content_type, uploaded_by, agent,
                         token_id, token_name)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12)
`

type InsertAttachmentParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	TicketID    uuid.UUID
	CommentID   *uuid.UUID
	FileName    string
	Size        int64
	Sha256      []byte
	ContentType string
	UploadedBy  uuid.UUID
	Agent       *string
	TokenID     *uuid.UUID
	TokenName   *string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertAttachment,
		arg.ID,
		arg.TenantID,
		arg.TicketID,
		arg.CommentID,
		arg.FileName,
		arg.Size,
		arg.Sha256,
		arg.ContentType,
		arg.UploadedBy,
		arg.Agent,
		arg.TokenID,
		arg.TokenName,
	)
	return err
}
