// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package writeq

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, tenant_id, actor_user_id, actor_system, agent, agent_capabilities, token_id,
    entity_type, entity_id, ticket_id, ticket_key, action, before, after,
    reason, note, explained_by_comment_id, refs, idempotency_key, request_id, source_hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21
)
`

type InsertAuditEventParams struct {
	ID                   uuid.UUID
	TenantID             *uuid.UUID
	ActorUserID          *uuid.UUID
	ActorSystem          *string
	Agent                *string
	AgentCapabilities    []string
	TokenID              *uuid.UUID
	EntityType           string
	EntityID             *uuid.UUID
	TicketID             *uuid.UUID
	TicketKey            *string
	Action               string
	Before               []byte
	After                []byte
	Reason               *string
	Note                 *string
	ExplainedByCommentID *uuid.UUID
	Refs                 []uuid.UUID
	IdempotencyKey       *uuid.UUID
	RequestID            *uuid.UUID
	SourceHash           []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorUserID,
		arg.ActorSystem,
		arg.Agent,
		arg.AgentCapabilities,
		arg.TokenID,
		arg.EntityType,
		arg.EntityID,
		arg.TicketID,
		arg.TicketKey,
		arg.Action,
		arg.Before,
		arg.After,
		arg.Reason,
		arg.Note,
		arg.ExplainedByCommentID,
		arg.Refs,
		arg.IdempotencyKey,
		arg.RequestID,
		arg.SourceHash,
	)
	return err
}
