// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package writeq

import (
	"context"

	"github.com/google/uuid"
)

const getChatCapabilitiesForUpdate = `-- name: GetChatCapabilitiesForUpdate :one
SELECT capabilities
FROM chat_capabilities
WHERE user_id = $1
FOR UPDATE
`

// The person's chat capabilities as they stand, locked for the change.
func (q *Queries) GetChatCapabilitiesForUpdate(ctx context.Context, userID uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getChatCapabilitiesForUpdate, userID)
	var capabilities []string
	err := row.Scan(&capabilities)
	return capabilities, err
}

const setChatCapabilities = `-- name: SetChatCapabilities :exec
INSERT INTO chat_capabilities (user_id, capabilities)
VALUES ($1, $2::text[])
ON CONFLICT (user_id) DO UPDATE
SET capabilities = EXCLUDED.capabilities,
    updated_at = now()
`

type SetChatCapabilitiesParams struct {
	UserID       uuid.UUID
	Capabilities []string
}

// The person's choice of the chat's capabilities (docs/adr/0043 D5): written
// the first time, replaced afterwards.
func (q *Queries) SetChatCapabilities(ctx context.Context, arg SetChatCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, setChatCapabilities, arg.UserID, arg.Capabilities)
	return err
}
