// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package writeq

import (
	"context"

	"github.com/google/uuid"
)

const insertComment = `-- name: InsertComment :one
INSERT INTO comments (tenant_id, ticket_id, author_id, agent, token_id, token_name, body, mentions)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8::uuid[])
RETURNING id
`

type InsertCommentParams struct {
	TenantID  uuid.UUID
	TicketID  uuid.UUID
	AuthorID  uuid.UUID
	Agent     *string
	TokenID   *uuid.UUID
	TokenName *string
	Body      string
	Mentions  []uuid.UUID
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertComment,
		arg.TenantID,
		arg.TicketID,
		arg.AuthorID,
		arg.Agent,
		arg.TokenID,
		arg.TokenName,
		arg.Body,
		arg.Mentions,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCommentRevision = `-- name: InsertCommentRevision :exec
INSERT INTO comment_revisions (tenant_id, comment_id, body, edited_by, agent, token_id, token_name)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertCommentRevisionParams struct {
	TenantID  uuid.UUID
	CommentID uuid.UUID
	Body      string
	EditedBy  uuid.UUID
	Agent     *string
	TokenID   *uuid.UUID
	TokenName *string
}

func (q *Queries) InsertCommentRevision(ctx context.Context, arg InsertCommentRevisionParams) error {
	_, err := q.db.Exec(ctx, insertCommentRevision,
		arg.TenantID,
		arg.CommentID,
		arg.Body,
		arg.EditedBy,
		arg.Agent,
		arg.TokenID,
		arg.TokenName,
	)
	return err
}

const updateCommentBody = `-- name: UpdateCommentBody :one
UPDATE comments
SET body = $1, mentions = $2::uuid[], version = version + 1, updated_at = now()
WHERE tenant_id = $3 AND id = $4 AND version = $5 AND withdrawn_at IS NULL
RETURNING version
`

type UpdateCommentBodyParams struct {
	Body     string
	Mentions []uuid.UUID
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

// The comment's text and its mentions, which an edit replaces together
// (docs/adr/0015 D3, D5).
func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCommentBody,
		arg.Body,
		arg.Mentions,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const withdrawComment = `-- name: WithdrawComment :exec
UPDATE comments
SET withdrawn_by = $1, withdrawn_at = now(), version = version + 1, updated_at = now()
WHERE tenant_id = $2 AND id = $3 AND withdrawn_at IS NULL
`

type WithdrawCommentParams struct {
	WithdrawnBy *uuid.UUID
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) WithdrawComment(ctx context.Context, arg WithdrawCommentParams) error {
	_, err := q.db.Exec(ctx, withdrawComment, arg.WithdrawnBy, arg.TenantID, arg.ID)
	return err
}
