// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredGitHubDeliveries = `-- name: DeleteExpiredGitHubDeliveries :execrows
DELETE FROM github_deliveries WHERE expires_at <= $1::timestamptz
`

// The expiry job's sweep across the tenants (migration 41).
func (q *Queries) DeleteExpiredGitHubDeliveries(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredGitHubDeliveries, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubWebhookSecret = `-- name: DeleteGitHubWebhookSecret :execrows
DELETE FROM github_webhook_secrets WHERE tenant_id = $1
`

// The revocation (D1): from now on the endpoint answers like an unknown
// tenant.
func (q *Queries) DeleteGitHubWebhookSecret(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubWebhookSecret, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTicketCommit = `-- name: InsertTicketCommit :one
INSERT INTO ticket_pull_requests (tenant_id, ticket_id, kind, repository, sha, title, state, url, author,
                                  merged_at, found_in, first_seen_at, last_seen_at)
VALUES ($1, $2, 'commit', $3, $4::text,
        $5, 'merged', $6, $7, $8::timestamptz,
        $9, $8::timestamptz, $8::timestamptz)
ON CONFLICT (tenant_id, ticket_id, repository, sha) WHERE kind = 'commit' DO NOTHING
RETURNING id
`

type InsertTicketCommitParams struct {
	TenantID   uuid.UUID
	TicketID   uuid.UUID
	Repository string
	Sha        string
	Title      string
	Url        string
	Author     *string
	SeenAt     time.Time
	FoundIn    string
}

// A default-branch commit's link to a ticket (D6): merged when it was pushed.
// No row when the ticket holds the link already, or held it until a person
// removed it.
func (q *Queries) InsertTicketCommit(ctx context.Context, arg InsertTicketCommitParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTicketCommit,
		arg.TenantID,
		arg.TicketID,
		arg.Repository,
		arg.Sha,
		arg.Title,
		arg.Url,
		arg.Author,
		arg.SeenAt,
		arg.FoundIn,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTicketPullRequest = `-- name: InsertTicketPullRequest :one
INSERT INTO ticket_pull_requests (tenant_id, ticket_id, kind, repository, number, title, state, url, author,
                                  merged_at, found_in, source_updated_at, first_seen_at, last_seen_at)
VALUES ($1, $2, 'pull_request', $3, $4::integer,
        $5, $6, $7, $8, $9, $10,
        $11, $12, $12)
ON CONFLICT (tenant_id, ticket_id, repository, number) WHERE kind = 'pull_request' DO NOTHING
RETURNING id
`

type InsertTicketPullRequestParams struct {
	TenantID        uuid.UUID
	TicketID        uuid.UUID
	Repository      string
	Number          int32
	Title           string
	State           string
	Url             string
	Author          *string
	MergedAt        *time.Time
	FoundIn         string
	SourceUpdatedAt *time.Time
	SeenAt          time.Time
}

// A pull request's link to a ticket (D6). No row when the ticket holds the
// link already, or held it until a person removed it: a removal stays.
func (q *Queries) InsertTicketPullRequest(ctx context.Context, arg InsertTicketPullRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTicketPullRequest,
		arg.TenantID,
		arg.TicketID,
		arg.Repository,
		arg.Number,
		arg.Title,
		arg.State,
		arg.Url,
		arg.Author,
		arg.MergedAt,
		arg.FoundIn,
		arg.SourceUpdatedAt,
		arg.SeenAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const recordGitHubDelivery = `-- name: RecordGitHubDelivery :one
INSERT INTO github_deliveries (tenant_id, delivery, received_at, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, delivery) DO UPDATE
    SET received_at = EXCLUDED.received_at, expires_at = EXCLUDED.expires_at
    WHERE github_deliveries.expires_at <= EXCLUDED.received_at
RETURNING id
`

type RecordGitHubDeliveryParams struct {
	TenantID   uuid.UUID
	Delivery   uuid.UUID
	ReceivedAt time.Time
	ExpiresAt  time.Time
}

// A delivery the tenant takes, kept a day (D3). No row when the tenant holds
// the same delivery unexpired: a repetition, which changes nothing. An expired
// row of the same id that the job has not removed yet is taken over.
func (q *Queries) RecordGitHubDelivery(ctx context.Context, arg RecordGitHubDeliveryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, recordGitHubDelivery,
		arg.TenantID,
		arg.Delivery,
		arg.ReceivedAt,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const removeTicketPullRequest = `-- name: RemoveTicketPullRequest :one
UPDATE ticket_pull_requests
SET removed_at = $1::timestamptz, removed_by = $2::uuid
WHERE tenant_id = $3 AND ticket_id = $4 AND id = $5 AND removed_at IS NULL
RETURNING kind, repository, number, sha
`

type RemoveTicketPullRequestParams struct {
	RemovedAt time.Time
	RemovedBy uuid.UUID
	TenantID  uuid.UUID
	TicketID  uuid.UUID
	ID        uuid.UUID
}

type RemoveTicketPullRequestRow struct {
	Kind       string
	Repository string
	Number     *int32
	Sha        *string
}

// A person removes a wrong link (docs/adr/0071 Residual risks): the row stays,
// so a later delivery that names the ticket does not bring it back. No row
// when the link was removed already or is another ticket's.
func (q *Queries) RemoveTicketPullRequest(ctx context.Context, arg RemoveTicketPullRequestParams) (RemoveTicketPullRequestRow, error) {
	row := q.db.QueryRow(ctx, removeTicketPullRequest,
		arg.RemovedAt,
		arg.RemovedBy,
		arg.TenantID,
		arg.TicketID,
		arg.ID,
	)
	var i RemoveTicketPullRequestRow
	err := row.Scan(
		&i.Kind,
		&i.Repository,
		&i.Number,
		&i.Sha,
	)
	return i, err
}

const repositoryBoundInTenant = `-- name: RepositoryBoundInTenant :one
SELECT EXISTS (SELECT 1 FROM project_repositories r
               WHERE r.tenant_id = $1 AND r.identity = $2)::boolean AS bound
`

type RepositoryBoundInTenantParams struct {
	TenantID uuid.UUID
	Identity string
}

// Whether a project of the tenant binds the repository, whatever its
// sub-directory (D4): the webhook's system actor asks past the projects'
// restriction and learns no project.
func (q *Queries) RepositoryBoundInTenant(ctx context.Context, arg RepositoryBoundInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, repositoryBoundInTenant, arg.TenantID, arg.Identity)
	var bound bool
	err := row.Scan(&bound)
	return bound, err
}

const resolveTicketKeys = `-- name: ResolveTicketKeys :many
SELECT t.id, p.key AS project_key, t.number
FROM unnest($1::text[]) AS k (key)
JOIN projects p ON p.tenant_id = $2 AND p.key = split_part(k.key, '-', 1)
JOIN tickets t ON t.tenant_id = p.tenant_id AND t.project_id = p.id
                  AND t.number = split_part(k.key, '-', 2)::integer
WHERE t.deleted_at IS NULL
ORDER BY p.key, t.number
`

type ResolveTicketKeysParams struct {
	Keys     []string
	TenantID uuid.UUID
}

type ResolveTicketKeysRow struct {
	ID         uuid.UUID
	ProjectKey string
	Number     int32
}

// The tickets of the tenant the short keys of a delivery name (D5), each key
// <PROJECT>-<number> as the caller parsed it — a project key has no hyphen: a
// key of no ticket, or of a deleted one, is no row.
// visibility: exempt (the webhook's system actor resolves the keys a signed delivery names; whoever reads a link is held to the ticket's predicate)
func (q *Queries) ResolveTicketKeys(ctx context.Context, arg ResolveTicketKeysParams) ([]ResolveTicketKeysRow, error) {
	rows, err := q.db.Query(ctx, resolveTicketKeys, arg.Keys, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveTicketKeysRow{}
	for rows.Next() {
		var i ResolveTicketKeysRow
		if err := rows.Scan(&i.ID, &i.ProjectKey, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGitHubWebhookSecret = `-- name: SetGitHubWebhookSecret :exec

INSERT INTO github_webhook_secrets (tenant_id, secret, created_by, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id) DO UPDATE
    SET secret = EXCLUDED.secret, created_by = EXCLUDED.created_by, created_at = EXCLUDED.created_at
`

type SetGitHubWebhookSecretParams struct {
	TenantID  uuid.UUID
	Secret    []byte
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

// GitHub's webhook (docs/adr/0071): the tenant's secret, the deliveries, and
// the links of pull requests and default-branch commits to tickets.
// The tenant's secret, sealed, made or rotated by an administrator (D1): a
// rotation replaces the old one at once.
func (q *Queries) SetGitHubWebhookSecret(ctx context.Context, arg SetGitHubWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, setGitHubWebhookSecret,
		arg.TenantID,
		arg.Secret,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const updatePullRequestFacts = `-- name: UpdatePullRequestFacts :many
WITH old AS (
    SELECT p.id, p.state, p.title, p.url, p.author, pr.key AS project_key, t.number AS ticket_number,
           (t.deleted_at IS NOT NULL)::boolean AS ticket_deleted
    FROM ticket_pull_requests p
    JOIN tickets t ON t.tenant_id = p.tenant_id AND t.id = p.ticket_id
    JOIN projects pr ON pr.tenant_id = t.tenant_id AND pr.id = t.project_id
    WHERE p.tenant_id = $8 AND p.kind = 'pull_request' AND p.repository = $9
      AND p.number = $10::integer AND p.removed_at IS NULL
      AND (p.source_updated_at IS NULL OR p.source_updated_at <= $6::timestamptz)
    FOR UPDATE OF p
)
UPDATE ticket_pull_requests p
SET title = $1, state = $2, url = $3, author = $4,
    merged_at = $5, source_updated_at = $6::timestamptz,
    last_seen_at = $7
FROM old
WHERE p.id = old.id
RETURNING p.id, p.ticket_id, old.project_key, old.ticket_number, old.ticket_deleted, old.state AS state_before,
          (old.title IS DISTINCT FROM p.title OR old.url IS DISTINCT FROM p.url
           OR old.author IS DISTINCT FROM p.author)::boolean AS facts_changed
`

type UpdatePullRequestFactsParams struct {
	Title           string
	State           string
	Url             string
	Author          *string
	MergedAt        *time.Time
	SourceUpdatedAt time.Time
	SeenAt          time.Time
	TenantID        uuid.UUID
	Repository      string
	Number          int32
}

type UpdatePullRequestFactsRow struct {
	ID            uuid.UUID
	TicketID      uuid.UUID
	ProjectKey    string
	TicketNumber  int32
	TicketDeleted bool
	StateBefore   string
	FactsChanged  bool
}

// A pull request's facts on every ticket it is linked to (D6), from a delivery
// no older than what a row holds: one GitHub sent before, or one replayed,
// changes nothing. A link a person removed stays as it was. Each row answers
// what it held before, its ticket's key and whether the ticket is deleted —
// whose link keeps the facts and records no act.
// visibility: exempt (the webhook's system actor keeps every link of the pull request; nobody reads through it)
// deletion: exempt (a deleted ticket's link keeps the pull request's facts and records no act)
func (q *Queries) UpdatePullRequestFacts(ctx context.Context, arg UpdatePullRequestFactsParams) ([]UpdatePullRequestFactsRow, error) {
	rows, err := q.db.Query(ctx, updatePullRequestFacts,
		arg.Title,
		arg.State,
		arg.Url,
		arg.Author,
		arg.MergedAt,
		arg.SourceUpdatedAt,
		arg.SeenAt,
		arg.TenantID,
		arg.Repository,
		arg.Number,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdatePullRequestFactsRow{}
	for rows.Next() {
		var i UpdatePullRequestFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ProjectKey,
			&i.TicketNumber,
			&i.TicketDeleted,
			&i.StateBefore,
			&i.FactsChanged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
