// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package writeq

import (
	"context"

	"github.com/google/uuid"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeIdempotencyKey = `-- name: StoreIdempotencyKey :one
INSERT INTO idempotency_keys (
    token_id, user_id, tenant_id, key, fingerprint, response_status, response_headers,
    response_body, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    now() + interval '24 hours'
)
ON CONFLICT (user_id, token_id, key) DO UPDATE
SET user_id = EXCLUDED.user_id, tenant_id = EXCLUDED.tenant_id, fingerprint = EXCLUDED.fingerprint,
    response_status = EXCLUDED.response_status, response_headers = EXCLUDED.response_headers,
    response_body = EXCLUDED.response_body, created_at = now(), expires_at = EXCLUDED.expires_at
WHERE idempotency_keys.expires_at <= now()
RETURNING id
`

type StoreIdempotencyKeyParams struct {
	TokenID         *uuid.UUID
	UserID          uuid.UUID
	TenantID        *uuid.UUID
	Key             uuid.UUID
	Fingerprint     []byte
	ResponseStatus  int16
	ResponseHeaders []byte
	ResponseBody    []byte
}

// A key that exists and has expired is taken over; one that has not expired
// belongs to a concurrent request with the same key, and no row comes back.
func (q *Queries) StoreIdempotencyKey(ctx context.Context, arg StoreIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, storeIdempotencyKey,
		arg.TokenID,
		arg.UserID,
		arg.TenantID,
		arg.Key,
		arg.Fingerprint,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
