// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const advanceTicketCounter = `-- name: AdvanceTicketCounter :exec
UPDATE ticket_counters
SET last_number = GREATEST(last_number, $1::integer)
WHERE tenant_id = $2 AND project_id = $3
`

type AdvanceTicketCounterParams struct {
	Number    int32
	TenantID  uuid.UUID
	ProjectID uuid.UUID
}

// The project's sequence past the highest number an import brought
// (docs/adr/0007 D6); it never moves back.
func (q *Queries) AdvanceTicketCounter(ctx context.Context, arg AdvanceTicketCounterParams) error {
	_, err := q.db.Exec(ctx, advanceTicketCounter, arg.Number, arg.TenantID, arg.ProjectID)
	return err
}

const deleteExpiredImportJobs = `-- name: DeleteExpiredImportJobs :execrows
DELETE FROM import_jobs
WHERE status = 'dry_run' AND expires_at <= $1
`

// The job import-expiry: the dry runs whose twenty-four hours have passed, in
// every tenant, with the files they hold (docs/adr/0051 D7).
func (q *Queries) DeleteExpiredImportJobs(ctx context.Context, now *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredImportJobs, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishImportJob = `-- name: FinishImportJob :execrows
UPDATE import_jobs
SET status = 'executed', executed_by = $1, executed_at = $2,
    report = $3, source = NULL, expires_at = NULL
WHERE tenant_id = $4 AND id = $5 AND status = 'dry_run'
`

type FinishImportJobParams struct {
	ExecutedBy *uuid.UUID
	ExecutedAt *time.Time
	Report     []byte
	TenantID   uuid.UUID
	ID         uuid.UUID
}

// The execution's end: the report of what it created replaces the dry run's,
// and the files it read go.
func (q *Queries) FinishImportJob(ctx context.Context, arg FinishImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishImportJob,
		arg.ExecutedBy,
		arg.ExecutedAt,
		arg.Report,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertImportJob = `-- name: InsertImportJob :exec

INSERT INTO import_jobs (id, tenant_id, project_id, created_by, expires_at, report, source)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertImportJobParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	CreatedBy uuid.UUID
	ExpiresAt *time.Time
	Report    []byte
	Source    []byte
}

// The writes of an import job (docs/adr/0051 D1–D3, D7). The policies of
// migration 43 hold every row of import_jobs to a tenant's administrators,
// and its deletion to the expiry job.
// A dry run: its report and the files it read, valid until expires_at.
func (q *Queries) InsertImportJob(ctx context.Context, arg InsertImportJobParams) error {
	_, err := q.db.Exec(ctx, insertImportJob,
		arg.ID,
		arg.TenantID,
		arg.ProjectID,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.Report,
		arg.Source,
	)
	return err
}

const insertImportedQuestion = `-- name: InsertImportedQuestion :one
INSERT INTO questions (tenant_id, ticket_id, number, question, options, recommendation, answer, status,
                       asked_by, answered_by, answered_at, withdrawn_by, withdrawn_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8::question_status, $9,
        CASE WHEN $8::question_status = 'answered' THEN $9::uuid END,
        CASE WHEN $8::question_status = 'answered' THEN now() END,
        CASE WHEN $8::question_status = 'withdrawn' THEN $9::uuid END,
        CASE WHEN $8::question_status = 'withdrawn' THEN now() END)
RETURNING id
`

type InsertImportedQuestionParams struct {
	TenantID       uuid.UUID
	TicketID       uuid.UUID
	Number         int32
	Question       string
	Options        string
	Recommendation string
	Answer         *string
	Status         string
	AskedBy        uuid.UUID
}

// An open question an import creates on its ticket with the number, the text
// and the answer of its source (docs/adr/0011 D2, D4); the importer asked it,
// and gave the answer it carries or withdrew it.
func (q *Queries) InsertImportedQuestion(ctx context.Context, arg InsertImportedQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertImportedQuestion,
		arg.TenantID,
		arg.TicketID,
		arg.Number,
		arg.Question,
		arg.Options,
		arg.Recommendation,
		arg.Answer,
		arg.Status,
		arg.AskedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertImportedTicket = `-- name: InsertImportedTicket :one
INSERT INTO tickets (
    tenant_id, project_id, number, type, title, body, state,
    blocked_from, block_kind, block_reason, block_ticket_id,
    severity, security, threat, urgency_derived, urgency_rule,
    urgency_override, urgency_override_by, urgency_override_at,
    effort, progress, progress_refinement, progress_review, parent_id,
    reporter_id, reporter_token_id, reporter_token_name, assignee_id, confidential, rank,
    opened_at, decided_at, done_at, done_from, done_by_hand,
    imported_from_file, imported_from_job
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17::urgency, $18::uuid,
    CASE WHEN $17::urgency IS NULL THEN NULL ELSE now() END,
    $19, $20, $21, $22, $23,
    $24, $25, $26, $27,
    $28, $29::text,
    coalesce($30::timestamptz, now()), $31, $32,
    $33, $34,
    $35, $36
)
RETURNING id
`

type InsertImportedTicketParams struct {
	TenantID           uuid.UUID
	ProjectID          uuid.UUID
	Number             int32
	Type               domain.TicketType
	Title              string
	Body               string
	State              domain.TicketState
	BlockedFrom        *domain.TicketState
	BlockKind          *domain.BlockKind
	BlockReason        *string
	BlockTicketID      *uuid.UUID
	Severity           domain.Severity
	Security           domain.SecurityClass
	Threat             *string
	UrgencyDerived     domain.Urgency
	UrgencyRule        string
	UrgencyOverride    *domain.Urgency
	UrgencyOverrideBy  *uuid.UUID
	Effort             domain.Effort
	Progress           int16
	ProgressRefinement int16
	ProgressReview     int16
	ParentID           *uuid.UUID
	ReporterID         uuid.UUID
	ReporterTokenID    *uuid.UUID
	ReporterTokenName  *string
	AssigneeID         *uuid.UUID
	Confidential       bool
	Rank               *string
	OpenedAt           *time.Time
	DecidedAt          *time.Time
	DoneAt             *time.Time
	DoneFrom           *domain.TicketState
	DoneByHand         bool
	ImportedFromFile   *string
	ImportedFromJob    *uuid.UUID
}

// A ticket an import creates, with its number kept (docs/adr/0007 D6), the
// state, dates, stages, horizon and block of its source, and the file and job
// it came from (docs/adr/0051 D3). The importer is its reporter.
func (q *Queries) InsertImportedTicket(ctx context.Context, arg InsertImportedTicketParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertImportedTicket,
		arg.TenantID,
		arg.ProjectID,
		arg.Number,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.State,
		arg.BlockedFrom,
		arg.BlockKind,
		arg.BlockReason,
		arg.BlockTicketID,
		arg.Severity,
		arg.Security,
		arg.Threat,
		arg.UrgencyDerived,
		arg.UrgencyRule,
		arg.UrgencyOverride,
		arg.UrgencyOverrideBy,
		arg.Effort,
		arg.Progress,
		arg.ProgressRefinement,
		arg.ProgressReview,
		arg.ParentID,
		arg.ReporterID,
		arg.ReporterTokenID,
		arg.ReporterTokenName,
		arg.AssigneeID,
		arg.Confidential,
		arg.Rank,
		arg.OpenedAt,
		arg.DecidedAt,
		arg.DoneAt,
		arg.DoneFrom,
		arg.DoneByHand,
		arg.ImportedFromFile,
		arg.ImportedFromJob,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockImportJob = `-- name: LockImportJob :one
SELECT status, expires_at, source
FROM import_jobs
WHERE tenant_id = $1 AND project_id = $2 AND id = $3
FOR UPDATE
`

type LockImportJobParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type LockImportJobRow struct {
	Status    string
	ExpiresAt *time.Time
	Source    []byte
}

// The job an execution writes, locked until the transaction ends: a second
// execution waits for the first and then finds it executed (docs/adr/0051 D3).
func (q *Queries) LockImportJob(ctx context.Context, arg LockImportJobParams) (LockImportJobRow, error) {
	row := q.db.QueryRow(ctx, lockImportJob, arg.TenantID, arg.ProjectID, arg.ID)
	var i LockImportJobRow
	err := row.Scan(&i.Status, &i.ExpiresAt, &i.Source)
	return i, err
}
