// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM ticket_links
WHERE tenant_id = $1 AND type = $2
  AND source_id = $3 AND target_id = $4
`

type DeleteLinkParams struct {
	TenantID uuid.UUID
	Type     domain.LinkType
	SourceID uuid.UUID
	TargetID uuid.UUID
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink,
		arg.TenantID,
		arg.Type,
		arg.SourceID,
		arg.TargetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLink = `-- name: InsertLink :one
INSERT INTO ticket_links (tenant_id, type, source_id, target_id, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertLinkParams struct {
	TenantID  uuid.UUID
	Type      domain.LinkType
	SourceID  uuid.UUID
	TargetID  uuid.UUID
	CreatedBy uuid.UUID
}

type InsertLinkRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) (InsertLinkRow, error) {
	row := q.db.QueryRow(ctx, insertLink,
		arg.TenantID,
		arg.Type,
		arg.SourceID,
		arg.TargetID,
		arg.CreatedBy,
	)
	var i InsertLinkRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const rederiveUrgency = `-- name: RederiveUrgency :exec
UPDATE tickets
SET urgency_derived = $1, urgency_rule = $2,
    urgency_override = NULL, urgency_override_reason = NULL, urgency_override_by = NULL,
    urgency_override_at = NULL, updated_at = now()
WHERE tenant_id = $3 AND id = $4
`

type RederiveUrgencyParams struct {
	UrgencyDerived domain.Urgency
	UrgencyRule    string
	TenantID       uuid.UUID
	ID             uuid.UUID
}

// A new derivation after an input changed, which ends the override
// (docs/adr/0010 D3). Caused by another entity — a link, another ticket's
// state — it leaves the ticket's version alone (docs/adr/0050 D1); the
// ticket's own transitions bump the version themselves.
func (q *Queries) RederiveUrgency(ctx context.Context, arg RederiveUrgencyParams) error {
	_, err := q.db.Exec(ctx, rederiveUrgency,
		arg.UrgencyDerived,
		arg.UrgencyRule,
		arg.TenantID,
		arg.ID,
	)
	return err
}
