// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredLoginAttempts = `-- name: DeleteExpiredLoginAttempts :execrows
DELETE FROM login_attempts WHERE created_at <= $1
`

func (q *Queries) DeleteExpiredLoginAttempts(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginAttempts, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredLoginLocks = `-- name: DeleteExpiredLoginLocks :execrows
DELETE FROM login_locks WHERE NOT sticky AND locked_at <= $1
`

// A lock that ended with its window; a sticky one stays until an administrator
// unlocks it.
func (q *Queries) DeleteExpiredLoginLocks(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginLocks, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFailedLoginAttempts = `-- name: DeleteFailedLoginAttempts :execrows
DELETE FROM login_attempts WHERE username = $1 AND failed
`

// The failures of a username, which is what a lock is made of: an
// administrator's unlock, the creation of an account of that name, a changed
// password of the local administrator.
func (q *Queries) DeleteFailedLoginAttempts(ctx context.Context, username string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFailedLoginAttempts, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginAttempt = `-- name: DeleteLoginAttempt :exec
DELETE FROM login_attempts WHERE id = $1
`

// The reservation of an attempt, which the attempt's outcome replaces.
func (q *Queries) DeleteLoginAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoginAttempt, id)
	return err
}

const deleteLoginLock = `-- name: DeleteLoginLock :execrows
DELETE FROM login_locks WHERE username = $1
`

func (q *Queries) DeleteLoginLock(ctx context.Context, username string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLoginLock, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec

INSERT INTO login_attempts (username, address, failed, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertLoginAttemptParams struct {
	Username  string
	Address   []byte
	Failed    bool
	CreatedAt time.Time
}

// The login's writes. They run in the login's transaction (app.job = 'login'),
// as a system actor (docs/adr/0027 D5).
func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt,
		arg.Username,
		arg.Address,
		arg.Failed,
		arg.CreatedAt,
	)
	return err
}

const noteLoginLock = `-- name: NoteLoginLock :exec
UPDATE login_locks SET noted_at = $1 WHERE username = $2
`

type NoteLoginLockParams struct {
	NotedAt  *time.Time
	Username string
}

func (q *Queries) NoteLoginLock(ctx context.Context, arg NoteLoginLockParams) error {
	_, err := q.db.Exec(ctx, noteLoginLock, arg.NotedAt, arg.Username)
	return err
}

const reserveLoginAttempt = `-- name: ReserveLoginAttempt :one
INSERT INTO login_attempts (username, address, failed, created_at)
VALUES ($1, $2, false, $3)
RETURNING id
`

type ReserveLoginAttemptParams struct {
	Username  string
	Address   []byte
	CreatedAt time.Time
}

// An attempt counted against its address's throttle before its password is
// hashed, under the address's lock (docs/adr/0033 D6); its outcome replaces it.
func (q *Queries) ReserveLoginAttempt(ctx context.Context, arg ReserveLoginAttemptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, reserveLoginAttempt, arg.Username, arg.Address, arg.CreatedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertLoginLock = `-- name: UpsertLoginLock :exec
INSERT INTO login_locks (username, locked_at, sticky)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO UPDATE
SET locked_at = EXCLUDED.locked_at, sticky = EXCLUDED.sticky, noted_at = NULL
`

type UpsertLoginLockParams struct {
	Username string
	LockedAt time.Time
	Sticky   bool
}

func (q *Queries) UpsertLoginLock(ctx context.Context, arg UpsertLoginLockParams) error {
	_, err := q.db.Exec(ctx, upsertLoginLock, arg.Username, arg.LockedAt, arg.Sticky)
	return err
}
