// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const deleteGrant = `-- name: DeleteGrant :one
DELETE FROM memberships
WHERE tenant_id = $1 AND user_id = $2 AND source = 'grant'
RETURNING id, role
`

type DeleteGrantParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type DeleteGrantRow struct {
	ID   uuid.UUID
	Role domain.Role
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (DeleteGrantRow, error) {
	row := q.db.QueryRow(ctx, deleteGrant, arg.TenantID, arg.UserID)
	var i DeleteGrantRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const deleteGroupMapping = `-- name: DeleteGroupMapping :one
DELETE FROM group_mappings
WHERE tenant_id = $1 AND id = $2
RETURNING group_name, role
`

type DeleteGroupMappingParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type DeleteGroupMappingRow struct {
	GroupName string
	Role      domain.Role
}

func (q *Queries) DeleteGroupMapping(ctx context.Context, arg DeleteGroupMappingParams) (DeleteGroupMappingRow, error) {
	row := q.db.QueryRow(ctx, deleteGroupMapping, arg.TenantID, arg.ID)
	var i DeleteGroupMappingRow
	err := row.Scan(&i.GroupName, &i.Role)
	return i, err
}

const deleteProjectAccess = `-- name: DeleteProjectAccess :one
DELETE FROM project_access
WHERE tenant_id = $1 AND project_id = $2 AND user_id = $3
RETURNING id, role
`

type DeleteProjectAccessParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

type DeleteProjectAccessRow struct {
	ID   uuid.UUID
	Role domain.Role
}

func (q *Queries) DeleteProjectAccess(ctx context.Context, arg DeleteProjectAccessParams) (DeleteProjectAccessRow, error) {
	row := q.db.QueryRow(ctx, deleteProjectAccess, arg.TenantID, arg.ProjectID, arg.UserID)
	var i DeleteProjectAccessRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const insertGroupMapping = `-- name: InsertGroupMapping :exec
INSERT INTO group_mappings (id, tenant_id, group_name, role, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertGroupMappingParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	GroupName string
	Role      domain.Role
	CreatedBy *uuid.UUID
}

// The id is made by the application, so the act that records the mapping can
// name it.
func (q *Queries) InsertGroupMapping(ctx context.Context, arg InsertGroupMappingParams) error {
	_, err := q.db.Exec(ctx, insertGroupMapping,
		arg.ID,
		arg.TenantID,
		arg.GroupName,
		arg.Role,
		arg.CreatedBy,
	)
	return err
}

const insertProjectAccess = `-- name: InsertProjectAccess :one
INSERT INTO project_access (tenant_id, project_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertProjectAccessParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      domain.Role
}

type InsertProjectAccessRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertProjectAccess(ctx context.Context, arg InsertProjectAccessParams) (InsertProjectAccessRow, error) {
	row := q.db.QueryRow(ctx, insertProjectAccess,
		arg.TenantID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
	)
	var i InsertProjectAccessRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const setGrantRole = `-- name: SetGrantRole :exec

UPDATE memberships
SET role = $1, version = version + 1, updated_at = now()
WHERE tenant_id = $2 AND user_id = $3 AND source = 'grant'
`

type SetGrantRoleParams struct {
	Role     domain.Role
	TenantID uuid.UUID
	UserID   uuid.UUID
}

// The administration's writes: grants, group mappings, a project's restriction
// and its access list (docs/adr/0030 D2, D3, docs/adr/0034 D3), inside the
// tenant's transaction of one of its administrators.
func (q *Queries) SetGrantRole(ctx context.Context, arg SetGrantRoleParams) error {
	_, err := q.db.Exec(ctx, setGrantRole, arg.Role, arg.TenantID, arg.UserID)
	return err
}

const setProjectAccessRole = `-- name: SetProjectAccessRole :one
UPDATE project_access
SET role = $1
WHERE tenant_id = $2 AND project_id = $3 AND user_id = $4
RETURNING id, created_at
`

type SetProjectAccessRoleParams struct {
	Role      domain.Role
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

type SetProjectAccessRoleRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) SetProjectAccessRole(ctx context.Context, arg SetProjectAccessRoleParams) (SetProjectAccessRoleRow, error) {
	row := q.db.QueryRow(ctx, setProjectAccessRole,
		arg.Role,
		arg.TenantID,
		arg.ProjectID,
		arg.UserID,
	)
	var i SetProjectAccessRoleRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const setProjectRestricted = `-- name: SetProjectRestricted :one
UPDATE projects
SET restricted = $1, version = version + 1, updated_at = now()
WHERE tenant_id = $2 AND id = $3 AND version = $4
RETURNING id, key, name, description, restricted, wip_limits, archived_at, version, created_at, updated_at
`

type SetProjectRestrictedParams struct {
	Restricted bool
	TenantID   uuid.UUID
	ID         uuid.UUID
	Version    int32
}

type SetProjectRestrictedRow struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	Restricted  bool
	WipLimits   []byte
	ArchivedAt  *time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// A compare-and-set on the version (docs/adr/0050 D3): the restriction is a
// setting of the project (docs/adr/0034 D3).
func (q *Queries) SetProjectRestricted(ctx context.Context, arg SetProjectRestrictedParams) (SetProjectRestrictedRow, error) {
	row := q.db.QueryRow(ctx, setProjectRestricted,
		arg.Restricted,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i SetProjectRestrictedRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Restricted,
		&i.WipLimits,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupMappingRole = `-- name: UpdateGroupMappingRole :one
UPDATE group_mappings
SET role = $1, version = version + 1, updated_at = now()
WHERE tenant_id = $2 AND id = $3 AND version = $4
RETURNING id, group_name, role, version, created_at, updated_at
`

type UpdateGroupMappingRoleParams struct {
	Role     domain.Role
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

type UpdateGroupMappingRoleRow struct {
	ID        uuid.UUID
	GroupName string
	Role      domain.Role
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

// A compare-and-set on the version (docs/adr/0050 D1, D3).
func (q *Queries) UpdateGroupMappingRole(ctx context.Context, arg UpdateGroupMappingRoleParams) (UpdateGroupMappingRoleRow, error) {
	row := q.db.QueryRow(ctx, updateGroupMappingRole,
		arg.Role,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i UpdateGroupMappingRoleRow
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
