// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteReadNotifications = `-- name: DeleteReadNotifications :execrows
DELETE FROM notifications WHERE read_at < $1::timestamptz
`

// The retention of docs/adr/0020 D6: a notification read before the bound
// goes; an unread one stays.
func (q *Queries) DeleteReadNotifications(ctx context.Context, readBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadNotifications, readBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotifications = `-- name: InsertNotifications :exec
INSERT INTO notifications (tenant_id, user_id, ticket_id, audit_event_id, reason)
SELECT $1, r.id, $2, $3, $4::notification_reason
FROM unnest($5::uuid[]) AS r (id)
`

type InsertNotificationsParams struct {
	TenantID     uuid.UUID
	TicketID     uuid.UUID
	AuditEventID uuid.UUID
	Reason       string
	Recipients   []uuid.UUID
}

func (q *Queries) InsertNotifications(ctx context.Context, arg InsertNotificationsParams) error {
	_, err := q.db.Exec(ctx, insertNotifications,
		arg.TenantID,
		arg.TicketID,
		arg.AuditEventID,
		arg.Reason,
		arg.Recipients,
	)
	return err
}

const listTicketsBlockedBy = `-- name: ListTicketsBlockedBy :many
SELECT l.target_id FROM ticket_links l
WHERE l.tenant_id = $1 AND l.source_id = $2 AND l.type = 'blocks'
ORDER BY l.target_id
`

type ListTicketsBlockedByParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

// The tickets a ticket blocks (docs/adr/0012 D1): the watchers of each hear
// when it reaches done or dropped (docs/adr/0020 D2).
func (q *Queries) ListTicketsBlockedBy(ctx context.Context, arg ListTicketsBlockedByParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTicketsBlockedBy, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var target_id uuid.UUID
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchers = `-- name: ListWatchers :many

SELECT i.user_id FROM ticket_interest i
WHERE i.tenant_id = $1 AND i.ticket_id = $2
UNION
SELECT t.assignee_id FROM tickets t
WHERE t.tenant_id = $1 AND t.id = $2 AND t.assignee_id IS NOT NULL
UNION
SELECT t.reporter_id FROM tickets t
WHERE t.tenant_id = $1 AND t.id = $2
UNION
SELECT q.asked_by FROM questions q
WHERE q.tenant_id = $1 AND q.ticket_id = $2 AND q.status = 'open'
UNION
SELECT q.asked_of FROM questions q
WHERE q.tenant_id = $1 AND q.ticket_id = $2 AND q.status = 'open'
  AND q.asked_of IS NOT NULL
`

type ListWatchersParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

// Whom an act tells in their inbox and how it is marked read (docs/adr/0020).
// The recipients are read inside the act's transaction, past the writer's own
// predicate: whom an act tells is decided by each recipient's sight of the
// ticket, never by the writer's.
// The watchers of a ticket (docs/adr/0013 D6): every person with a stake of
// any weight, the assignee, the reporter, and whoever asked or was asked an
// open question on it.
// visibility: exempt (whom an act tells; NoticeRecipients holds each to their own sight of the ticket)
func (q *Queries) ListWatchers(ctx context.Context, arg ListWatchersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWatchers, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxRead = `-- name: MarkInboxRead :execrows
UPDATE notifications n SET read_at = $1::timestamptz
WHERE n.tenant_id = $2 AND n.user_id = $3 AND n.id <= $4
  AND n.read_at IS NULL
  AND EXISTS (SELECT 1
              FROM tickets t
              JOIN audit_events a ON a.tenant_id = n.tenant_id AND a.id = n.audit_event_id
              JOIN tickets xt ON xt.tenant_id = a.tenant_id AND xt.id = a.ticket_id
              WHERE t.tenant_id = n.tenant_id AND t.id = n.ticket_id
                AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
                AND app_ticket_visible(xt.project_id, xt.confidential, xt.assignee_id, xt.reporter_id))
`

type MarkInboxReadParams struct {
	Now      time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
	Through  uuid.UUID
}

// The person's unread notifications in the tenant up to and including one,
// read now (docs/adr/0020 D6): what arrived after the one the person saw
// stays unread. Those of tickets they no longer see stay as they are.
func (q *Queries) MarkInboxRead(ctx context.Context, arg MarkInboxReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInboxRead,
		arg.Now,
		arg.TenantID,
		arg.UserID,
		arg.Through,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications n SET read_at = $1::timestamptz
WHERE n.tenant_id = $2 AND n.user_id = $3 AND n.id = $4
  AND n.read_at IS NULL
  AND EXISTS (SELECT 1
              FROM tickets t
              JOIN audit_events a ON a.tenant_id = n.tenant_id AND a.id = n.audit_event_id
              JOIN tickets xt ON xt.tenant_id = a.tenant_id AND xt.id = a.ticket_id
              WHERE t.tenant_id = n.tenant_id AND t.id = n.ticket_id
                AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
                AND app_ticket_visible(xt.project_id, xt.confidential, xt.assignee_id, xt.reporter_id))
`

type MarkNotificationReadParams struct {
	Now      time.Time
	TenantID uuid.UUID
	UserID   uuid.UUID
	ID       uuid.UUID
}

// One of the person's notifications, read now; one they no longer see stays
// as it is (docs/adr/0065 D5).
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead,
		arg.Now,
		arg.TenantID,
		arg.UserID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const noticeRecipients = `-- name: NoticeRecipients :many
SELECT u.id FROM users u
WHERE u.id = ANY ($1::uuid[]) AND u.deactivated_at IS NULL
  AND u.id IS DISTINCT FROM $2::uuid
  AND person_sees_ticket($3, $4, u.id)
  AND person_sees_ticket($3, $5, u.id)
ORDER BY u.id
`

type NoticeRecipientsParams struct {
	People      []uuid.UUID
	Actor       *uuid.UUID
	TenantID    uuid.UUID
	TicketID    uuid.UUID
	ActTicketID uuid.UUID
}

// Of the persons an act names, those it tells: active, not the actor — a
// person's own act and their agent's tell them nothing (docs/adr/0020 D2) —
// and able to see the ticket the notification is about and the ticket the act
// is on (docs/adr/0065 D5).
func (q *Queries) NoticeRecipients(ctx context.Context, arg NoticeRecipientsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, noticeRecipients,
		arg.People,
		arg.Actor,
		arg.TenantID,
		arg.TicketID,
		arg.ActTicketID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionAskedOf = `-- name: QuestionAskedOf :one
SELECT asked_of FROM questions
WHERE tenant_id = $1 AND id = $2
`

type QuestionAskedOfParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The person a question is asked of, whom its events reach across their
// tenants (docs/adr/0054 D1); null for a question open in the tenant.
func (q *Queries) QuestionAskedOf(ctx context.Context, arg QuestionAskedOfParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, questionAskedOf, arg.TenantID, arg.ID)
	var asked_of *uuid.UUID
	err := row.Scan(&asked_of)
	return asked_of, err
}
