// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects
SET archived_at = now(), version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND archived_at IS NULL
RETURNING id, key, name, description, restricted, wip_limits, archived_at, version, created_at, updated_at
`

type ArchiveProjectParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type ArchiveProjectRow struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	Restricted  bool
	WipLimits   []byte
	ArchivedAt  *time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (ArchiveProjectRow, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.TenantID, arg.ID)
	var i ArchiveProjectRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Restricted,
		&i.WipLimits,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (tenant_id, key, name, description, wip_limits)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, key, name, description, restricted, wip_limits, archived_at, version, created_at, updated_at
`

type InsertProjectParams struct {
	TenantID    uuid.UUID
	Key         string
	Name        string
	Description string
	WipLimits   []byte
}

type InsertProjectRow struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	Restricted  bool
	WipLimits   []byte
	ArchivedAt  *time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (InsertProjectRow, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.TenantID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.WipLimits,
	)
	var i InsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Restricted,
		&i.WipLimits,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTicketCounter = `-- name: InsertTicketCounter :exec
INSERT INTO ticket_counters (tenant_id, project_id) VALUES ($1, $2)
`

type InsertTicketCounterParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) InsertTicketCounter(ctx context.Context, arg InsertTicketCounterParams) error {
	_, err := q.db.Exec(ctx, insertTicketCounter, arg.TenantID, arg.ProjectID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $1, description = $2, wip_limits = $3,
    version = version + 1, updated_at = now()
WHERE tenant_id = $4 AND id = $5 AND version = $6
RETURNING id, key, name, description, restricted, wip_limits, archived_at, version, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string
	Description string
	WipLimits   []byte
	TenantID    uuid.UUID
	ID          uuid.UUID
	Version     int32
}

type UpdateProjectRow struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	Restricted  bool
	WipLimits   []byte
	ArchivedAt  *time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// A compare-and-set on the version (docs/adr/0050 D1).
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.WipLimits,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Restricted,
		&i.WipLimits,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
