// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package writeq

import (
	"context"

	"github.com/google/uuid"
)

const answerQuestion = `-- name: AnswerQuestion :one
UPDATE questions
SET answer = $1, status = 'answered', answered_by = $2, answered_at = now(),
    recorded_by_agent = $3, answered_by_token_id = $4,
    answered_by_token_name = $5, version = version + 1, updated_at = now()
WHERE tenant_id = $6 AND id = $7 AND version = $8 AND status <> 'withdrawn'
RETURNING version
`

type AnswerQuestionParams struct {
	Answer              *string
	AnsweredBy          *uuid.UUID
	RecordedByAgent     bool
	AnsweredByTokenID   *uuid.UUID
	AnsweredByTokenName *string
	TenantID            uuid.UUID
	ID                  uuid.UUID
	Version             int32
}

// Every answer records how it came, replacing what an earlier one recorded:
// the agent's, and the token's or none (docs/adr/0066 D8, docs/adr/0036 D6).
func (q *Queries) AnswerQuestion(ctx context.Context, arg AnswerQuestionParams) (int32, error) {
	row := q.db.QueryRow(ctx, answerQuestion,
		arg.Answer,
		arg.AnsweredBy,
		arg.RecordedByAgent,
		arg.AnsweredByTokenID,
		arg.AnsweredByTokenName,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (tenant_id, ticket_id, number, question, options, recommendation, asked_by, asked_by_agent,
                       asked_by_token_id, asked_by_token_name, asked_of)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11)
RETURNING id
`

type InsertQuestionParams struct {
	TenantID         uuid.UUID
	TicketID         uuid.UUID
	Number           int32
	Question         string
	Options          string
	Recommendation   string
	AskedBy          uuid.UUID
	AskedByAgent     *string
	AskedByTokenID   *uuid.UUID
	AskedByTokenName *string
	AskedOf          *uuid.UUID
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertQuestion,
		arg.TenantID,
		arg.TicketID,
		arg.Number,
		arg.Question,
		arg.Options,
		arg.Recommendation,
		arg.AskedBy,
		arg.AskedByAgent,
		arg.AskedByTokenID,
		arg.AskedByTokenName,
		arg.AskedOf,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const nextQuestionNumber = `-- name: NextQuestionNumber :one
SELECT (coalesce(max(number), 0) + 1)::integer AS number
FROM questions
WHERE tenant_id = $1 AND ticket_id = $2
`

type NextQuestionNumberParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

// The ticket's next question number; the caller holds the ticket's question
// lock, so two askers never take the same.
func (q *Queries) NextQuestionNumber(ctx context.Context, arg NextQuestionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextQuestionNumber, arg.TenantID, arg.TicketID)
	var number int32
	err := row.Scan(&number)
	return number, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET question = $1, options = $2, recommendation = $3,
    asked_of = $4, version = version + 1, updated_at = now()
WHERE tenant_id = $5 AND id = $6 AND version = $7 AND status = 'open'
RETURNING version
`

type UpdateQuestionParams struct {
	Question       string
	Options        string
	Recommendation string
	AskedOf        *uuid.UUID
	TenantID       uuid.UUID
	ID             uuid.UUID
	Version        int32
}

// An edit of an open question, a compare-and-set on its version
// (docs/adr/0050 D3).
func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.Question,
		arg.Options,
		arg.Recommendation,
		arg.AskedOf,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const withdrawQuestion = `-- name: WithdrawQuestion :one
UPDATE questions
SET status = 'withdrawn', withdrawn_by = $1, withdrawn_at = now(),
    version = version + 1, updated_at = now()
WHERE tenant_id = $2 AND id = $3 AND status = 'open'
RETURNING version
`

type WithdrawQuestionParams struct {
	WithdrawnBy *uuid.UUID
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) WithdrawQuestion(ctx context.Context, arg WithdrawQuestionParams) (int32, error) {
	row := q.db.QueryRow(ctx, withdrawQuestion, arg.WithdrawnBy, arg.TenantID, arg.ID)
	var version int32
	err := row.Scan(&version)
	return version, err
}
