// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRepository = `-- name: DeleteRepository :one
DELETE FROM project_repositories
WHERE tenant_id = $1 AND project_id = $2 AND id = $3
RETURNING id, identity, path, remote
`

type DeleteRepositoryParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type DeleteRepositoryRow struct {
	ID       uuid.UUID
	Identity string
	Path     string
	Remote   string
}

// Unbinds a repository; no row when it was not bound to the project.
func (q *Queries) DeleteRepository(ctx context.Context, arg DeleteRepositoryParams) (DeleteRepositoryRow, error) {
	row := q.db.QueryRow(ctx, deleteRepository, arg.TenantID, arg.ProjectID, arg.ID)
	var i DeleteRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.Path,
		&i.Remote,
	)
	return i, err
}

const insertRepository = `-- name: InsertRepository :one
INSERT INTO project_repositories (tenant_id, project_id, identity, path, remote)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, identity, path) DO NOTHING
RETURNING id, project_id, identity, path, remote, created_at, updated_at
`

type InsertRepositoryParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	Identity  string
	Path      string
	Remote    string
}

type InsertRepositoryRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Identity  string
	Path      string
	Remote    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Binds a repository to a project; a binding of the same identity and path
// that a simultaneous request wrote first returns no row.
func (q *Queries) InsertRepository(ctx context.Context, arg InsertRepositoryParams) (InsertRepositoryRow, error) {
	row := q.db.QueryRow(ctx, insertRepository,
		arg.TenantID,
		arg.ProjectID,
		arg.Identity,
		arg.Path,
		arg.Remote,
	)
	var i InsertRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identity,
		&i.Path,
		&i.Remote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepositoryRemote = `-- name: UpdateRepositoryRemote :one
UPDATE project_repositories
SET remote = $1, updated_at = now()
WHERE tenant_id = $2 AND id = $3
RETURNING id, project_id, identity, path, remote, created_at, updated_at
`

type UpdateRepositoryRemoteParams struct {
	Remote   string
	TenantID uuid.UUID
	ID       uuid.UUID
}

type UpdateRepositoryRemoteRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Identity  string
	Path      string
	Remote    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Keeps the last original form of a bound remote (docs/adr/0066 D1).
func (q *Queries) UpdateRepositoryRemote(ctx context.Context, arg UpdateRepositoryRemoteParams) (UpdateRepositoryRemoteRow, error) {
	row := q.db.QueryRow(ctx, updateRepositoryRemote, arg.Remote, arg.TenantID, arg.ID)
	var i UpdateRepositoryRemoteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identity,
		&i.Path,
		&i.Remote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
