// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenants
SET name = $1,
    time_visible_to_members = $2,
    time_locked_until = $3,
    members_create_projects = $4,
    chat_external_allowed = $5,
    chat_external_provider = $6,
    version = version + 1,
    updated_at = now()
WHERE id = $7 AND version = $8
RETURNING version, updated_at
`

type UpdateTenantSettingsParams struct {
	Name                  string
	TimeVisibleToMembers  bool
	TimeLockedUntil       *time.Time
	MembersCreateProjects bool
	ChatExternalAllowed   bool
	ChatExternalProvider  *string
	TenantID              uuid.UUID
	Version               int32
}

type UpdateTenantSettingsRow struct {
	Version   int32
	UpdatedAt time.Time
}

// A compare-and-set on the version (docs/adr/0050 D1, D3): no row comes back
// when the version moved since the caller read it.
func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (UpdateTenantSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings,
		arg.Name,
		arg.TimeVisibleToMembers,
		arg.TimeLockedUntil,
		arg.MembersCreateProjects,
		arg.ChatExternalAllowed,
		arg.ChatExternalProvider,
		arg.TenantID,
		arg.Version,
	)
	var i UpdateTenantSettingsRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}
