// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package writeq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const revokeTenantToken = `-- name: RevokeTenantToken :one
UPDATE tokens
SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND revoked_at IS NULL
  AND (restricted_tenant_id IS NULL OR restricted_tenant_id = $3::uuid)
RETURNING id
`

type RevokeTenantTokenParams struct {
	RevokedBy *uuid.UUID
	TokenID   uuid.UUID
	TenantID  uuid.UUID
}

// An administrator's revocation of a token that can act in the tenant
// (docs/adr/0035 D5, D6): immediate, the row kept; the policy of migration 35
// admits it.
func (q *Queries) RevokeTenantToken(ctx context.Context, arg RevokeTenantTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeTenantToken, arg.RevokedBy, arg.TokenID, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeToken = `-- name: RevokeToken :one
UPDATE tokens
SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
RETURNING id
`

type RevokeTokenParams struct {
	RevokedBy *uuid.UUID
	TokenID   uuid.UUID
	UserID    uuid.UUID
}

// Revocation is immediate and keeps the row (docs/adr/0035 D6).
func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeToken, arg.RevokedBy, arg.TokenID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE tokens
SET last_used_on = $1
WHERE id = $2 AND (last_used_on IS NULL OR last_used_on < $1)
`

type TouchTokenLastUsedParams struct {
	Day     *time.Time
	TokenID uuid.UUID
}

// Bookkeeping, not an act (docs/adr/0035 D2): at most one write per token and
// UTC day.
func (q *Queries) TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, arg.Day, arg.TokenID)
	return err
}
