/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Dashboard } from '../../models/dashboard';

export interface GetDashboard$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * A project key, negatable with !
 */
  project?: Array<string>;

/**
 * The first day of the period, inclusive
 */
  from?: string;

/**
 * The last day of the period, inclusive
 */
  to?: string;

/**
 * The weak `ETag` of a list the client holds; an unchanged list answers 304 (docs/adr/0054 D7)
 */
  'If-None-Match'?: string;
}

export function getDashboard(http: HttpClient, rootUrl: string, params: GetDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<Dashboard>> {
  const rb = new RequestBuilder(rootUrl, getDashboard.PATH, 'get');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.query('project', params.project, {"style":"form","explode":true});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.header('If-None-Match', params['If-None-Match'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Dashboard>;
    })
  );
}

getDashboard.PATH = '/api/v1/tenants/{tenant}/dashboard';
