// Command problemdoc writes what the problem catalogue decides
// (docs/adr/0047 D4): the OpenAPI enum of the codes, and the table of codes in
// the README between its markers. `make generate` runs it from backend/.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/guided-traffic/cowork/backend/internal/problem"
)

const (
	enumFile   = "api/components/problem-codes.yaml"
	readmeFile = "../README.md"
	startMark  = "<!-- problem-codes:start -->"
	endMark    = "<!-- problem-codes:end -->"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "problemdoc: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	if err := os.WriteFile(enumFile, enumYAML(), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", enumFile, err)
	}
	readme, err := os.ReadFile(readmeFile)
	if err != nil {
		return fmt.Errorf("read %s: %w", readmeFile, err)
	}
	updated, err := replaceBetween(readme, table())
	if err != nil {
		return err
	}
	if err := os.WriteFile(readmeFile, updated, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", readmeFile, err)
	}
	return nil
}

func enumYAML() []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by `make generate` from backend/internal/problem; do not edit.\n")
	b.WriteString("ProblemCode:\n  type: string\n  description: The stable code of a problem (docs/adr/0047 D2)\n  enum:\n")
	for _, c := range problem.Catalogue {
		fmt.Fprintf(&b, "    - %s\n", c.Code)
	}
	return b.Bytes()
}

func table() []byte {
	var b bytes.Buffer
	b.WriteString("| `code` | Status | Meaning |\n|---|---|---|\n")
	for _, c := range problem.Catalogue {
		fmt.Fprintf(&b, "| `%s` | %d | %s |\n", c.Code, c.Status, strings.ReplaceAll(c.Meaning, "|", "\\|"))
	}
	return b.Bytes()
}

func replaceBetween(doc, content []byte) ([]byte, error) {
	start := bytes.Index(doc, []byte(startMark))
	end := bytes.Index(doc, []byte(endMark))
	if start < 0 || end < start {
		return nil, errors.New("the README lacks the problem-codes markers")
	}
	var out bytes.Buffer
	out.Write(doc[:start+len(startMark)])
	out.WriteString("\n")
	out.Write(content)
	out.Write(doc[end:])
	return out.Bytes(), nil
}
