/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatAvailability } from '../../models/chat-availability';

export interface GetChatAvailability$Params {

/**
 * The team's slug (docs/adr/0005 D1, D4)
 */
  team: string;
}

export function getChatAvailability(http: HttpClient, rootUrl: string, params: GetChatAvailability$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatAvailability>> {
  const rb = new RequestBuilder(rootUrl, getChatAvailability.PATH, 'get');
  if (params) {
    rb.path('team', params.team, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatAvailability>;
    })
  );
}

getChatAvailability.PATH = '/api/v1/teams/{team}/chat';
