// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getManagedAccount = `-- name: GetManagedAccount :one
SELECT u.id, u.username, u.display_name, u.deactivated_at, u.global_admin
FROM users u
JOIN local_accounts a ON a.user_id = u.id
WHERE u.username = $1 AND a.managing_tenant_id = $2
`

type GetManagedAccountParams struct {
	Username *string
	TenantID *uuid.UUID
}

type GetManagedAccountRow struct {
	ID            uuid.UUID
	Username      *string
	DisplayName   string
	DeactivatedAt *time.Time
	GlobalAdmin   bool
}

// One of the tenant's managed accounts by username; no row when the username
// names none — also one another tenant manages, which this tenant cannot see.
func (q *Queries) GetManagedAccount(ctx context.Context, arg GetManagedAccountParams) (GetManagedAccountRow, error) {
	row := q.db.QueryRow(ctx, getManagedAccount, arg.Username, arg.TenantID)
	var i GetManagedAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.DeactivatedAt,
		&i.GlobalAdmin,
	)
	return i, err
}

const getOwnLocalAccount = `-- name: GetOwnLocalAccount :one
SELECT password_hash, origin
FROM local_accounts
WHERE user_id = $1
`

type GetOwnLocalAccountRow struct {
	PasswordHash string
	Origin       string
}

// The person's own account row: the hash of the current password and where the
// account comes from.
func (q *Queries) GetOwnLocalAccount(ctx context.Context, userID uuid.UUID) (GetOwnLocalAccountRow, error) {
	row := q.db.QueryRow(ctx, getOwnLocalAccount, userID)
	var i GetOwnLocalAccountRow
	err := row.Scan(&i.PasswordHash, &i.Origin)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT u.id, u.username, u.deactivated_at, u.global_admin,
       a.password_hash AS account_password_hash, a.origin AS account_origin
FROM users u
LEFT JOIN local_accounts a ON a.user_id = u.id
WHERE u.username = $1
`

type GetUserByUsernameRow struct {
	ID                  uuid.UUID
	Username            *string
	DeactivatedAt       *time.Time
	GlobalAdmin         bool
	AccountPasswordHash *string
	AccountOrigin       *string
}

// The start-up synchronisation's lookup of the account COWORK_LOCAL_ADMIN_USERNAME
// names (app.job = 'bootstrap'): the person, and what a local account has, if
// they have one.
func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DeactivatedAt,
		&i.GlobalAdmin,
		&i.AccountPasswordHash,
		&i.AccountOrigin,
	)
	return i, err
}

const listConfigAccounts = `-- name: ListConfigAccounts :many
SELECT u.id, u.username, u.deactivated_at
FROM local_accounts a
JOIN users u ON u.id = a.user_id
WHERE a.origin = 'config'
ORDER BY u.username
`

type ListConfigAccountsRow struct {
	ID            uuid.UUID
	Username      *string
	DeactivatedAt *time.Time
}

// The accounts the configuration keeps (docs/adr/0032 D2, D4).
func (q *Queries) ListConfigAccounts(ctx context.Context) ([]ListConfigAccountsRow, error) {
	rows, err := q.db.Query(ctx, listConfigAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigAccountsRow{}
	for rows.Next() {
		var i ListConfigAccountsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DeactivatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedAccounts = `-- name: ListManagedAccounts :many
SELECT u.id, u.username, u.display_name, u.deactivated_at, u.created_at, a.password_change_required,
       COALESCE(m.role::text, '')::text AS role,
       EXISTS (SELECT 1 FROM login_locks l
               WHERE l.username = u.username AND (l.sticky OR l.locked_at > $1))::boolean AS locked
FROM local_accounts a
JOIN users u ON u.id = a.user_id
LEFT JOIN (SELECT user_id, max(role)::tenant_role AS role FROM memberships
           WHERE tenant_id = $2 GROUP BY user_id) m ON m.user_id = u.id
WHERE a.managing_tenant_id = $2
  AND ($3::uuid IS NULL OR u.id > $3::uuid)
ORDER BY u.id
LIMIT $4
`

type ListManagedAccountsParams struct {
	LockSince time.Time
	TenantID  uuid.UUID
	After     *uuid.UUID
	PageSize  int32
}

type ListManagedAccountsRow struct {
	ID                     uuid.UUID
	Username               *string
	DisplayName            string
	DeactivatedAt          *time.Time
	CreatedAt              time.Time
	PasswordChangeRequired bool
	Role                   string
	Locked                 bool
}

// The local accounts a tenant manages (docs/adr/0033 D1, D5), by person id, a
// page after the cursor's person: the person's highest role in the tenant — empty
// when they no longer have one — and whether the account is locked at the moment.
func (q *Queries) ListManagedAccounts(ctx context.Context, arg ListManagedAccountsParams) ([]ListManagedAccountsRow, error) {
	rows, err := q.db.Query(ctx, listManagedAccounts,
		arg.LockSince,
		arg.TenantID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedAccountsRow{}
	for rows.Next() {
		var i ListManagedAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.PasswordChangeRequired,
			&i.Role,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
