// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAttachments = `-- name: CountAttachments :one
SELECT count(*)::bigint AS attachments
FROM attachments
WHERE tenant_id = $1 AND ticket_id = $2
`

type CountAttachmentsParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

// The ticket's attachments, against the per-ticket count (docs/adr/0016 D6).
func (q *Queries) CountAttachments(ctx context.Context, arg CountAttachmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachments, arg.TenantID, arg.TicketID)
	var attachments int64
	err := row.Scan(&attachments)
	return attachments, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT a.id, a.comment_id, a.file_name, a.size, a.sha256, a.content_type, a.uploaded_by,
       u.username AS uploaded_by_username, u.display_name AS uploaded_by_name, a.agent, a.token_id, a.token_name,
       a.created_at
FROM attachments a
JOIN tickets t ON t.tenant_id = a.tenant_id AND t.id = a.ticket_id
LEFT JOIN users u ON u.id = a.uploaded_by
WHERE a.tenant_id = $1 AND a.ticket_id = $2 AND a.id = $3
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
`

type GetAttachmentParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	ID       uuid.UUID
}

type GetAttachmentRow struct {
	ID                 uuid.UUID
	CommentID          *uuid.UUID
	FileName           string
	Size               int64
	Sha256             []byte
	ContentType        string
	UploadedBy         uuid.UUID
	UploadedByUsername *string
	UploadedByName     *string
	Agent              *string
	TokenID            *uuid.UUID
	TokenName          *string
	CreatedAt          time.Time
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.TenantID, arg.TicketID, arg.ID)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.FileName,
		&i.Size,
		&i.Sha256,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedByUsername,
		&i.UploadedByName,
		&i.Agent,
		&i.TokenID,
		&i.TokenName,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many

SELECT a.id, a.comment_id, a.file_name, a.size, a.sha256, a.content_type, a.uploaded_by,
       u.username AS uploaded_by_username, u.display_name AS uploaded_by_name, a.agent, a.token_id, a.token_name,
       a.created_at
FROM attachments a
JOIN tickets t ON t.tenant_id = a.tenant_id AND t.id = a.ticket_id
LEFT JOIN users u ON u.id = a.uploaded_by
WHERE a.tenant_id = $1 AND a.ticket_id = $2
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND ($3::uuid IS NULL OR a.id > $3::uuid)
ORDER BY a.id
LIMIT $4
`

type ListAttachmentsParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListAttachmentsRow struct {
	ID                 uuid.UUID
	CommentID          *uuid.UUID
	FileName           string
	Size               int64
	Sha256             []byte
	ContentType        string
	UploadedBy         uuid.UUID
	UploadedByUsername *string
	UploadedByName     *string
	Agent              *string
	TokenID            *uuid.UUID
	TokenName          *string
	CreatedAt          time.Time
}

// An attachment is visible with its ticket (docs/adr/0016 D2).
func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments,
		arg.TenantID,
		arg.TicketID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsRow{}
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.FileName,
			&i.Size,
			&i.Sha256,
			&i.ContentType,
			&i.UploadedBy,
			&i.UploadedByUsername,
			&i.UploadedByName,
			&i.Agent,
			&i.TokenID,
			&i.TokenName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketImages = `-- name: ListTicketImages :many
SELECT a.ticket_id, a.id, a.content_type
FROM attachments a
JOIN tickets t ON t.tenant_id = a.tenant_id AND t.id = a.ticket_id
WHERE a.tenant_id = $1 AND a.ticket_id = ANY($2::uuid[])
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
ORDER BY a.ticket_id, a.id
`

type ListTicketImagesParams struct {
	TenantID  uuid.UUID
	TicketIds []uuid.UUID
}

type ListTicketImagesRow struct {
	TicketID    uuid.UUID
	ID          uuid.UUID
	ContentType string
}

// The attachments of the tickets a rendered text may show as images, with
// their type; the caller keeps the raster ones (docs/adr/0016 D7).
func (q *Queries) ListTicketImages(ctx context.Context, arg ListTicketImagesParams) ([]ListTicketImagesRow, error) {
	rows, err := q.db.Query(ctx, listTicketImages, arg.TenantID, arg.TicketIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketImagesRow{}
	for rows.Next() {
		var i ListTicketImagesRow
		if err := rows.Scan(&i.TicketID, &i.ID, &i.ContentType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
