// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChatCapabilities = `-- name: GetChatCapabilities :one
SELECT capabilities, updated_at
FROM chat_capabilities
WHERE user_id = $1
`

type GetChatCapabilitiesRow struct {
	Capabilities []string
	UpdatedAt    time.Time
}

// The capabilities the person gave the chat (docs/adr/0043 D5); no row is the
// default. The policy admits the person's own row only.
func (q *Queries) GetChatCapabilities(ctx context.Context, userID uuid.UUID) (GetChatCapabilitiesRow, error) {
	row := q.db.QueryRow(ctx, getChatCapabilities, userID)
	var i GetChatCapabilitiesRow
	err := row.Scan(&i.Capabilities, &i.UpdatedAt)
	return i, err
}
