// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context.sql

package readq

import (
	"context"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const contextLinks = `-- name: ContextLinks :many

SELECT l.id, l.type, (l.source_id = $1::uuid)::boolean AS outgoing,
       op.key AS other_project_key, o.number AS other_number, o.title AS other_title, o.state AS other_state,
       au.display_name AS other_assignee_name
FROM ticket_links l
JOIN tickets o ON o.tenant_id = l.tenant_id
     AND o.id = CASE WHEN l.source_id = $1::uuid THEN l.target_id ELSE l.source_id END
JOIN projects op ON op.tenant_id = o.tenant_id AND op.id = o.project_id
LEFT JOIN users au ON au.id = o.assignee_id
WHERE l.tenant_id = $2
  AND (l.source_id = $1::uuid OR l.target_id = $1::uuid)
  AND o.deleted_at IS NULL AND app_ticket_visible(o.project_id, o.confidential, o.assignee_id, o.reporter_id)
ORDER BY l.type, outgoing DESC, op.key, o.number
LIMIT $3
`

type ContextLinksParams struct {
	TicketID uuid.UUID
	TenantID uuid.UUID
	PageSize int32
}

type ContextLinksRow struct {
	ID                uuid.UUID
	Type              domain.LinkType
	Outgoing          bool
	OtherProjectKey   string
	OtherNumber       int32
	OtherTitle        string
	OtherState        domain.TicketState
	OtherAssigneeName *string
}

// What the context of a ticket shows beside the canonical document
// (docs/adr/0044 D2). The comments, the attachments, the activity and the
// prerequisite tree are read with the queries of their own routes; the links
// need the facts a reader of one ticket wants of the others.
// The ticket's links in both directions with each other end's state and
// assignee; a link whose other end the caller cannot see is absent
// (docs/adr/0065 D4).
func (q *Queries) ContextLinks(ctx context.Context, arg ContextLinksParams) ([]ContextLinksRow, error) {
	rows, err := q.db.Query(ctx, contextLinks, arg.TicketID, arg.TenantID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextLinksRow{}
	for rows.Next() {
		var i ContextLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Outgoing,
			&i.OtherProjectKey,
			&i.OtherNumber,
			&i.OtherTitle,
			&i.OtherState,
			&i.OtherAssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
