// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const dashboardAge = `-- name: DashboardAge :one
SELECT count(*) FILTER (WHERE t.opened_at > $1::timestamptz)::bigint AS under_7,
       count(*) FILTER (WHERE t.opened_at <= $1::timestamptz
                          AND t.opened_at > $2::timestamptz)::bigint AS under_30,
       count(*) FILTER (WHERE t.opened_at <= $2::timestamptz
                          AND t.opened_at > $3::timestamptz)::bigint AS under_90,
       count(*) FILTER (WHERE t.opened_at <= $3::timestamptz
                          AND t.opened_at > $4::timestamptz)::bigint AS under_365,
       count(*) FILTER (WHERE t.opened_at <= $4::timestamptz)::bigint AS older
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $5
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state NOT IN ('done', 'dropped')
  AND (p.key = ANY ($6::text[])
       OR (cardinality($6::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($7::text[]))
`

type DashboardAgeParams struct {
	Cut7            time.Time
	Cut30           time.Time
	Cut90           time.Time
	Cut365          time.Time
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
}

type DashboardAgeRow struct {
	Under7   int64
	Under30  int64
	Under90  int64
	Under365 int64
	Older    int64
}

// Tile 5: the open tickets per age bucket, by their filing against the
// bounds the handler computes from its clock: opened after a bound is
// younger than it.
// visibility: app_ticket_visible on every ticket counted.
func (q *Queries) DashboardAge(ctx context.Context, arg DashboardAgeParams) (DashboardAgeRow, error) {
	row := q.db.QueryRow(ctx, dashboardAge,
		arg.Cut7,
		arg.Cut30,
		arg.Cut90,
		arg.Cut365,
		arg.TenantID,
		arg.Projects,
		arg.WithoutProjects,
	)
	var i DashboardAgeRow
	err := row.Scan(
		&i.Under7,
		&i.Under30,
		&i.Under90,
		&i.Under365,
		&i.Older,
	)
	return i, err
}

const dashboardBlocked = `-- name: DashboardBlocked :many
SELECT count(*) OVER ()::bigint AS tickets, p.key AS project_key, t.number, t.title, t.block_kind,
       coalesce((SELECT max(a.created_at) FROM audit_events a
                 WHERE a.tenant_id = t.tenant_id AND a.ticket_id = t.id
                   AND a.action = 'transitioned' AND a.after ->> 'state' = 'blocked'),
                t.updated_at)::timestamptz AS since
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state = 'blocked'
  AND (p.key = ANY ($2::text[])
       OR (cardinality($2::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($3::text[]))
ORDER BY since, t.id
LIMIT 1
`

type DashboardBlockedParams struct {
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
}

type DashboardBlockedRow struct {
	Tickets    int64
	ProjectKey string
	Number     int32
	Title      string
	BlockKind  *domain.BlockKind
	Since      time.Time
}

// Tile 4: the blocked tickets' count, on the one blocked longest. A ticket is
// blocked since its latest act that moved it into blocked (docs/adr/0026), or
// since its last update where no act records one; the earlier id on a tie.
// No row while none is blocked.
// visibility: app_ticket_visible on every ticket counted and named; the act
// is read only for a ticket the caller sees.
func (q *Queries) DashboardBlocked(ctx context.Context, arg DashboardBlockedParams) ([]DashboardBlockedRow, error) {
	rows, err := q.db.Query(ctx, dashboardBlocked, arg.TenantID, arg.Projects, arg.WithoutProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardBlockedRow{}
	for rows.Next() {
		var i DashboardBlockedRow
		if err := rows.Scan(
			&i.Tickets,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.BlockKind,
			&i.Since,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardDecisions = `-- name: DashboardDecisions :many
SELECT count(*) OVER ()::bigint AS questions, p.key AS project_key, t.number AS ticket_number,
       t.title AS ticket_title, q.number AS question_number, q.question, q.created_at
FROM questions q
JOIN tickets t ON t.tenant_id = q.tenant_id AND t.id = q.ticket_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE q.tenant_id = $1 AND q.status = 'open'
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND (p.key = ANY ($2::text[])
       OR (cardinality($2::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($3::text[]))
ORDER BY q.created_at, q.id
LIMIT 1
`

type DashboardDecisionsParams struct {
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
}

type DashboardDecisionsRow struct {
	Questions      int64
	ProjectKey     string
	TicketNumber   int32
	TicketTitle    string
	QuestionNumber int32
	Question       string
	CreatedAt      time.Time
}

// Tile 8: the open questions' count, on the one asked first, the earlier id
// on a tie (docs/adr/0011 D3); no row while none is open.
// visibility: app_ticket_visible on the ticket of every question counted.
func (q *Queries) DashboardDecisions(ctx context.Context, arg DashboardDecisionsParams) ([]DashboardDecisionsRow, error) {
	rows, err := q.db.Query(ctx, dashboardDecisions, arg.TenantID, arg.Projects, arg.WithoutProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardDecisionsRow{}
	for rows.Next() {
		var i DashboardDecisionsRow
		if err := rows.Scan(
			&i.Questions,
			&i.ProjectKey,
			&i.TicketNumber,
			&i.TicketTitle,
			&i.QuestionNumber,
			&i.Question,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardLeadTime = `-- name: DashboardLeadTime :one
SELECT count(*)::bigint AS tickets,
       coalesce(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM t.done_at - t.opened_at)),
                0)::float8 AS median_seconds
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state = 'done'
  AND t.done_at >= $2::timestamptz AND t.done_at < $3::timestamptz
  AND (p.key = ANY ($4::text[])
       OR (cardinality($4::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($5::text[]))
`

type DashboardLeadTimeParams struct {
	TenantID        uuid.UUID
	Since           time.Time
	Until           time.Time
	Projects        []string
	WithoutProjects []string
}

type DashboardLeadTimeRow struct {
	Tickets       int64
	MedianSeconds float64
}

// Tile 7: the tickets done now whose done_at lies in [since, until), and the
// median of their seconds from filing to done; 0 while there is none.
// visibility: app_ticket_visible on every ticket measured.
func (q *Queries) DashboardLeadTime(ctx context.Context, arg DashboardLeadTimeParams) (DashboardLeadTimeRow, error) {
	row := q.db.QueryRow(ctx, dashboardLeadTime,
		arg.TenantID,
		arg.Since,
		arg.Until,
		arg.Projects,
		arg.WithoutProjects,
	)
	var i DashboardLeadTimeRow
	err := row.Scan(&i.Tickets, &i.MedianSeconds)
	return i, err
}

const dashboardOpenBySeverity = `-- name: DashboardOpenBySeverity :many
SELECT t.severity, count(*)::bigint AS tickets
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state NOT IN ('done', 'dropped')
  AND (p.key = ANY ($2::text[])
       OR (cardinality($2::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($3::text[]))
GROUP BY t.severity
ORDER BY t.severity
`

type DashboardOpenBySeverityParams struct {
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
}

type DashboardOpenBySeverityRow struct {
	Severity domain.Severity
	Tickets  int64
}

// Tile 2: the open tickets per severity; a severity without one has no row.
// visibility: app_ticket_visible on every ticket counted.
func (q *Queries) DashboardOpenBySeverity(ctx context.Context, arg DashboardOpenBySeverityParams) ([]DashboardOpenBySeverityRow, error) {
	rows, err := q.db.Query(ctx, dashboardOpenBySeverity, arg.TenantID, arg.Projects, arg.WithoutProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardOpenBySeverityRow{}
	for rows.Next() {
		var i DashboardOpenBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Tickets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardOpenByState = `-- name: DashboardOpenByState :many

SELECT p.key AS project_key, t.state, count(*)::bigint AS tickets
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state NOT IN ('done', 'dropped')
  AND (p.key = ANY ($2::text[])
       OR (cardinality($2::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($3::text[]))
GROUP BY p.key, t.state
ORDER BY p.key, t.state
`

type DashboardOpenByStateParams struct {
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
}

type DashboardOpenByStateRow struct {
	ProjectKey string
	State      domain.TicketState
	Tickets    int64
}

// The tiles of the tenant's dashboard (docs/adr/0018 D6), read in one
// transaction by GET …/dashboard. Each counts only what the caller can see:
// app_ticket_visible holds every ticket a query reads, so a restricted project
// or a confidential ticket the caller cannot see counts nowhere and is named
// nowhere (docs/adr/0034 D4, docs/adr/0065 D4).
//
// The counted projects: the keys of `projects`, or — while it is empty —
// every project that is not archived; never one of `without_projects`. The
// handler passes both arrays, empty rather than NULL. Open is every state but
// done and dropped (docs/adr/0009 D1).
// Tile 1: the open tickets per project and state.
// visibility: app_ticket_visible on every ticket counted.
func (q *Queries) DashboardOpenByState(ctx context.Context, arg DashboardOpenByStateParams) ([]DashboardOpenByStateRow, error) {
	rows, err := q.db.Query(ctx, dashboardOpenByState, arg.TenantID, arg.Projects, arg.WithoutProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardOpenByStateRow{}
	for rows.Next() {
		var i DashboardOpenByStateRow
		if err := rows.Scan(&i.ProjectKey, &i.State, &i.Tickets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecent = `-- name: DashboardRecent :many
SELECT p.key AS project_key, t.number, t.type, t.title, t.state, t.updated_at
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state NOT IN ('done', 'dropped')
  AND (p.key = ANY ($2::text[])
       OR (cardinality($2::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($3::text[]))
ORDER BY t.updated_at DESC, t.id DESC
LIMIT $4
`

type DashboardRecentParams struct {
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
	PageSize        int32
}

type DashboardRecentRow struct {
	ProjectKey string
	Number     int32
	Type       domain.TicketType
	Title      string
	State      domain.TicketState
	UpdatedAt  time.Time
}

// Beside the tiles: the open tickets updated last, the later id on a tie.
// visibility: app_ticket_visible on every ticket listed.
func (q *Queries) DashboardRecent(ctx context.Context, arg DashboardRecentParams) ([]DashboardRecentRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecent,
		arg.TenantID,
		arg.Projects,
		arg.WithoutProjects,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentRow{}
	for rows.Next() {
		var i DashboardRecentRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.Number,
			&i.Type,
			&i.Title,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSecurity = `-- name: DashboardSecurity :many
SELECT DISTINCT ON (t.security) t.security, count(*) OVER (PARTITION BY t.security)::bigint AS tickets,
       p.key AS project_key, t.number, t.title, t.opened_at
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state NOT IN ('done', 'dropped')
  AND t.security IN ('live', 'boundary')
  AND (p.key = ANY ($2::text[])
       OR (cardinality($2::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($3::text[]))
ORDER BY t.security, t.opened_at, t.id
`

type DashboardSecurityParams struct {
	TenantID        uuid.UUID
	Projects        []string
	WithoutProjects []string
}

type DashboardSecurityRow struct {
	Security   domain.SecurityClass
	Tickets    int64
	ProjectKey string
	Number     int32
	Title      string
	OpenedAt   time.Time
}

// Tile 3: per class live and boundary that has an open ticket, the count and
// the oldest by filing, the earlier id on a tie.
// visibility: app_ticket_visible on every ticket counted and named.
func (q *Queries) DashboardSecurity(ctx context.Context, arg DashboardSecurityParams) ([]DashboardSecurityRow, error) {
	rows, err := q.db.Query(ctx, dashboardSecurity, arg.TenantID, arg.Projects, arg.WithoutProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardSecurityRow{}
	for rows.Next() {
		var i DashboardSecurityRow
		if err := rows.Scan(
			&i.Security,
			&i.Tickets,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardThroughput = `-- name: DashboardThroughput :many
SELECT date_trunc('week', t.done_at AT TIME ZONE 'UTC')::date AS week, count(*)::bigint AS tickets
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE t.tenant_id = $1
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND t.state = 'done'
  AND t.done_at >= $2::timestamptz AND t.done_at < $3::timestamptz
  AND (p.key = ANY ($4::text[])
       OR (cardinality($4::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($5::text[]))
GROUP BY 1
ORDER BY 1
`

type DashboardThroughputParams struct {
	TenantID        uuid.UUID
	Since           time.Time
	Until           time.Time
	Projects        []string
	WithoutProjects []string
}

type DashboardThroughputRow struct {
	Week    time.Time
	Tickets int64
}

// Tile 6: the tickets done now per ISO week of their done_at in UTC, the
// Monday naming the week, inside [since, until); a week without one has no
// row (docs/adr/0019 D2).
// visibility: app_ticket_visible on every ticket counted.
func (q *Queries) DashboardThroughput(ctx context.Context, arg DashboardThroughputParams) ([]DashboardThroughputRow, error) {
	rows, err := q.db.Query(ctx, dashboardThroughput,
		arg.TenantID,
		arg.Since,
		arg.Until,
		arg.Projects,
		arg.WithoutProjects,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardThroughputRow{}
	for rows.Next() {
		var i DashboardThroughputRow
		if err := rows.Scan(&i.Week, &i.Tickets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTime = `-- name: DashboardTime :many
SELECT p.key AS project_key, p.name AS project_name, sum(e.minutes)::bigint AS minutes
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE e.tenant_id = $1 AND e.voided_at IS NULL
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
  AND e.day >= $2::date AND e.day <= $3::date
  AND (p.key = ANY ($4::text[])
       OR (cardinality($4::text[]) = 0 AND p.archived_at IS NULL))
  AND NOT (p.key = ANY ($5::text[]))
GROUP BY p.key, p.name
ORDER BY p.key
`

type DashboardTimeParams struct {
	TenantID        uuid.UUID
	FromDay         time.Time
	ToDay           time.Time
	Projects        []string
	WithoutProjects []string
}

type DashboardTimeRow struct {
	ProjectKey  string
	ProjectName string
	Minutes     int64
}

// Tile 9: the minutes booked on a day of [from_day, to_day] per project,
// voided entries left out (docs/adr/0017 D7, D10).
// visibility: app_ticket_visible on every entry's ticket, and app_time_visible
// on the entry (docs/adr/0034 D5).
func (q *Queries) DashboardTime(ctx context.Context, arg DashboardTimeParams) ([]DashboardTimeRow, error) {
	rows, err := q.db.Query(ctx, dashboardTime,
		arg.TenantID,
		arg.FromDay,
		arg.ToDay,
		arg.Projects,
		arg.WithoutProjects,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardTimeRow{}
	for rows.Next() {
		var i DashboardTimeRow
		if err := rows.Scan(&i.ProjectKey, &i.ProjectName, &i.Minutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
