// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package readq

import (
	"context"

	"github.com/google/uuid"
)

const exportAttachmentNames = `-- name: ExportAttachmentNames :many
SELECT a.file_name
FROM attachments a
JOIN tickets t ON t.tenant_id = a.tenant_id AND t.id = a.ticket_id
WHERE a.tenant_id = $1 AND a.ticket_id = $2
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
ORDER BY a.id
`

type ExportAttachmentNamesParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

func (q *Queries) ExportAttachmentNames(ctx context.Context, arg ExportAttachmentNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, exportAttachmentNames, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_name string
		if err := rows.Scan(&file_name); err != nil {
			return nil, err
		}
		items = append(items, file_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportQuestions = `-- name: ExportQuestions :many
SELECT q.number, q.question, q.options, q.recommendation, q.answer, q.status
FROM questions q
JOIN tickets t ON t.tenant_id = q.tenant_id AND t.id = q.ticket_id
WHERE q.tenant_id = $1 AND q.ticket_id = $2
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
ORDER BY q.number
`

type ExportQuestionsParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

type ExportQuestionsRow struct {
	Number         int32
	Question       string
	Options        string
	Recommendation string
	Answer         *string
	Status         string
}

func (q *Queries) ExportQuestions(ctx context.Context, arg ExportQuestionsParams) ([]ExportQuestionsRow, error) {
	rows, err := q.db.Query(ctx, exportQuestions, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportQuestionsRow{}
	for rows.Next() {
		var i ExportQuestionsRow
		if err := rows.Scan(
			&i.Number,
			&i.Question,
			&i.Options,
			&i.Recommendation,
			&i.Answer,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionNote = `-- name: TransitionNote :one

SELECT coalesce(note, '')::text AS note, coalesce(reason, '')::text AS reason
FROM audit_events
WHERE tenant_id = $1 AND ticket_id = $2 AND action = 'transitioned'
  AND after->>'state' = $3::text
ORDER BY id DESC
LIMIT 1
`

type TransitionNoteParams struct {
	TenantID *uuid.UUID
	TicketID *uuid.UUID
	State    string
}

type TransitionNoteRow struct {
	Note   string
	Reason string
}

// The parts of the Markdown export beyond the ticket row (docs/adr/0044 D1);
// the caller has read the ticket through the predicate.
// The note and the reason of the act that last brought the ticket into a
// state: where the export's shipped and dropped-reason come from
// (docs/adr/0009 D5).
func (q *Queries) TransitionNote(ctx context.Context, arg TransitionNoteParams) (TransitionNoteRow, error) {
	row := q.db.QueryRow(ctx, transitionNote, arg.TenantID, arg.TicketID, arg.State)
	var i TransitionNoteRow
	err := row.Scan(&i.Note, &i.Reason)
	return i, err
}
