// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getGitHubWebhook = `-- name: GetGitHubWebhook :one

SELECT s.created_at, s.created_by, u.username AS created_by_username, u.display_name AS created_by_name
FROM github_webhook_secrets s
LEFT JOIN users u ON u.id = s.created_by
WHERE s.tenant_id = $1
`

type GetGitHubWebhookRow struct {
	CreatedAt         time.Time
	CreatedBy         uuid.UUID
	CreatedByUsername *string
	CreatedByName     *string
}

// GitHub's webhook (docs/adr/0071): the tenant's secret as its
// administrators and the webhook read it, and a ticket's pull requests.
// When and by whom the tenant's secret was made, never the secret: the
// restrictive policy of migration 42 shows the row to the tenant's
// administrators and the webhook's job only.
func (q *Queries) GetGitHubWebhook(ctx context.Context, tenantID uuid.UUID) (GetGitHubWebhookRow, error) {
	row := q.db.QueryRow(ctx, getGitHubWebhook, tenantID)
	var i GetGitHubWebhookRow
	err := row.Scan(
		&i.CreatedAt,
		&i.CreatedBy,
		&i.CreatedByUsername,
		&i.CreatedByName,
	)
	return i, err
}

const getGitHubWebhookSecret = `-- name: GetGitHubWebhookSecret :one
SELECT secret FROM github_webhook_secrets WHERE tenant_id = $1
`

// The sealed secret a delivery's signature is verified with (D3).
func (q *Queries) GetGitHubWebhookSecret(ctx context.Context, tenantID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGitHubWebhookSecret, tenantID)
	var secret []byte
	err := row.Scan(&secret)
	return secret, err
}

const listTicketPullRequests = `-- name: ListTicketPullRequests :many
SELECT p.id, p.kind, p.repository, p.number, p.sha, p.title, p.state, p.url, p.author, p.merged_at, p.found_in,
       p.first_seen_at, p.last_seen_at
FROM ticket_pull_requests p
JOIN tickets t ON t.tenant_id = p.tenant_id AND t.id = p.ticket_id
WHERE p.tenant_id = $1 AND p.ticket_id = $2 AND p.removed_at IS NULL
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND ($3::uuid IS NULL OR p.id > $3::uuid)
ORDER BY p.id
LIMIT $4
`

type ListTicketPullRequestsParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListTicketPullRequestsRow struct {
	ID          uuid.UUID
	Kind        string
	Repository  string
	Number      *int32
	Sha         *string
	Title       string
	State       string
	Url         string
	Author      *string
	MergedAt    *time.Time
	FoundIn     string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
}

// What the webhook linked to a ticket the caller sees (D6), oldest link
// first, without the links a person removed. The ticket's predicate holds
// them as it holds the ticket's other children (docs/adr/0065 D1).
func (q *Queries) ListTicketPullRequests(ctx context.Context, arg ListTicketPullRequestsParams) ([]ListTicketPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listTicketPullRequests,
		arg.TenantID,
		arg.TicketID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketPullRequestsRow{}
	for rows.Next() {
		var i ListTicketPullRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Repository,
			&i.Number,
			&i.Sha,
			&i.Title,
			&i.State,
			&i.Url,
			&i.Author,
			&i.MergedAt,
			&i.FoundIn,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
