// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package readq

import (
	"context"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT fingerprint, response_status, response_headers, response_body
FROM idempotency_keys
WHERE token_id = $1 AND key = $2 AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	TokenID uuid.UUID
	Key     uuid.UUID
}

type GetIdempotencyKeyRow struct {
	Fingerprint     []byte
	ResponseStatus  int16
	ResponseHeaders []byte
	ResponseBody    []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TokenID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Fingerprint,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
	)
	return i, err
}
