// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const countUnread = `-- name: CountUnread :one
SELECT count(*)::integer AS unread
FROM notifications n
JOIN tickets t ON t.tenant_id = n.tenant_id AND t.id = n.ticket_id
JOIN audit_events a ON a.tenant_id = n.tenant_id AND a.id = n.audit_event_id
JOIN tickets xt ON xt.tenant_id = a.tenant_id AND xt.id = a.ticket_id
WHERE n.tenant_id = $1 AND n.user_id = $2 AND n.read_at IS NULL
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_ticket_visible(xt.project_id, xt.confidential, xt.assignee_id, xt.reporter_id)
`

type CountUnreadParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

// The unread count of the page header (D1), over what ListInbox shows.
func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.TenantID, arg.UserID)
	var unread int32
	err := row.Scan(&unread)
	return unread, err
}

const findNotification = `-- name: FindNotification :one
SELECT (n.read_at IS NOT NULL)::boolean AS read
FROM notifications n
JOIN tickets t ON t.tenant_id = n.tenant_id AND t.id = n.ticket_id
JOIN audit_events a ON a.tenant_id = n.tenant_id AND a.id = n.audit_event_id
JOIN tickets xt ON xt.tenant_id = a.tenant_id AND xt.id = a.ticket_id
WHERE n.tenant_id = $1 AND n.user_id = $2 AND n.id = $3
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_ticket_visible(xt.project_id, xt.confidential, xt.assignee_id, xt.reporter_id)
`

type FindNotificationParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	ID       uuid.UUID
}

// Whether one of the person's notifications is in the tenant, and read, over
// what ListInbox shows: marking it read finds its tenant so.
func (q *Queries) FindNotification(ctx context.Context, arg FindNotificationParams) (bool, error) {
	row := q.db.QueryRow(ctx, findNotification, arg.TenantID, arg.UserID, arg.ID)
	var read bool
	err := row.Scan(&read)
	return read, err
}

const listInbox = `-- name: ListInbox :many

SELECT n.id, n.reason::text AS reason, n.read_at, n.created_at,
       tp.key AS project_key, t.number, t.title, t.state,
       a.actor_user_id, u.username AS actor_username, u.display_name AS actor_name, a.actor_system,
       a.agent, a.token_id, a.token_name, a.entity_type, a.entity_id, a.action::text AS action, a.before, a.after,
       a.reason AS act_reason, a.note AS act_note, a.explained_by_comment_id, a.refs, a.id AS act_id,
       a.created_at AS act_at,
       xt.id AS act_ticket_id, xp.key AS act_project_key, xt.number AS act_number, xt.title AS act_title,
       xt.state AS act_state,
       (c.withdrawn_at IS NOT NULL OR q.withdrawn_at IS NOT NULL)::boolean AS withdrawn
FROM notifications n
JOIN tickets t ON t.tenant_id = n.tenant_id AND t.id = n.ticket_id
JOIN projects tp ON tp.tenant_id = t.tenant_id AND tp.id = t.project_id
JOIN audit_events a ON a.tenant_id = n.tenant_id AND a.id = n.audit_event_id
JOIN tickets xt ON xt.tenant_id = a.tenant_id AND xt.id = a.ticket_id
JOIN projects xp ON xp.tenant_id = xt.tenant_id AND xp.id = xt.project_id
LEFT JOIN users u ON u.id = a.actor_user_id
LEFT JOIN comments c ON a.entity_type = 'comment' AND c.tenant_id = a.tenant_id AND c.id = a.entity_id
LEFT JOIN questions q ON a.entity_type = 'question' AND q.tenant_id = a.tenant_id AND q.id = a.entity_id
WHERE n.tenant_id = $1 AND n.user_id = $2
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_ticket_visible(xt.project_id, xt.confidential, xt.assignee_id, xt.reporter_id)
  AND ($3::uuid IS NULL OR n.id < $3::uuid)
ORDER BY n.id DESC
LIMIT $4
`

type ListInboxParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Before   *uuid.UUID
	PageSize int32
}

type ListInboxRow struct {
	ID                   uuid.UUID
	Reason               string
	ReadAt               *time.Time
	CreatedAt            time.Time
	ProjectKey           string
	Number               int32
	Title                string
	State                domain.TicketState
	ActorUserID          *uuid.UUID
	ActorUsername        *string
	ActorName            *string
	ActorSystem          *string
	Agent                *string
	TokenID              *uuid.UUID
	TokenName            *string
	EntityType           string
	EntityID             *uuid.UUID
	Action               string
	Before               []byte
	After                []byte
	ActReason            *string
	ActNote              *string
	ExplainedByCommentID *uuid.UUID
	Refs                 []uuid.UUID
	ActID                uuid.UUID
	ActAt                time.Time
	ActTicketID          uuid.UUID
	ActProjectKey        string
	ActNumber            int32
	ActTitle             string
	ActState             domain.TicketState
	Withdrawn            bool
}

// The person's inbox in one tenant (docs/adr/0020 D1); the person-level route
// reads it once per tenant of the person (docs/adr/0021 D5). A notification of
// a ticket the person no longer sees, or whose act is on such a ticket, is
// absent (docs/adr/0065 D5).
// Newest first, each with the act it renders from (D3) and the tickets as
// they are now: the one it is about, and the one the act is on.
func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error) {
	rows, err := q.db.Query(ctx, listInbox,
		arg.TenantID,
		arg.UserID,
		arg.Before,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxRow{}
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Reason,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.State,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.ActorName,
			&i.ActorSystem,
			&i.Agent,
			&i.TokenID,
			&i.TokenName,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.ActReason,
			&i.ActNote,
			&i.ExplainedByCommentID,
			&i.Refs,
			&i.ActID,
			&i.ActAt,
			&i.ActTicketID,
			&i.ActProjectKey,
			&i.ActNumber,
			&i.ActTitle,
			&i.ActState,
			&i.Withdrawn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
