// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const blocksPathExists = `-- name: BlocksPathExists :one
SELECT blocks_path_exists($1, $2, $3)::boolean AS reachable
`

type BlocksPathExistsParams struct {
	TenantID uuid.UUID
	FromID   uuid.UUID
	ToID     uuid.UUID
}

// Whether to_id is reachable from from_id over blocks links (docs/adr/0012 D4).
// visibility: exempt (an integrity walk returns no ticket)
func (q *Queries) BlocksPathExists(ctx context.Context, arg BlocksPathExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, blocksPathExists, arg.TenantID, arg.FromID, arg.ToID)
	var reachable bool
	err := row.Scan(&reachable)
	return reachable, err
}

const getLink = `-- name: GetLink :one
SELECT l.id, l.created_by, u.username AS created_by_username, u.display_name AS created_by_name, l.created_at
FROM ticket_links l
LEFT JOIN users u ON u.id = l.created_by
WHERE l.tenant_id = $1 AND l.type = $2
  AND l.source_id = $3 AND l.target_id = $4
`

type GetLinkParams struct {
	TenantID uuid.UUID
	Type     domain.LinkType
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type GetLinkRow struct {
	ID                uuid.UUID
	CreatedBy         uuid.UUID
	CreatedByUsername *string
	CreatedByName     *string
	CreatedAt         time.Time
}

// A link between two tickets the caller has read through the predicate.
func (q *Queries) GetLink(ctx context.Context, arg GetLinkParams) (GetLinkRow, error) {
	row := q.db.QueryRow(ctx, getLink,
		arg.TenantID,
		arg.Type,
		arg.SourceID,
		arg.TargetID,
	)
	var i GetLinkRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedByUsername,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const getUrgencyInputs = `-- name: GetUrgencyInputs :one
SELECT t.state, t.block_kind, (t.urgency_override IS NOT NULL)::boolean AS overridden,
       EXISTS (SELECT 1
               FROM ticket_links l
               JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.source_id
               WHERE l.tenant_id = t.tenant_id AND l.target_id = t.id AND l.type = 'blocks'
                 AND s.type = 'decision' AND s.state NOT IN ('done', 'dropped')) AS open_decision_blocker
FROM tickets t
WHERE t.tenant_id = $1 AND t.id = $2
`

type GetUrgencyInputsParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetUrgencyInputsRow struct {
	State               domain.TicketState
	BlockKind           *domain.BlockKind
	Overridden          bool
	OpenDecisionBlocker bool
}

// The facts rule set v1 reads (docs/adr/0010 D3). The derivation belongs to
// the ticket, not to a reader: an open decision that blocks it counts whether
// or not the caller can see it, and only the derived value leaves.
// visibility: exempt (the derivation's inputs of a ticket the caller writes)
func (q *Queries) GetUrgencyInputs(ctx context.Context, arg GetUrgencyInputsParams) (GetUrgencyInputsRow, error) {
	row := q.db.QueryRow(ctx, getUrgencyInputs, arg.TenantID, arg.ID)
	var i GetUrgencyInputsRow
	err := row.Scan(
		&i.State,
		&i.BlockKind,
		&i.Overridden,
		&i.OpenDecisionBlocker,
	)
	return i, err
}

const listBlockedTickets = `-- name: ListBlockedTickets :many
SELECT t.id, p.key AS project_key, t.number
FROM ticket_links l
JOIN tickets t ON t.tenant_id = l.tenant_id AND t.id = l.target_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE l.tenant_id = $1 AND l.source_id = $2 AND l.type = 'blocks'
ORDER BY t.id
`

type ListBlockedTicketsParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

type ListBlockedTicketsRow struct {
	ID         uuid.UUID
	ProjectKey string
	Number     int32
}

// The tickets a ticket blocks, whose urgency derivation reads it
// (docs/adr/0010 D3). Their keys reach only their own timelines.
// visibility: exempt (the dependents of a derivation input)
func (q *Queries) ListBlockedTickets(ctx context.Context, arg ListBlockedTicketsParams) ([]ListBlockedTicketsRow, error) {
	rows, err := q.db.Query(ctx, listBlockedTickets, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedTicketsRow{}
	for rows.Next() {
		var i ListBlockedTicketsRow
		if err := rows.Scan(&i.ID, &i.ProjectKey, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPrerequisites = `-- name: ListOpenPrerequisites :many
SELECT s.id, sp.key AS project_key, s.number, s.title, s.state
FROM ticket_links l
JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.source_id
JOIN projects sp ON sp.tenant_id = s.tenant_id AND sp.id = s.project_id
WHERE l.tenant_id = $1 AND l.target_id = $2 AND l.type = 'blocks'
  AND s.state NOT IN ('done', 'dropped')
  AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
ORDER BY sp.key, s.number
`

type ListOpenPrerequisitesParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

type ListOpenPrerequisitesRow struct {
	ID         uuid.UUID
	ProjectKey string
	Number     int32
	Title      string
	State      domain.TicketState
}

// The open direct blocks sources of a ticket the caller can see: what refuses
// done (docs/adr/0012 D7). One the caller cannot see neither shows nor
// refuses.
func (q *Queries) ListOpenPrerequisites(ctx context.Context, arg ListOpenPrerequisitesParams) ([]ListOpenPrerequisitesRow, error) {
	rows, err := q.db.Query(ctx, listOpenPrerequisites, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPrerequisitesRow{}
	for rows.Next() {
		var i ListOpenPrerequisitesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinks = `-- name: ListTicketLinks :many
SELECT l.id, l.type, (l.source_id = $1::uuid)::boolean AS outgoing,
       o.id AS other_id, op.key AS other_project_key, o.number AS other_number, o.title AS other_title,
       o.state AS other_state, l.created_by, u.username AS created_by_username,
       u.display_name AS created_by_name, l.created_at
FROM ticket_links l
JOIN tickets o ON o.tenant_id = l.tenant_id
     AND o.id = CASE WHEN l.source_id = $1::uuid THEN l.target_id ELSE l.source_id END
JOIN projects op ON op.tenant_id = o.tenant_id AND op.id = o.project_id
LEFT JOIN users u ON u.id = l.created_by
WHERE l.tenant_id = $2
  AND (l.source_id = $1::uuid OR l.target_id = $1::uuid)
  AND app_ticket_visible(o.project_id, o.confidential, o.assignee_id, o.reporter_id)
  AND ($3::uuid IS NULL OR l.id > $3::uuid)
ORDER BY l.id
LIMIT $4
`

type ListTicketLinksParams struct {
	TicketID uuid.UUID
	TenantID uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListTicketLinksRow struct {
	ID                uuid.UUID
	Type              domain.LinkType
	Outgoing          bool
	OtherID           uuid.UUID
	OtherProjectKey   string
	OtherNumber       int32
	OtherTitle        string
	OtherState        domain.TicketState
	CreatedBy         uuid.UUID
	CreatedByUsername *string
	CreatedByName     *string
	CreatedAt         time.Time
}

// A ticket's links in both directions, read from the ticket's side; a link
// whose other end the caller cannot see is absent (docs/adr/0065 D4).
func (q *Queries) ListTicketLinks(ctx context.Context, arg ListTicketLinksParams) ([]ListTicketLinksRow, error) {
	rows, err := q.db.Query(ctx, listTicketLinks,
		arg.TicketID,
		arg.TenantID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketLinksRow{}
	for rows.Next() {
		var i ListTicketLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Outgoing,
			&i.OtherID,
			&i.OtherProjectKey,
			&i.OtherNumber,
			&i.OtherTitle,
			&i.OtherState,
			&i.CreatedBy,
			&i.CreatedByUsername,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
