// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const blocksPathExists = `-- name: BlocksPathExists :one
SELECT blocks_path_exists($1, $2, $3)::boolean AS reachable
`

type BlocksPathExistsParams struct {
	TenantID uuid.UUID
	FromID   uuid.UUID
	ToID     uuid.UUID
}

// Whether to_id is reachable from from_id over blocks links (docs/adr/0012 D4).
// visibility: exempt (an integrity walk returns no ticket)
func (q *Queries) BlocksPathExists(ctx context.Context, arg BlocksPathExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, blocksPathExists, arg.TenantID, arg.FromID, arg.ToID)
	var reachable bool
	err := row.Scan(&reachable)
	return reachable, err
}

const getLink = `-- name: GetLink :one
SELECT l.id, l.created_by, u.username AS created_by_username, u.display_name AS created_by_name, l.created_at
FROM ticket_links l
LEFT JOIN users u ON u.id = l.created_by
WHERE l.tenant_id = $1 AND l.type = $2
  AND l.source_id = $3 AND l.target_id = $4
`

type GetLinkParams struct {
	TenantID uuid.UUID
	Type     domain.LinkType
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type GetLinkRow struct {
	ID                uuid.UUID
	CreatedBy         uuid.UUID
	CreatedByUsername *string
	CreatedByName     *string
	CreatedAt         time.Time
}

// A link between two tickets the caller has read through the predicate.
func (q *Queries) GetLink(ctx context.Context, arg GetLinkParams) (GetLinkRow, error) {
	row := q.db.QueryRow(ctx, getLink,
		arg.TenantID,
		arg.Type,
		arg.SourceID,
		arg.TargetID,
	)
	var i GetLinkRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedByUsername,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const listDependents = `-- name: ListDependents :many
WITH RECURSIVE reach (id, via, depth) AS (
    SELECT l.target_id, l.source_id, 1
    FROM ticket_links l
    JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.target_id
    WHERE l.tenant_id = $3 AND l.source_id = $4::uuid AND l.type = 'blocks'
      AND s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
    UNION
    SELECT l.target_id, l.source_id, reach.depth + 1
    FROM reach
    JOIN ticket_links l ON l.tenant_id = $3 AND l.source_id = reach.id AND l.type = 'blocks'
    JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.target_id
    WHERE reach.depth < $5::integer AND s.id <> $4::uuid
      AND s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
), first AS (
    SELECT DISTINCT ON (reach.id) reach.id, reach.via, reach.depth FROM reach ORDER BY reach.id, reach.depth, reach.via
), tree (id, depth, path) AS (
    SELECT first.id, first.depth, ARRAY[first.id] FROM first WHERE first.depth = 1
    UNION ALL
    SELECT first.id, first.depth, tree.path || first.id FROM tree JOIN first ON first.via = tree.id
), nodes AS (
    SELECT tree.id, tree.depth, tree.path, false AS repeated FROM tree
    UNION
    SELECT reach.id, tree.depth + 1, tree.path || reach.id, true
    FROM reach
    JOIN first ON first.id = reach.id AND first.via <> reach.via
    JOIN tree ON tree.id = reach.via
), shown AS (
    SELECT nodes.depth, nodes.path, nodes.repeated, sp.key AS project_key, s.number, s.title, s.state, s.blocked_from,
           s.assignee_id, au.username AS assignee_username, au.display_name AS assignee_name,
           s.progress, s.progress_derived, s.progress_refinement, s.progress_refinement_derived,
           s.progress_review, s.progress_review_derived,
           count(*) FILTER (WHERE NOT nodes.repeated AND s.state NOT IN ('done', 'dropped')) OVER () AS open_count
    FROM nodes
    JOIN tickets s ON s.tenant_id = $3 AND s.id = nodes.id
    JOIN projects sp ON sp.tenant_id = s.tenant_id AND sp.id = s.project_id
    LEFT JOIN users au ON au.id = s.assignee_id
    WHERE s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
)
SELECT shown.depth::integer AS depth, shown.path::uuid[] AS path, shown.repeated::boolean AS repeated,
       shown.project_key, shown.number, shown.title, shown.state, shown.blocked_from,
       shown.assignee_id, shown.assignee_username, shown.assignee_name,
       shown.progress, shown.progress_derived, shown.progress_refinement, shown.progress_refinement_derived,
       shown.progress_review, shown.progress_review_derived, shown.open_count::integer AS open_count
FROM shown
WHERE $1::uuid[] IS NULL OR shown.path > $1::uuid[]
ORDER BY shown.path
LIMIT $2
`

type ListDependentsParams struct {
	After    []uuid.UUID
	PageSize int32
	TenantID uuid.UUID
	TicketID uuid.UUID
	MaxDepth int32
}

type ListDependentsRow struct {
	Depth                     int32
	Path                      []uuid.UUID
	Repeated                  bool
	ProjectKey                string
	Number                    int32
	Title                     string
	State                     domain.TicketState
	BlockedFrom               *domain.TicketState
	AssigneeID                *uuid.UUID
	AssigneeUsername          *string
	AssigneeName              *string
	Progress                  int16
	ProgressDerived           *int16
	ProgressRefinement        int16
	ProgressRefinementDerived *int16
	ProgressReview            int16
	ProgressReviewDerived     *int16
	OpenCount                 int32
}

// The prerequisite tree read upward (docs/adr/0012 D6): the tickets the
// ticket blocks, what those block, and so on — ListPrerequisites with the two
// ends of every link swapped, under the same rules.
func (q *Queries) ListDependents(ctx context.Context, arg ListDependentsParams) ([]ListDependentsRow, error) {
	rows, err := q.db.Query(ctx, listDependents,
		arg.After,
		arg.PageSize,
		arg.TenantID,
		arg.TicketID,
		arg.MaxDepth,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependentsRow{}
	for rows.Next() {
		var i ListDependentsRow
		if err := rows.Scan(
			&i.Depth,
			&i.Path,
			&i.Repeated,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.State,
			&i.BlockedFrom,
			&i.AssigneeID,
			&i.AssigneeUsername,
			&i.AssigneeName,
			&i.Progress,
			&i.ProgressDerived,
			&i.ProgressRefinement,
			&i.ProgressRefinementDerived,
			&i.ProgressReview,
			&i.ProgressReviewDerived,
			&i.OpenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPrerequisites = `-- name: ListOpenPrerequisites :many
SELECT s.id, sp.key AS project_key, s.number, s.title, s.state
FROM ticket_links l
JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.source_id
JOIN projects sp ON sp.tenant_id = s.tenant_id AND sp.id = s.project_id
WHERE l.tenant_id = $1 AND l.target_id = $2 AND l.type = 'blocks'
  AND s.state NOT IN ('done', 'dropped')
  AND s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
ORDER BY sp.key, s.number
`

type ListOpenPrerequisitesParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

type ListOpenPrerequisitesRow struct {
	ID         uuid.UUID
	ProjectKey string
	Number     int32
	Title      string
	State      domain.TicketState
}

// The open direct blocks sources of a ticket the caller can see: what refuses
// done (docs/adr/0012 D7). One the caller cannot see neither shows nor
// refuses.
func (q *Queries) ListOpenPrerequisites(ctx context.Context, arg ListOpenPrerequisitesParams) ([]ListOpenPrerequisitesRow, error) {
	rows, err := q.db.Query(ctx, listOpenPrerequisites, arg.TenantID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPrerequisitesRow{}
	for rows.Next() {
		var i ListOpenPrerequisitesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrerequisites = `-- name: ListPrerequisites :many
WITH RECURSIVE reach (id, via, depth) AS (
    SELECT l.source_id, l.target_id, 1
    FROM ticket_links l
    JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.source_id
    WHERE l.tenant_id = $3 AND l.target_id = $4::uuid AND l.type = 'blocks'
      AND s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
    UNION
    SELECT l.source_id, l.target_id, reach.depth + 1
    FROM reach
    JOIN ticket_links l ON l.tenant_id = $3 AND l.target_id = reach.id AND l.type = 'blocks'
    JOIN tickets s ON s.tenant_id = l.tenant_id AND s.id = l.source_id
    WHERE reach.depth < $5::integer AND s.id <> $4::uuid
      AND s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
), first AS (
    SELECT DISTINCT ON (reach.id) reach.id, reach.via, reach.depth FROM reach ORDER BY reach.id, reach.depth, reach.via
), tree (id, depth, path) AS (
    SELECT first.id, first.depth, ARRAY[first.id] FROM first WHERE first.depth = 1
    UNION ALL
    SELECT first.id, first.depth, tree.path || first.id FROM tree JOIN first ON first.via = tree.id
), nodes AS (
    SELECT tree.id, tree.depth, tree.path, false AS repeated FROM tree
    UNION
    SELECT reach.id, tree.depth + 1, tree.path || reach.id, true
    FROM reach
    JOIN first ON first.id = reach.id AND first.via <> reach.via
    JOIN tree ON tree.id = reach.via
), shown AS (
    SELECT nodes.depth, nodes.path, nodes.repeated, sp.key AS project_key, s.number, s.title, s.state, s.blocked_from,
           s.assignee_id, au.username AS assignee_username, au.display_name AS assignee_name,
           s.progress, s.progress_derived, s.progress_refinement, s.progress_refinement_derived,
           s.progress_review, s.progress_review_derived,
           count(*) FILTER (WHERE NOT nodes.repeated AND s.state NOT IN ('done', 'dropped')) OVER () AS open_count
    FROM nodes
    JOIN tickets s ON s.tenant_id = $3 AND s.id = nodes.id
    JOIN projects sp ON sp.tenant_id = s.tenant_id AND sp.id = s.project_id
    LEFT JOIN users au ON au.id = s.assignee_id
    WHERE s.deleted_at IS NULL AND app_ticket_visible(s.project_id, s.confidential, s.assignee_id, s.reporter_id)
)
SELECT shown.depth::integer AS depth, shown.path::uuid[] AS path, shown.repeated::boolean AS repeated,
       shown.project_key, shown.number, shown.title, shown.state, shown.blocked_from,
       shown.assignee_id, shown.assignee_username, shown.assignee_name,
       shown.progress, shown.progress_derived, shown.progress_refinement, shown.progress_refinement_derived,
       shown.progress_review, shown.progress_review_derived, shown.open_count::integer AS open_count
FROM shown
WHERE $1::uuid[] IS NULL OR shown.path > $1::uuid[]
ORDER BY shown.path
LIMIT $2
`

type ListPrerequisitesParams struct {
	After    []uuid.UUID
	PageSize int32
	TenantID uuid.UUID
	TicketID uuid.UUID
	MaxDepth int32
}

type ListPrerequisitesRow struct {
	Depth                     int32
	Path                      []uuid.UUID
	Repeated                  bool
	ProjectKey                string
	Number                    int32
	Title                     string
	State                     domain.TicketState
	BlockedFrom               *domain.TicketState
	AssigneeID                *uuid.UUID
	AssigneeUsername          *string
	AssigneeName              *string
	Progress                  int16
	ProgressDerived           *int16
	ProgressRefinement        int16
	ProgressRefinementDerived *int16
	ProgressReview            int16
	ProgressReviewDerived     *int16
	OpenCount                 int32
}

// The prerequisite tree of a ticket (docs/adr/0012 D6): the tickets that
// block it, what blocks those, and so on to max_depth, depth first, siblings
// by id — in the order they were filed. The walk keeps each link once per
// depth (UNION), never each path, so a dense graph costs its links times the
// depth and not the number of its paths. It never passes a ticket the caller
// cannot see: that ticket and what lies only behind it are absent
// (docs/adr/0065 D5). A ticket reached under several others stands in full
// under the first of them nearest the root (first) and under each other one as
// a repeated leaf. open_count counts the open tickets of the whole tree, each
// once, before the page is cut.
func (q *Queries) ListPrerequisites(ctx context.Context, arg ListPrerequisitesParams) ([]ListPrerequisitesRow, error) {
	rows, err := q.db.Query(ctx, listPrerequisites,
		arg.After,
		arg.PageSize,
		arg.TenantID,
		arg.TicketID,
		arg.MaxDepth,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrerequisitesRow{}
	for rows.Next() {
		var i ListPrerequisitesRow
		if err := rows.Scan(
			&i.Depth,
			&i.Path,
			&i.Repeated,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.State,
			&i.BlockedFrom,
			&i.AssigneeID,
			&i.AssigneeUsername,
			&i.AssigneeName,
			&i.Progress,
			&i.ProgressDerived,
			&i.ProgressRefinement,
			&i.ProgressRefinementDerived,
			&i.ProgressReview,
			&i.ProgressReviewDerived,
			&i.OpenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinks = `-- name: ListTicketLinks :many
SELECT l.id, l.type, (l.source_id = $1::uuid)::boolean AS outgoing,
       o.id AS other_id, op.key AS other_project_key, o.number AS other_number, o.title AS other_title,
       o.state AS other_state, l.created_by, u.username AS created_by_username,
       u.display_name AS created_by_name, l.created_at
FROM ticket_links l
JOIN tickets o ON o.tenant_id = l.tenant_id
     AND o.id = CASE WHEN l.source_id = $1::uuid THEN l.target_id ELSE l.source_id END
JOIN projects op ON op.tenant_id = o.tenant_id AND op.id = o.project_id
LEFT JOIN users u ON u.id = l.created_by
WHERE l.tenant_id = $2
  AND (l.source_id = $1::uuid OR l.target_id = $1::uuid)
  AND o.deleted_at IS NULL AND app_ticket_visible(o.project_id, o.confidential, o.assignee_id, o.reporter_id)
  AND ($3::uuid IS NULL OR l.id > $3::uuid)
ORDER BY l.id
LIMIT $4
`

type ListTicketLinksParams struct {
	TicketID uuid.UUID
	TenantID uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListTicketLinksRow struct {
	ID                uuid.UUID
	Type              domain.LinkType
	Outgoing          bool
	OtherID           uuid.UUID
	OtherProjectKey   string
	OtherNumber       int32
	OtherTitle        string
	OtherState        domain.TicketState
	CreatedBy         uuid.UUID
	CreatedByUsername *string
	CreatedByName     *string
	CreatedAt         time.Time
}

// A ticket's links in both directions, read from the ticket's side; a link
// whose other end the caller cannot see is absent (docs/adr/0065 D4).
func (q *Queries) ListTicketLinks(ctx context.Context, arg ListTicketLinksParams) ([]ListTicketLinksRow, error) {
	rows, err := q.db.Query(ctx, listTicketLinks,
		arg.TicketID,
		arg.TenantID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketLinksRow{}
	for rows.Next() {
		var i ListTicketLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Outgoing,
			&i.OtherID,
			&i.OtherProjectKey,
			&i.OtherNumber,
			&i.OtherTitle,
			&i.OtherState,
			&i.CreatedBy,
			&i.CreatedByUsername,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
