// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAddressAttempts = `-- name: CountAddressAttempts :one
SELECT count(*)
FROM login_attempts
WHERE address = $1 AND created_at > $2
`

type CountAddressAttemptsParams struct {
	Address []byte
	Since   time.Time
}

// The attempts of an address since a time, whatever their outcome
// (docs/adr/0033 D6).
func (q *Queries) CountAddressAttempts(ctx context.Context, arg CountAddressAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressAttempts, arg.Address, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoginFailures = `-- name: CountLoginFailures :one
SELECT count(*)
FROM login_attempts
WHERE username = $1 AND failed AND created_at > $2
`

type CountLoginFailuresParams struct {
	Username string
	Since    time.Time
}

// The failed attempts of a username since a time; attempts refused because of
// a lock count as failed.
func (q *Queries) CountLoginFailures(ctx context.Context, arg CountLoginFailuresParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginFailures, arg.Username, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLoginAccount = `-- name: GetLoginAccount :one

SELECT u.id, u.username, u.deactivated_at, u.global_admin, a.password_hash, a.password_change_required
FROM users u
JOIN local_accounts a ON a.user_id = u.id
WHERE u.username = $1
`

type GetLoginAccountRow struct {
	ID                     uuid.UUID
	Username               *string
	DeactivatedAt          *time.Time
	GlobalAdmin            bool
	PasswordHash           string
	PasswordChangeRequired bool
}

// The login's reads. Each runs in a transaction that names the login as its
// job (app.job = 'login'), which the policies of these tables admit
// (docs/adr/0021 D3, D6): the login looks an account up by the username it was
// given, before it knows a person.
// The local account a username names, with its password hash; no row when the
// username names no local account.
func (q *Queries) GetLoginAccount(ctx context.Context, username *string) (GetLoginAccountRow, error) {
	row := q.db.QueryRow(ctx, getLoginAccount, username)
	var i GetLoginAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DeactivatedAt,
		&i.GlobalAdmin,
		&i.PasswordHash,
		&i.PasswordChangeRequired,
	)
	return i, err
}

const getLoginLock = `-- name: GetLoginLock :one
SELECT locked_at, sticky, noted_at
FROM login_locks
WHERE username = $1
`

type GetLoginLockRow struct {
	LockedAt time.Time
	Sticky   bool
	NotedAt  *time.Time
}

func (q *Queries) GetLoginLock(ctx context.Context, username string) (GetLoginLockRow, error) {
	row := q.db.QueryRow(ctx, getLoginLock, username)
	var i GetLoginLockRow
	err := row.Scan(&i.LockedAt, &i.Sticky, &i.NotedAt)
	return i, err
}

const localLoginAvailable = `-- name: LocalLoginAvailable :one
SELECT EXISTS (
    SELECT 1
    FROM local_accounts a
    JOIN users u ON u.id = a.user_id
    WHERE u.deactivated_at IS NULL
) AS available
`

// docs/adr/0033 D8: the login page offers the local form when at least one
// active local account exists.
func (q *Queries) LocalLoginAvailable(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, localLoginAvailable)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const tenantsExist = `-- name: TenantsExist :one
SELECT EXISTS (SELECT 1 FROM tenants) AS exist
`

// docs/adr/0032 D5: the installation is initialised once a tenant exists.
func (q *Queries) TenantsExist(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tenantsExist)
	var exist bool
	err := row.Scan(&exist)
	return exist, err
}
