// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const findPersonByUsername = `-- name: FindPersonByUsername :one
SELECT id
FROM users
WHERE username = $1 AND deactivated_at IS NULL
`

// The active local account of a username (docs/adr/0033 D2), looked up the same
// way.
func (q *Queries) FindPersonByUsername(ctx context.Context, username *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findPersonByUsername, username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findPersonsByEmail = `-- name: FindPersonsByEmail :many

SELECT id
FROM users
WHERE lower(email) = lower($1) AND deactivated_at IS NULL
  AND (email_verified OR ($2::boolean AND email_verified IS NULL))
  AND oidc_issuer = $3::text
ORDER BY id
LIMIT 2
`

type FindPersonsByEmailParams struct {
	Email        string
	EmailTrusted bool
	Issuer       string
}

// The reads of the administration of members, mappings and project access
// (docs/adr/0030 D2, D3, docs/adr/0034 D3, D7), inside the tenant's
// transaction.
// The active persons of the configured issuer whose address — as the issuer
// asserted it at their last login — is the given one, compared without regard
// to case. An address is someone's only when the issuer marked it verified, or,
// with COWORK_OIDC_EMAIL_TRUSTED (email_trusted), when it said nothing about
// it; one it marked unverified is no one's (docs/adr/0030 D3). A person of
// another issuer cannot log in (the security review of 2026-10-04, m6). The
// transaction names the address in app.person_lookup, which the users policy
// admits those rows for; two rows say the address is not one person's.
func (q *Queries) FindPersonsByEmail(ctx context.Context, arg FindPersonsByEmailParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findPersonsByEmail, arg.Email, arg.EmailTrusted, arg.Issuer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrant = `-- name: GetGrant :one
SELECT id, role
FROM memberships
WHERE tenant_id = $1 AND user_id = $2 AND source = 'grant'
`

type GetGrantParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetGrantRow struct {
	ID   uuid.UUID
	Role domain.Role
}

// The person's marked grant in the tenant (docs/adr/0030 D3).
func (q *Queries) GetGrant(ctx context.Context, arg GetGrantParams) (GetGrantRow, error) {
	row := q.db.QueryRow(ctx, getGrant, arg.TenantID, arg.UserID)
	var i GetGrantRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const getGroupMapping = `-- name: GetGroupMapping :one
SELECT id, group_name, role, version, created_at, updated_at
FROM group_mappings
WHERE tenant_id = $1 AND id = $2
`

type GetGroupMappingParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetGroupMappingRow struct {
	ID        uuid.UUID
	GroupName string
	Role      domain.Role
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetGroupMapping(ctx context.Context, arg GetGroupMappingParams) (GetGroupMappingRow, error) {
	row := q.db.QueryRow(ctx, getGroupMapping, arg.TenantID, arg.ID)
	var i GetGroupMappingRow
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectAccessEntry = `-- name: GetProjectAccessEntry :one
SELECT role, created_at
FROM project_access
WHERE tenant_id = $1 AND project_id = $2 AND user_id = $3
`

type GetProjectAccessEntryParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

type GetProjectAccessEntryRow struct {
	Role      domain.Role
	CreatedAt time.Time
}

func (q *Queries) GetProjectAccessEntry(ctx context.Context, arg GetProjectAccessEntryParams) (GetProjectAccessEntryRow, error) {
	row := q.db.QueryRow(ctx, getProjectAccessEntry, arg.TenantID, arg.ProjectID, arg.UserID)
	var i GetProjectAccessEntryRow
	err := row.Scan(&i.Role, &i.CreatedAt)
	return i, err
}

const groupMappingExists = `-- name: GroupMappingExists :one
SELECT EXISTS (
    SELECT 1 FROM group_mappings WHERE tenant_id = $1 AND group_name = $2
) AS taken
`

type GroupMappingExistsParams struct {
	TenantID  uuid.UUID
	GroupName string
}

func (q *Queries) GroupMappingExists(ctx context.Context, arg GroupMappingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupMappingExists, arg.TenantID, arg.GroupName)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (
    SELECT 1 FROM memberships WHERE tenant_id = $1 AND user_id = $2
) AS member
`

type IsMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.TenantID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const listGroupMappings = `-- name: ListGroupMappings :many
SELECT id, group_name, role, version, created_at, updated_at
FROM group_mappings
WHERE tenant_id = $1
  AND ($2::text IS NULL OR group_name > $2::text)
ORDER BY group_name
LIMIT $3
`

type ListGroupMappingsParams struct {
	TenantID uuid.UUID
	After    *string
	PageSize int32
}

type ListGroupMappingsRow struct {
	ID        uuid.UUID
	GroupName string
	Role      domain.Role
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The tenant's group mappings by group, a page after the cursor's group.
func (q *Queries) ListGroupMappings(ctx context.Context, arg ListGroupMappingsParams) ([]ListGroupMappingsRow, error) {
	rows, err := q.db.Query(ctx, listGroupMappings, arg.TenantID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMappingsRow{}
	for rows.Next() {
		var i ListGroupMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Role,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectAccess = `-- name: ListProjectAccess :many
SELECT a.user_id, u.username, u.display_name, u.email, a.role, a.created_at
FROM project_access a
JOIN users u ON u.id = a.user_id
WHERE a.tenant_id = $1 AND a.project_id = $2
  AND ($3::uuid IS NULL OR a.user_id > $3::uuid)
ORDER BY a.user_id
LIMIT $4
`

type ListProjectAccessParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	After     *uuid.UUID
	PageSize  int32
}

type ListProjectAccessRow struct {
	UserID      uuid.UUID
	Username    *string
	DisplayName string
	Email       *string
	Role        domain.Role
	CreatedAt   time.Time
}

// A project's access list by person id (docs/adr/0034 D3), a page after the
// cursor's person: the entries of the tenant's members, whom the users policy
// admits to the join.
func (q *Queries) ListProjectAccess(ctx context.Context, arg ListProjectAccessParams) ([]ListProjectAccessRow, error) {
	rows, err := q.db.Query(ctx, listProjectAccess,
		arg.TenantID,
		arg.ProjectID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectAccessRow{}
	for rows.Next() {
		var i ListProjectAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantHasAdmin = `-- name: TenantHasAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE m.tenant_id = $1 AND m.role = 'admin' AND u.deactivated_at IS NULL
      AND (u.oidc_issuer IS NULL OR (u.oidc_issuer = $2::text AND u.gate_checked_at IS NOT NULL))
) AS has_admin
`

type TenantHasAdminParams struct {
	TenantID uuid.UUID
	Issuer   string
}

// Whether a person who can log in holds the admin role in the tenant, mapped
// or granted: what a change of a grant or a mapping must leave
// (docs/adr/0034 D1). A deactivated person cannot, nor can a person of the
// identity provider who is not of the configured issuer, or whom the gate
// refused at their last login or refresh (gate_checked_at is cleared then).
func (q *Queries) TenantHasAdmin(ctx context.Context, arg TenantHasAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantHasAdmin, arg.TenantID, arg.Issuer)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}
