// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const canSeeTicket = `-- name: CanSeeTicket :one
SELECT EXISTS (
    SELECT 1
    FROM tickets t
    JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
    JOIN memberships m ON m.tenant_id = t.tenant_id AND m.user_id = $1
    WHERE t.tenant_id = $2 AND t.id = $3
      AND (NOT p.restricted OR m.role = 'admin'
           OR EXISTS (SELECT 1 FROM project_access a
                      WHERE a.tenant_id = t.tenant_id AND a.project_id = p.id AND a.user_id = m.user_id))
      AND (NOT t.confidential OR m.role = 'admin' OR t.assignee_id = m.user_id OR t.reporter_id = m.user_id)
) AS visible
`

type CanSeeTicketParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	TicketID uuid.UUID
}

// Whether a person can see a ticket: its project (docs/adr/0034 D3) and,
// while it is confidential, as administrator, assignee or reporter
// (docs/adr/0065 D4). A question is asked only of such a person.
// visibility: exempt (whether another person sees a ticket the caller reads)
func (q *Queries) CanSeeTicket(ctx context.Context, arg CanSeeTicketParams) (bool, error) {
	row := q.db.QueryRow(ctx, canSeeTicket, arg.UserID, arg.TenantID, arg.TicketID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT q.id, q.number, q.question, q.options, q.recommendation, q.answer, q.status,
       q.asked_by, ab.username AS asked_by_username, ab.display_name AS asked_by_name, q.asked_by_agent,
       q.asked_by_token_id, q.asked_by_token_name,
       q.asked_of, ao.username AS asked_of_username, ao.display_name AS asked_of_name,
       q.answered_by, an.username AS answered_by_username, an.display_name AS answered_by_name,
       q.answered_at, q.recorded_by_agent, q.answered_by_token_id, q.answered_by_token_name,
       q.withdrawn_at, q.version, q.created_at, q.updated_at
FROM questions q
JOIN tickets t ON t.tenant_id = q.tenant_id AND t.id = q.ticket_id
LEFT JOIN users ab ON ab.id = q.asked_by
LEFT JOIN users ao ON ao.id = q.asked_of
LEFT JOIN users an ON an.id = q.answered_by
WHERE q.tenant_id = $1 AND q.ticket_id = $2 AND q.number = $3
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
`

type GetQuestionParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	Number   int32
}

type GetQuestionRow struct {
	ID                  uuid.UUID
	Number              int32
	Question            string
	Options             string
	Recommendation      string
	Answer              *string
	Status              string
	AskedBy             uuid.UUID
	AskedByUsername     *string
	AskedByName         *string
	AskedByAgent        *string
	AskedByTokenID      *uuid.UUID
	AskedByTokenName    *string
	AskedOf             *uuid.UUID
	AskedOfUsername     *string
	AskedOfName         *string
	AnsweredBy          *uuid.UUID
	AnsweredByUsername  *string
	AnsweredByName      *string
	AnsweredAt          *time.Time
	RecordedByAgent     bool
	AnsweredByTokenID   *uuid.UUID
	AnsweredByTokenName *string
	WithdrawnAt         *time.Time
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (GetQuestionRow, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.TenantID, arg.TicketID, arg.Number)
	var i GetQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Question,
		&i.Options,
		&i.Recommendation,
		&i.Answer,
		&i.Status,
		&i.AskedBy,
		&i.AskedByUsername,
		&i.AskedByName,
		&i.AskedByAgent,
		&i.AskedByTokenID,
		&i.AskedByTokenName,
		&i.AskedOf,
		&i.AskedOfUsername,
		&i.AskedOfName,
		&i.AnsweredBy,
		&i.AnsweredByUsername,
		&i.AnsweredByName,
		&i.AnsweredAt,
		&i.RecordedByAgent,
		&i.AnsweredByTokenID,
		&i.AnsweredByTokenName,
		&i.WithdrawnAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestions = `-- name: ListQuestions :many

SELECT q.id, q.number, q.question, q.options, q.recommendation, q.answer, q.status,
       q.asked_by, ab.username AS asked_by_username, ab.display_name AS asked_by_name, q.asked_by_agent,
       q.asked_by_token_id, q.asked_by_token_name,
       q.asked_of, ao.username AS asked_of_username, ao.display_name AS asked_of_name,
       q.answered_by, an.username AS answered_by_username, an.display_name AS answered_by_name,
       q.answered_at, q.recorded_by_agent, q.answered_by_token_id, q.answered_by_token_name,
       q.withdrawn_at, q.version, q.created_at, q.updated_at
FROM questions q
JOIN tickets t ON t.tenant_id = q.tenant_id AND t.id = q.ticket_id
LEFT JOIN users ab ON ab.id = q.asked_by
LEFT JOIN users ao ON ao.id = q.asked_of
LEFT JOIN users an ON an.id = q.answered_by
WHERE q.tenant_id = $1 AND q.ticket_id = $2
  AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND ($3::integer IS NULL OR q.number > $3::integer)
ORDER BY q.number
LIMIT $4
`

type ListQuestionsParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	After    *int32
	PageSize int32
}

type ListQuestionsRow struct {
	ID                  uuid.UUID
	Number              int32
	Question            string
	Options             string
	Recommendation      string
	Answer              *string
	Status              string
	AskedBy             uuid.UUID
	AskedByUsername     *string
	AskedByName         *string
	AskedByAgent        *string
	AskedByTokenID      *uuid.UUID
	AskedByTokenName    *string
	AskedOf             *uuid.UUID
	AskedOfUsername     *string
	AskedOfName         *string
	AnsweredBy          *uuid.UUID
	AnsweredByUsername  *string
	AnsweredByName      *string
	AnsweredAt          *time.Time
	RecordedByAgent     bool
	AnsweredByTokenID   *uuid.UUID
	AnsweredByTokenName *string
	WithdrawnAt         *time.Time
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// A question is visible when its ticket is (docs/adr/0065 D4).
func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listQuestions,
		arg.TenantID,
		arg.TicketID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsRow{}
	for rows.Next() {
		var i ListQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Question,
			&i.Options,
			&i.Recommendation,
			&i.Answer,
			&i.Status,
			&i.AskedBy,
			&i.AskedByUsername,
			&i.AskedByName,
			&i.AskedByAgent,
			&i.AskedByTokenID,
			&i.AskedByTokenName,
			&i.AskedOf,
			&i.AskedOfUsername,
			&i.AskedOfName,
			&i.AnsweredBy,
			&i.AnsweredByUsername,
			&i.AnsweredByName,
			&i.AnsweredAt,
			&i.RecordedByAgent,
			&i.AnsweredByTokenID,
			&i.AnsweredByTokenName,
			&i.WithdrawnAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
