// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findRepositoryBindings = `-- name: FindRepositoryBindings :many
SELECT r.id, r.identity, r.path, r.remote, p.id AS project_id, p.key AS project_key, p.name AS project_name,
       p.archived_at
FROM project_repositories r
JOIN projects p ON p.tenant_id = r.tenant_id AND p.id = r.project_id
WHERE r.tenant_id = $1 AND r.identity = ANY ($2::text[]) AND app_project_visible(p.id)
ORDER BY r.identity, r.path, p.key
`

type FindRepositoryBindingsParams struct {
	TenantID   uuid.UUID
	Identities []string
}

type FindRepositoryBindingsRow struct {
	ID          uuid.UUID
	Identity    string
	Path        string
	Remote      string
	ProjectID   uuid.UUID
	ProjectKey  string
	ProjectName string
	ArchivedAt  *time.Time
}

// The tenant's bindings of any of the identities, for the lookup across the
// person's tenants (docs/adr/0066 D2).
func (q *Queries) FindRepositoryBindings(ctx context.Context, arg FindRepositoryBindingsParams) ([]FindRepositoryBindingsRow, error) {
	rows, err := q.db.Query(ctx, findRepositoryBindings, arg.TenantID, arg.Identities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRepositoryBindingsRow{}
	for rows.Next() {
		var i FindRepositoryBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.Path,
			&i.Remote,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepositoryBinding = `-- name: GetRepositoryBinding :one
SELECT r.id, r.project_id, r.identity, r.path, r.remote, r.created_at, r.updated_at
FROM project_repositories r
WHERE r.tenant_id = $1 AND r.identity = $2 AND r.path = $3
`

type GetRepositoryBindingParams struct {
	TenantID uuid.UUID
	Identity string
	Path     string
}

type GetRepositoryBindingRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Identity  string
	Path      string
	Remote    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Whether the tenant binds the repository at all, and to which project: the
// identity and path are unique in the tenant whether or not the caller sees
// the project that holds them. The project is named to the caller only when
// they see it.
// visibility: exempt (whether a binding exists, as ProjectKeyTaken for a key)
func (q *Queries) GetRepositoryBinding(ctx context.Context, arg GetRepositoryBindingParams) (GetRepositoryBindingRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryBinding, arg.TenantID, arg.Identity, arg.Path)
	var i GetRepositoryBindingRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identity,
		&i.Path,
		&i.Remote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleProjectByID = `-- name: GetVisibleProjectByID :one
SELECT id, key, name, description, restricted, wip_limits, archived_at, version, created_at, updated_at
FROM projects
WHERE tenant_id = $1 AND id = $2 AND app_project_visible(id)
`

type GetVisibleProjectByIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetVisibleProjectByIDRow struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	Restricted  bool
	WipLimits   []byte
	ArchivedAt  *time.Time
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetVisibleProjectByID(ctx context.Context, arg GetVisibleProjectByIDParams) (GetVisibleProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getVisibleProjectByID, arg.TenantID, arg.ID)
	var i GetVisibleProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Restricted,
		&i.WipLimits,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectRepositories = `-- name: ListProjectRepositories :many

SELECT r.id, r.identity, r.path, r.remote, r.created_at, r.updated_at
FROM project_repositories r
JOIN projects p ON p.tenant_id = r.tenant_id AND p.id = r.project_id
WHERE r.tenant_id = $1 AND r.project_id = $2 AND app_project_visible(p.id)
  AND ($3::uuid IS NULL OR r.id > $3::uuid)
ORDER BY r.id
LIMIT $4
`

type ListProjectRepositoriesParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	After     *uuid.UUID
	PageSize  int32
}

type ListProjectRepositoriesRow struct {
	ID        uuid.UUID
	Identity  string
	Path      string
	Remote    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// The repositories a project owns (docs/adr/0006 D3, docs/adr/0066). A
// binding is visible with its project: a restricted project's bindings are
// read by the people who see the project, and a token restricted to a project
// reads that project's only (docs/adr/0034 D3, docs/adr/0035 D3).
// A project's repositories in the order they were bound.
func (q *Queries) ListProjectRepositories(ctx context.Context, arg ListProjectRepositoriesParams) ([]ListProjectRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listProjectRepositories,
		arg.TenantID,
		arg.ProjectID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectRepositoriesRow{}
	for rows.Next() {
		var i ListProjectRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.Path,
			&i.Remote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repositoriesUnderOwner = `-- name: RepositoriesUnderOwner :one
SELECT EXISTS (
    SELECT 1
    FROM project_repositories r
    JOIN projects p ON p.tenant_id = r.tenant_id AND p.id = r.project_id
    WHERE r.tenant_id = $1 AND starts_with(r.identity, $2::text) AND app_project_visible(p.id)
) AS found
`

type RepositoriesUnderOwnerParams struct {
	TenantID uuid.UUID
	Prefix   string
}

// Whether the tenant binds a repository under the same remote owner, the
// proposal's guess at the tenant (docs/adr/0066 D2).
func (q *Queries) RepositoriesUnderOwner(ctx context.Context, arg RepositoriesUnderOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, repositoriesUnderOwner, arg.TenantID, arg.Prefix)
	var found bool
	err := row.Scan(&found)
	return found, err
}
