// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package readq

import (
	"context"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const searchTickets = `-- name: SearchTickets :many

WITH query AS (
    SELECT plainto_tsquery('cowork_simple', $2::text) AS tsq
),
matches AS (
    SELECT t.id AS ticket_id, 1 AS place, NULL::uuid AS source_id, NULL::integer AS question_number,
           ts_rank(t.search, query.tsq) AS rank, 'ticket'::text AS found_in
    FROM tickets t CROSS JOIN query
    WHERE t.tenant_id = $1 AND t.search @@ query.tsq
      AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
    UNION ALL
    SELECT t.id, 5, NULL, NULL, (word_similarity($2::text, t.title) * 0.05::real)::real, 'ticket'
    FROM tickets t
    WHERE t.tenant_id = $1 AND $2::text <% t.title
      AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
    UNION ALL
    SELECT t.id, 0, NULL, NULL,
           (CASE WHEN p.key || '-' || t.number::text = $3::text THEN 4 ELSE 2 END)::real, 'key'
    FROM tickets t
    JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
    WHERE t.tenant_id = $1 AND $3::text <> ''
      AND starts_with(p.key || '-' || t.number::text, $3::text)
      AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
    UNION ALL
    SELECT c.ticket_id, 3, c.id, NULL, ts_rank(c.search, query.tsq), 'comment'
    FROM comments c
    JOIN tickets t ON t.tenant_id = c.tenant_id AND t.id = c.ticket_id
    CROSS JOIN query
    WHERE c.tenant_id = $1 AND c.withdrawn_at IS NULL AND c.search @@ query.tsq
      AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
    UNION ALL
    SELECT q.ticket_id, 2, NULL, q.number, ts_rank('{0.1, 0.1, 0.1, 0.1}', q.search, query.tsq), 'question'
    FROM questions q
    JOIN tickets t ON t.tenant_id = q.tenant_id AND t.id = q.ticket_id
    CROSS JOIN query
    WHERE q.tenant_id = $1 AND q.search @@ query.tsq
      AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
    UNION ALL
    SELECT a.ticket_id, 4, a.id, NULL, ts_rank(a.search, query.tsq), 'attachment'
    FROM attachments a
    JOIN tickets t ON t.tenant_id = a.tenant_id AND t.id = a.ticket_id
    CROSS JOIN query
    WHERE a.tenant_id = $1 AND a.search @@ query.tsq
      AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
),
best AS (
    SELECT DISTINCT ON (m.ticket_id) m.ticket_id, m.found_in, m.source_id, m.question_number, m.rank
    FROM matches m
    ORDER BY m.ticket_id, m.rank DESC, m.place, m.source_id, m.question_number
),
hits AS (
    SELECT b.ticket_id, b.found_in, b.source_id, b.question_number, b.rank
    FROM best b
    WHERE $4::real IS NULL
       OR (b.rank, b.ticket_id) < ($4::real, $5::uuid)
    ORDER BY b.rank DESC, b.ticket_id DESC
    LIMIT $6
)
SELECT t.id, p.key AS project_key, t.number, t.title, t.type, t.state,
       h.found_in, h.source_id, h.question_number, h.rank,
       CASE WHEN h.found_in = 'attachment' THEN translate(coalesce(a.file_name, ''), chr(2) || chr(3), '')
            ELSE ts_headline('cowork_simple',
                translate(CASE h.found_in
                              WHEN 'comment' THEN coalesce(c.body, '')
                              WHEN 'question' THEN concat_ws(E'\n', qn.question, qn.options, qn.recommendation, qn.answer)
                              ELSE t.body
                          END, chr(2) || chr(3), ''),
                query.tsq,
                'StartSel=' || chr(2) || ', StopSel=' || chr(3)
                    || ', MaxWords=18, MinWords=6, MaxFragments=2, FragmentDelimiter=" … "')
       END::text AS snippet
FROM hits h
JOIN tickets t ON t.tenant_id = $1 AND t.id = h.ticket_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
LEFT JOIN comments c ON h.found_in = 'comment' AND c.tenant_id = t.tenant_id AND c.ticket_id = t.id
     AND c.id = h.source_id AND c.withdrawn_at IS NULL
LEFT JOIN questions qn ON h.found_in = 'question' AND qn.tenant_id = t.tenant_id AND qn.ticket_id = t.id
     AND qn.number = h.question_number
LEFT JOIN attachments a ON h.found_in = 'attachment' AND a.tenant_id = t.tenant_id AND a.ticket_id = t.id
     AND a.id = h.source_id
CROSS JOIN query
WHERE app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
ORDER BY h.rank DESC, h.ticket_id DESC
`

type SearchTicketsParams struct {
	TenantID  uuid.UUID
	Query     string
	KeyPrefix string
	AfterRank *float32
	AfterID   *uuid.UUID
	PageSize  int32
}

type SearchTicketsRow struct {
	ID             uuid.UUID
	ProjectKey     string
	Number         int32
	Title          string
	Type           domain.TicketType
	State          domain.TicketState
	FoundIn        string
	SourceID       *uuid.UUID
	QuestionNumber *int32
	Rank           float32
	Snippet        string
}

// Search within a tenant (docs/adr/0025 D3–D5). Every text is read through the
// predicate of the ticket it belongs to, so a hit — its snippet included —
// never shows what the caller cannot see (docs/adr/0034 D3, docs/adr/0065 D5).
// The tenant's tickets that match the query, one row per ticket at its best
// match, the best first, after the cursor's place: a key above everything,
// then the title above the body (weights A and B of the ticket's vector)
// above comments, questions and file names (weight 0.1 each), a title found
// by trigram below them (D3, D4). A withdrawn comment is not searched
// (docs/adr/0015 D3). The snippet is taken of the page's rows only, with the
// bytes 0x02 and 0x03 around the words found, which the text loses first; a
// file name, which the parser reads as one word, is its own snippet.
func (q *Queries) SearchTickets(ctx context.Context, arg SearchTicketsParams) ([]SearchTicketsRow, error) {
	rows, err := q.db.Query(ctx, searchTickets,
		arg.TenantID,
		arg.Query,
		arg.KeyPrefix,
		arg.AfterRank,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTicketsRow{}
	for rows.Next() {
		var i SearchTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Number,
			&i.Title,
			&i.Type,
			&i.State,
			&i.FoundIn,
			&i.SourceID,
			&i.QuestionNumber,
			&i.Rank,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
