// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const getMember = `-- name: GetMember :one
SELECT u.id, u.username, u.display_name, u.email, max(m.role)::tenant_role AS role,
       array_agg(m.source::text ORDER BY m.source)::text[] AS sources,
       array_agg(m.role::text ORDER BY m.source)::text[] AS roles,
       (u.username IS NOT NULL)::boolean AS local
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1 AND m.user_id = $2
GROUP BY u.id, u.username, u.display_name, u.email
`

type GetMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetMemberRow struct {
	ID          uuid.UUID
	Username    *string
	DisplayName string
	Email       *string
	Role        domain.Role
	Sources     []string
	Roles       []string
	Local       bool
}

// One member of the tenant, as the list shows them; no row when the person is
// not a member.
func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.TenantID, arg.UserID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.Sources,
		&i.Roles,
		&i.Local,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, version, time_visible_to_members, time_locked_until,
       members_create_projects, chat_external_allowed, chat_external_provider, created_at, updated_at
FROM tenants
WHERE id = $1
`

type GetTenantRow struct {
	ID                    uuid.UUID
	Slug                  string
	Name                  string
	Version               int32
	TimeVisibleToMembers  bool
	TimeLockedUntil       *time.Time
	MembersCreateProjects bool
	ChatExternalAllowed   bool
	ChatExternalProvider  *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) GetTenant(ctx context.Context, tenantID uuid.UUID) (GetTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenant, tenantID)
	var i GetTenantRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Version,
		&i.TimeVisibleToMembers,
		&i.TimeLockedUntil,
		&i.MembersCreateProjects,
		&i.ChatExternalAllowed,
		&i.ChatExternalProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name
FROM tenants
WHERE slug = $1
`

type GetTenantBySlugRow struct {
	ID   uuid.UUID
	Slug string
	Name string
}

// A tenant by slug, whoever is a member: the tenant boundary's read for a
// global administrator who holds no role in it (docs/adr/0034 D2). The tenants
// policy admits the row to a global administrator and to the tenant's members
// only (migration 26), so for anybody else it is no row.
func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (GetTenantBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i GetTenantBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getTenantForPerson = `-- name: GetTenantForPerson :one
SELECT t.id, t.slug, t.name, max(m.role)::tenant_role AS role
FROM tenants t
JOIN memberships m ON m.tenant_id = t.id
WHERE t.slug = $1 AND m.user_id = $2
GROUP BY t.id, t.slug, t.name
`

type GetTenantForPersonParams struct {
	Slug   string
	UserID uuid.UUID
}

type GetTenantForPersonRow struct {
	ID   uuid.UUID
	Slug string
	Name string
	Role domain.Role
}

// The tenant boundary (docs/adr/0023 D5): the tenant by slug with the
// person's highest role in it, or no row when the slug is unknown or the
// person has no membership — the caller answers both alike.
func (q *Queries) GetTenantForPerson(ctx context.Context, arg GetTenantForPersonParams) (GetTenantForPersonRow, error) {
	row := q.db.QueryRow(ctx, getTenantForPerson, arg.Slug, arg.UserID)
	var i GetTenantForPersonRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT u.id, u.username, u.display_name, u.deactivated_at, u.created_at, u.global_admin,
       (a.user_id IS NOT NULL)::boolean AS local,
       COALESCE(a.password_change_required, false)::boolean AS password_change_required,
       (u.oidc_issuer IS NOT NULL)::boolean AS provider, u.oidc_issuer, u.oidc_subject, u.oidc_groups,
       u.oidc_groups_at, u.gate_checked_at
FROM users u
LEFT JOIN local_accounts a ON a.user_id = u.id
WHERE u.id = $1
`

type GetUserRow struct {
	ID                     uuid.UUID
	Username               *string
	DisplayName            string
	DeactivatedAt          *time.Time
	CreatedAt              time.Time
	GlobalAdmin            bool
	Local                  bool
	PasswordChangeRequired bool
	Provider               bool
	OidcIssuer             *string
	OidcSubject            *string
	OidcGroups             []string
	OidcGroupsAt           *time.Time
	GateCheckedAt          *time.Time
}

// The person with what the resolvers and GET /api/v1/me need: whether they are
// a global administrator, whether they have a local account, and whether its
// password must be changed before anything else (docs/adr/0033 D4). The
// account row is the person's own to read, so another person's flags are not
// this query's to answer. A person of the identity provider comes with their
// groups as of the last login or refresh and when the token gate last checked
// them (docs/adr/0035 D8).
func (q *Queries) GetUser(ctx context.Context, userID uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.GlobalAdmin,
		&i.Local,
		&i.PasswordChangeRequired,
		&i.Provider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.OidcGroups,
		&i.OidcGroupsAt,
		&i.GateCheckedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.username, u.display_name, u.email, max(m.role)::tenant_role AS role,
       array_agg(m.source::text ORDER BY m.source)::text[] AS sources,
       array_agg(m.role::text ORDER BY m.source)::text[] AS roles,
       (u.username IS NOT NULL)::boolean AS local
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
  AND ($2::uuid IS NULL OR u.id > $2::uuid)
GROUP BY u.id, u.username, u.display_name, u.email
ORDER BY u.id
LIMIT $3
`

type ListMembersParams struct {
	TenantID uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListMembersRow struct {
	ID          uuid.UUID
	Username    *string
	DisplayName string
	Email       *string
	Role        domain.Role
	Sources     []string
	Roles       []string
	Local       bool
}

// The tenant's members by person id (docs/adr/0034 D7), a page after the
// cursor's person: the highest role, every source of it with its own role —
// the mapping before the grant — whether the person is a local account rather
// than one of the identity provider (docs/adr/0030 D4, docs/adr/0033), and
// the address, which the handler shows the tenant's administrators only.
func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.TenantID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.Sources,
			&i.Roles,
			&i.Local,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsOfUser = `-- name: ListMembershipsOfUser :many
SELECT t.id AS tenant_id, t.slug, t.name, max(m.role)::tenant_role AS role,
       array_agg(m.source::text ORDER BY m.source)::text[] AS sources,
       array_agg(m.role::text ORDER BY m.source)::text[] AS roles
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1
GROUP BY t.id, t.slug, t.name
ORDER BY t.slug
`

type ListMembershipsOfUserRow struct {
	TenantID uuid.UUID
	Slug     string
	Name     string
	Role     domain.Role
	Sources  []string
	Roles    []string
}

// The person's tenants with the highest role in each (GET /api/v1/me), and
// every source of it with its own role, the mapping before the grant
// (docs/adr/0030 D4).
func (q *Queries) ListMembershipsOfUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsOfUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsOfUserRow{}
	for rows.Next() {
		var i ListMembershipsOfUserRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Role,
			&i.Sources,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT t.slug, t.name, COALESCE(max(m.role)::text, '')::text AS role
FROM tenants t
LEFT JOIN memberships m ON m.tenant_id = t.id AND m.user_id = $1
WHERE $2::text IS NULL OR t.slug > $2::text
GROUP BY t.id, t.slug, t.name
ORDER BY t.slug
LIMIT $3
`

type ListTenantsParams struct {
	UserID   uuid.UUID
	After    *string
	PageSize int32
}

type ListTenantsRow struct {
	Slug string
	Name string
	Role string
}

// Every tenant of the installation by slug, a page after the cursor's slug,
// with the person's highest role in each — ” where they hold none: the
// tenant list of a global administrator (docs/adr/0034 D2), whom alone the
// tenants policy shows every row.
func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.UserID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
