// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const canSeeProject = `-- name: CanSeeProject :one
SELECT EXISTS (
    SELECT 1
    FROM memberships m
    JOIN projects p ON p.tenant_id = m.tenant_id AND p.id = $1
    WHERE m.tenant_id = $2 AND m.user_id = $3
      AND (NOT p.restricted OR m.role = 'admin'
           OR EXISTS (SELECT 1 FROM project_access a
                      WHERE a.tenant_id = m.tenant_id AND a.project_id = p.id AND a.user_id = m.user_id))
) AS visible
`

type CanSeeProjectParams struct {
	ProjectID uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
}

// Whether a person can see a project: a member of the tenant, and on a
// restricted project an administrator or on its list (docs/adr/0034 D3). An
// assignee must be one; assignment admits a person to a confidential ticket
// (docs/adr/0065 D9), never to a restricted project.
// visibility: exempt (whether another person sees a project the caller reads)
func (q *Queries) CanSeeProject(ctx context.Context, arg CanSeeProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, canSeeProject, arg.ProjectID, arg.TenantID, arg.UserID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const getTicketByNumber = `-- name: GetTicketByNumber :one

SELECT t.id, t.project_id, p.key AS project_key, t.number, t.type, t.title, t.body, t.state,
       t.blocked_from, t.block_kind, t.block_reason, t.block_ticket_id, t.block_external_ref,
       bp.key AS block_project_key, bt.number AS block_number,
       t.severity, t.security, t.threat, t.urgency_derived, t.urgency_rule, t.urgency_override,
       t.urgency_override_reason, t.urgency_override_by, ou.username AS urgency_override_by_username,
       ou.display_name AS urgency_override_by_name, t.urgency_override_at, t.effort, t.progress, t.progress_derived,
       t.progress_refinement, t.progress_refinement_derived, t.progress_review, t.progress_review_derived,
       t.parent_id,
       t.reporter_id, ru.username AS reporter_username, ru.display_name AS reporter_name,
       t.reporter_agent, t.reporter_token_id, t.reporter_token_name,
       t.assignee_id, au.username AS assignee_username, au.display_name AS assignee_name,
       t.confidential, t.rank, t.score_key, t.score_version, t.opened_at, t.decided_at, t.done_at, t.done_from, t.done_by_hand,
       open_prerequisite_count(t.id)::integer AS open_prerequisites,
       t.version, t.created_at, t.updated_at
FROM tickets t
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
LEFT JOIN users ru ON ru.id = t.reporter_id
LEFT JOIN users au ON au.id = t.assignee_id
LEFT JOIN users ou ON ou.id = t.urgency_override_by
LEFT JOIN tickets bt ON bt.tenant_id = t.tenant_id AND bt.id = t.block_ticket_id
     AND bt.deleted_at IS NULL AND app_ticket_visible(bt.project_id, bt.confidential, bt.assignee_id, bt.reporter_id)
LEFT JOIN projects bp ON bp.tenant_id = bt.tenant_id AND bp.id = bt.project_id
WHERE t.tenant_id = $1 AND t.project_id = $2 AND t.number = $3
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
`

type GetTicketByNumberParams struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	Number    int32
}

type GetTicketByNumberRow struct {
	ID                        uuid.UUID
	ProjectID                 uuid.UUID
	ProjectKey                string
	Number                    int32
	Type                      domain.TicketType
	Title                     string
	Body                      string
	State                     domain.TicketState
	BlockedFrom               *domain.TicketState
	BlockKind                 *domain.BlockKind
	BlockReason               *string
	BlockTicketID             *uuid.UUID
	BlockExternalRef          *string
	BlockProjectKey           *string
	BlockNumber               *int32
	Severity                  domain.Severity
	Security                  domain.SecurityClass
	Threat                    *string
	UrgencyDerived            domain.Urgency
	UrgencyRule               string
	UrgencyOverride           *domain.Urgency
	UrgencyOverrideReason     *string
	UrgencyOverrideBy         *uuid.UUID
	UrgencyOverrideByUsername *string
	UrgencyOverrideByName     *string
	UrgencyOverrideAt         *time.Time
	Effort                    domain.Effort
	Progress                  int16
	ProgressDerived           *int16
	ProgressRefinement        int16
	ProgressRefinementDerived *int16
	ProgressReview            int16
	ProgressReviewDerived     *int16
	ParentID                  *uuid.UUID
	ReporterID                uuid.UUID
	ReporterUsername          *string
	ReporterName              *string
	ReporterAgent             *string
	ReporterTokenID           *uuid.UUID
	ReporterTokenName         *string
	AssigneeID                *uuid.UUID
	AssigneeUsername          *string
	AssigneeName              *string
	Confidential              bool
	Rank                      *string
	ScoreKey                  float64
	ScoreVersion              int16
	OpenedAt                  time.Time
	DecidedAt                 *time.Time
	DoneAt                    *time.Time
	DoneFrom                  *domain.TicketState
	DoneByHand                bool
	OpenPrerequisites         int32
	Version                   int32
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

// The ticket's columns are listed once more in the list builder
// (internal/store/tickets.go); a unit test holds the two lists equal.
// open_prerequisites counts the open tickets of any team that block it and
// whose state the caller reads in a head, the number on a board card
// (docs/adr/0018 D1, docs/adr/0012 D6, D7): open_prerequisite_count of
// migration 47 decides, and never counts a placeholder. The parent is its id
// here; its head comes from relation_heads (store.Reader.ParentHeads). The persons it names — the reporter, the
// assignee and the one who set the horizon — are read through the policy of
// users: a person who is no longer a member of the tenant has the id alone.
func (q *Queries) GetTicketByNumber(ctx context.Context, arg GetTicketByNumberParams) (GetTicketByNumberRow, error) {
	row := q.db.QueryRow(ctx, getTicketByNumber, arg.TenantID, arg.ProjectID, arg.Number)
	var i GetTicketByNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectKey,
		&i.Number,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.State,
		&i.BlockedFrom,
		&i.BlockKind,
		&i.BlockReason,
		&i.BlockTicketID,
		&i.BlockExternalRef,
		&i.BlockProjectKey,
		&i.BlockNumber,
		&i.Severity,
		&i.Security,
		&i.Threat,
		&i.UrgencyDerived,
		&i.UrgencyRule,
		&i.UrgencyOverride,
		&i.UrgencyOverrideReason,
		&i.UrgencyOverrideBy,
		&i.UrgencyOverrideByUsername,
		&i.UrgencyOverrideByName,
		&i.UrgencyOverrideAt,
		&i.Effort,
		&i.Progress,
		&i.ProgressDerived,
		&i.ProgressRefinement,
		&i.ProgressRefinementDerived,
		&i.ProgressReview,
		&i.ProgressReviewDerived,
		&i.ParentID,
		&i.ReporterID,
		&i.ReporterUsername,
		&i.ReporterName,
		&i.ReporterAgent,
		&i.ReporterTokenID,
		&i.ReporterTokenName,
		&i.AssigneeID,
		&i.AssigneeUsername,
		&i.AssigneeName,
		&i.Confidential,
		&i.Rank,
		&i.ScoreKey,
		&i.ScoreVersion,
		&i.OpenedAt,
		&i.DecidedAt,
		&i.DoneAt,
		&i.DoneFrom,
		&i.DoneByHand,
		&i.OpenPrerequisites,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRankPlaces = `-- name: ListRankPlaces :many
SELECT t.id,
       ((SELECT count(*) FROM tickets o
         WHERE o.tenant_id = t.tenant_id AND o.project_id = t.project_id
           AND o.state NOT IN ('done', 'dropped')
           AND coalesce(o.urgency_override, o.urgency_derived) = coalesce(t.urgency_override, t.urgency_derived)
           AND (o.rank < t.rank OR (o.rank IS NOT NULL AND t.rank IS NULL)
                OR (o.rank IS NULL AND t.rank IS NULL AND o.number < t.number))
           AND o.deleted_at IS NULL
           AND app_ticket_visible(o.project_id, o.confidential, o.assignee_id, o.reporter_id)) + 1)::integer AS place
FROM tickets t
WHERE t.tenant_id = $1 AND t.id = ANY ($2::uuid[])
  AND t.state NOT IN ('done', 'dropped')
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
`

type ListRankPlacesParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

type ListRankPlacesRow struct {
	ID    uuid.UUID
	Place int32
}

// Each ticket's place in its project's rank among the open tickets of its
// horizon that the caller can see, 1 for the first: the place the backlog's
// group shows it at, and the secondary indicator of the person-level lists
// (docs/adr/0014 D5, docs/adr/0018 D1). A ticket the caller cannot see, or a
// deleted one, is never counted, so the place tells nothing of one; the
// unranked open tickets of a release before the rank follow the ranked by
// number, as the list shows them.
func (q *Queries) ListRankPlaces(ctx context.Context, arg ListRankPlacesParams) ([]ListRankPlacesRow, error) {
	rows, err := q.db.Query(ctx, listRankPlaces, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRankPlacesRow{}
	for rows.Next() {
		var i ListRankPlacesRow
		if err := rows.Scan(&i.ID, &i.Place); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
