// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTenantTime = `-- name: CountTenantTime :one
SELECT count(*)::bigint AS entries
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
WHERE e.tenant_id = $1
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
  AND ($2::date IS NULL OR e.day >= $2::date)
  AND ($3::date IS NULL OR e.day <= $3::date)
  AND ($4::text IS NULL OR p.key = $4::text)
  AND ($5::integer IS NULL OR t.number = $5::integer)
  AND ($6::uuid IS NULL OR e.person_id = $6::uuid)
  AND ($7::boolean OR e.voided_at IS NULL)
`

type CountTenantTimeParams struct {
	TenantID      uuid.UUID
	FromDay       *time.Time
	ToDay         *time.Time
	ProjectKey    *string
	TicketNumber  *int32
	PersonID      *uuid.UUID
	IncludeVoided bool
}

func (q *Queries) CountTenantTime(ctx context.Context, arg CountTenantTimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantTime,
		arg.TenantID,
		arg.FromDay,
		arg.ToDay,
		arg.ProjectKey,
		arg.TicketNumber,
		arg.PersonID,
		arg.IncludeVoided,
	)
	var entries int64
	err := row.Scan(&entries)
	return entries, err
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT e.id, e.person_id, pu.username AS person_username, pu.display_name AS person_name,
       e.author_id, au.username AS author_username, au.display_name AS author_name,
       e.minutes, e.day, e.note, e.voided_at, e.token_id, e.token_name,
       EXISTS (SELECT 1 FROM time_entry_revisions r WHERE r.tenant_id = e.tenant_id AND r.entry_id = e.id) AS edited,
       e.version, e.created_at, e.updated_at
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
LEFT JOIN users pu ON pu.id = e.person_id
LEFT JOIN users au ON au.id = e.author_id
WHERE e.tenant_id = $1 AND e.ticket_id = $2 AND e.id = $3
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
`

type GetTimeEntryParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	ID       uuid.UUID
}

type GetTimeEntryRow struct {
	ID             uuid.UUID
	PersonID       uuid.UUID
	PersonUsername *string
	PersonName     *string
	AuthorID       uuid.UUID
	AuthorUsername *string
	AuthorName     *string
	Minutes        int32
	Day            time.Time
	Note           string
	VoidedAt       *time.Time
	TokenID        *uuid.UUID
	TokenName      *string
	Edited         bool
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTimeEntry(ctx context.Context, arg GetTimeEntryParams) (GetTimeEntryRow, error) {
	row := q.db.QueryRow(ctx, getTimeEntry, arg.TenantID, arg.TicketID, arg.ID)
	var i GetTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.PersonUsername,
		&i.PersonName,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorName,
		&i.Minutes,
		&i.Day,
		&i.Note,
		&i.VoidedAt,
		&i.TokenID,
		&i.TokenName,
		&i.Edited,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantTime = `-- name: ListTenantTime :many
SELECT e.id, e.person_id, pu.username AS person_username, pu.display_name AS person_name,
       e.author_id, au.username AS author_username, au.display_name AS author_name,
       e.minutes, e.day, e.note, e.voided_at, e.token_id, e.token_name,
       EXISTS (SELECT 1 FROM time_entry_revisions r WHERE r.tenant_id = e.tenant_id AND r.entry_id = e.id) AS edited,
       e.version, e.created_at, e.updated_at, p.key AS project_key, t.number AS ticket_number, t.title AS ticket_title
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
LEFT JOIN users pu ON pu.id = e.person_id
LEFT JOIN users au ON au.id = e.author_id
WHERE e.tenant_id = $1
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
  AND ($2::date IS NULL OR e.day >= $2::date)
  AND ($3::date IS NULL OR e.day <= $3::date)
  AND ($4::text IS NULL OR p.key = $4::text)
  AND ($5::integer IS NULL OR t.number = $5::integer)
  AND ($6::uuid IS NULL OR e.person_id = $6::uuid)
  AND ($7::boolean OR e.voided_at IS NULL)
  AND ($8::uuid IS NULL OR e.id < $8::uuid)
ORDER BY e.id DESC
LIMIT $10 OFFSET $9
`

type ListTenantTimeParams struct {
	TenantID      uuid.UUID
	FromDay       *time.Time
	ToDay         *time.Time
	ProjectKey    *string
	TicketNumber  *int32
	PersonID      *uuid.UUID
	IncludeVoided bool
	Before        *uuid.UUID
	PageOffset    int32
	PageSize      int32
}

type ListTenantTimeRow struct {
	ID             uuid.UUID
	PersonID       uuid.UUID
	PersonUsername *string
	PersonName     *string
	AuthorID       uuid.UUID
	AuthorUsername *string
	AuthorName     *string
	Minutes        int32
	Day            time.Time
	Note           string
	VoidedAt       *time.Time
	TokenID        *uuid.UUID
	TokenName      *string
	Edited         bool
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ProjectKey     string
	TicketNumber   int32
	TicketTitle    string
}

// The tenant's visible entries over a period, newest first: by id after a
// cursor, or a numbered page by offset (docs/adr/0048 D1, D2).
func (q *Queries) ListTenantTime(ctx context.Context, arg ListTenantTimeParams) ([]ListTenantTimeRow, error) {
	rows, err := q.db.Query(ctx, listTenantTime,
		arg.TenantID,
		arg.FromDay,
		arg.ToDay,
		arg.ProjectKey,
		arg.TicketNumber,
		arg.PersonID,
		arg.IncludeVoided,
		arg.Before,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantTimeRow{}
	for rows.Next() {
		var i ListTenantTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.PersonUsername,
			&i.PersonName,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.Minutes,
			&i.Day,
			&i.Note,
			&i.VoidedAt,
			&i.TokenID,
			&i.TokenName,
			&i.Edited,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.TicketNumber,
			&i.TicketTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTime = `-- name: ListTicketTime :many

SELECT e.id, e.person_id, pu.username AS person_username, pu.display_name AS person_name,
       e.author_id, au.username AS author_username, au.display_name AS author_name,
       e.minutes, e.day, e.note, e.voided_at, e.token_id, e.token_name,
       EXISTS (SELECT 1 FROM time_entry_revisions r WHERE r.tenant_id = e.tenant_id AND r.entry_id = e.id) AS edited,
       e.version, e.created_at, e.updated_at
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
LEFT JOIN users pu ON pu.id = e.person_id
LEFT JOIN users au ON au.id = e.author_id
WHERE e.tenant_id = $1 AND e.ticket_id = $2
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
  AND ($3::uuid IS NULL OR e.id > $3::uuid)
ORDER BY e.id
LIMIT $4
`

type ListTicketTimeParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListTicketTimeRow struct {
	ID             uuid.UUID
	PersonID       uuid.UUID
	PersonUsername *string
	PersonName     *string
	AuthorID       uuid.UUID
	AuthorUsername *string
	AuthorName     *string
	Minutes        int32
	Day            time.Time
	Note           string
	VoidedAt       *time.Time
	TokenID        *uuid.UUID
	TokenName      *string
	Edited         bool
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Time entries are visible through their ticket's predicate and the time
// visibility of docs/adr/0034 D5 (app_time_visible).
func (q *Queries) ListTicketTime(ctx context.Context, arg ListTicketTimeParams) ([]ListTicketTimeRow, error) {
	rows, err := q.db.Query(ctx, listTicketTime,
		arg.TenantID,
		arg.TicketID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTimeRow{}
	for rows.Next() {
		var i ListTicketTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.PersonUsername,
			&i.PersonName,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.Minutes,
			&i.Day,
			&i.Note,
			&i.VoidedAt,
			&i.TokenID,
			&i.TokenName,
			&i.Edited,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntryRevisions = `-- name: ListTimeEntryRevisions :many
SELECT r.id, r.minutes, r.day, r.note, r.edited_by, u.username AS edited_by_username,
       u.display_name AS edited_by_name, r.token_id, r.token_name, r.created_at
FROM time_entry_revisions r
JOIN time_entries e ON e.tenant_id = r.tenant_id AND e.id = r.entry_id
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
LEFT JOIN users u ON u.id = r.edited_by
WHERE r.tenant_id = $1 AND r.entry_id = $2
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
  AND ($3::uuid IS NULL OR r.id > $3::uuid)
ORDER BY r.id
LIMIT $4
`

type ListTimeEntryRevisionsParams struct {
	TenantID uuid.UUID
	EntryID  uuid.UUID
	After    *uuid.UUID
	PageSize int32
}

type ListTimeEntryRevisionsRow struct {
	ID               uuid.UUID
	Minutes          int32
	Day              time.Time
	Note             string
	EditedBy         uuid.UUID
	EditedByUsername *string
	EditedByName     *string
	TokenID          *uuid.UUID
	TokenName        *string
	CreatedAt        time.Time
}

func (q *Queries) ListTimeEntryRevisions(ctx context.Context, arg ListTimeEntryRevisionsParams) ([]ListTimeEntryRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listTimeEntryRevisions,
		arg.TenantID,
		arg.EntryID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimeEntryRevisionsRow{}
	for rows.Next() {
		var i ListTimeEntryRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Minutes,
			&i.Day,
			&i.Note,
			&i.EditedBy,
			&i.EditedByUsername,
			&i.EditedByName,
			&i.TokenID,
			&i.TokenName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTicketTime = `-- name: SumTicketTime :one
SELECT coalesce(sum(e.minutes), 0)::bigint AS minutes
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
WHERE e.tenant_id = $1 AND e.ticket_id = $2 AND e.voided_at IS NULL
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
`

type SumTicketTimeParams struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
}

// The minutes of the visible entries a ticket carries, voided ones excluded
// (docs/adr/0017 D7).
func (q *Queries) SumTicketTime(ctx context.Context, arg SumTicketTimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumTicketTime, arg.TenantID, arg.TicketID)
	var minutes int64
	err := row.Scan(&minutes)
	return minutes, err
}

const timeReport = `-- name: TimeReport :many
SELECT CASE $1::text
           WHEN 'ticket' THEN p.key || '-' || t.number::text
           WHEN 'project' THEN p.key
           WHEN 'person' THEN e.person_id::text
           ELSE 'tenant' END::text AS group_key,
       max(CASE $1::text
               WHEN 'ticket' THEN t.title
               WHEN 'project' THEN p.name
               WHEN 'person' THEN coalesce(u.display_name, '')
               ELSE '' END)::text AS label,
       sum(e.minutes)::bigint AS minutes
FROM time_entries e
JOIN tickets t ON t.tenant_id = e.tenant_id AND t.id = e.ticket_id
JOIN projects p ON p.tenant_id = t.tenant_id AND p.id = t.project_id
LEFT JOIN users u ON u.id = e.person_id
WHERE e.tenant_id = $2 AND e.voided_at IS NULL
  AND t.deleted_at IS NULL AND app_ticket_visible(t.project_id, t.confidential, t.assignee_id, t.reporter_id)
  AND app_time_visible(e.person_id)
  AND ($3::date IS NULL OR e.day >= $3::date)
  AND ($4::date IS NULL OR e.day <= $4::date)
  AND ($5::text IS NULL OR p.key = $5::text)
  AND ($6::uuid IS NULL OR e.person_id = $6::uuid)
GROUP BY 1
ORDER BY 1
`

type TimeReportParams struct {
	GroupBy    string
	TenantID   uuid.UUID
	FromDay    *time.Time
	ToDay      *time.Time
	ProjectKey *string
	PersonID   *uuid.UUID
}

type TimeReportRow struct {
	GroupKey string
	Label    string
	Minutes  int64
}

// Minutes summed per ticket, project, person or for the tenant over a
// period (docs/adr/0017 D10); voided entries never count.
func (q *Queries) TimeReport(ctx context.Context, arg TimeReportParams) ([]TimeReportRow, error) {
	rows, err := q.db.Query(ctx, timeReport,
		arg.GroupBy,
		arg.TenantID,
		arg.FromDay,
		arg.ToDay,
		arg.ProjectKey,
		arg.PersonID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeReportRow{}
	for rows.Next() {
		var i TimeReportRow
		if err := rows.Scan(&i.GroupKey, &i.Label, &i.Minutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
