// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package readq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guided-traffic/cowork/backend/internal/domain"
)

const countRecentRefusals = `-- name: CountRecentRefusals :one
SELECT count(*)
FROM audit_events
WHERE tenant_id IS NULL
  AND token_id = $1
  AND action = 'refused'
  AND reason = $2
  AND created_at > now() - interval '1 hour'
`

type CountRecentRefusalsParams struct {
	TokenID *uuid.UUID
	Reason  *string
}

// docs/adr/0035 D9: a refused use is recorded at most once per token, reason
// and hour.
func (q *Queries) CountRecentRefusals(ctx context.Context, arg CountRecentRefusalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRefusals, arg.TokenID, arg.Reason)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, name, scope, restricted_tenant_id, restricted_project_id, agent,
       capabilities, created_at, expires_at, last_used_on, revoked_at
FROM tokens
WHERE token_hash = $1
`

type GetTokenByHashRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Name                string
	Scope               domain.Scope
	RestrictedTenantID  *uuid.UUID
	RestrictedProjectID *uuid.UUID
	Agent               bool
	Capabilities        []string
	CreatedAt           time.Time
	ExpiresAt           time.Time
	LastUsedOn          *time.Time
	RevokedAt           *time.Time
}

// The resolver's lookup: the policy admits the row whose hash the lookup
// transaction set in app.token_hash, and no other.
func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash []byte) (GetTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i GetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scope,
		&i.RestrictedTenantID,
		&i.RestrictedProjectID,
		&i.Agent,
		&i.Capabilities,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedOn,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenOfUser = `-- name: GetTokenOfUser :one
SELECT id, revoked_at
FROM tokens
WHERE id = $1 AND user_id = $2
`

type GetTokenOfUserParams struct {
	TokenID uuid.UUID
	UserID  uuid.UUID
}

type GetTokenOfUserRow struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) GetTokenOfUser(ctx context.Context, arg GetTokenOfUserParams) (GetTokenOfUserRow, error) {
	row := q.db.QueryRow(ctx, getTokenOfUser, arg.TokenID, arg.UserID)
	var i GetTokenOfUserRow
	err := row.Scan(&i.ID, &i.RevokedAt)
	return i, err
}

const listTokensOfUser = `-- name: ListTokensOfUser :many
SELECT t.id, t.name, t.scope, t.agent, t.capabilities, t.restricted_tenant_id, t.restricted_project_id,
       t.created_at, t.expires_at, t.last_used_on, t.revoked_at, rt.slug AS restricted_tenant_slug
FROM tokens t
LEFT JOIN tenants rt ON rt.id = t.restricted_tenant_id
WHERE t.user_id = $1
  AND ($2::uuid IS NULL OR t.id = $2::uuid)
  AND ($3::uuid IS NULL OR t.id < $3::uuid)
ORDER BY t.id DESC
LIMIT $4
`

type ListTokensOfUserParams struct {
	UserID   uuid.UUID
	OnlyID   *uuid.UUID
	Before   *uuid.UUID
	PageSize int32
}

type ListTokensOfUserRow struct {
	ID                   uuid.UUID
	Name                 string
	Scope                domain.Scope
	Agent                bool
	Capabilities         []string
	RestrictedTenantID   *uuid.UUID
	RestrictedProjectID  *uuid.UUID
	CreatedAt            time.Time
	ExpiresAt            time.Time
	LastUsedOn           *time.Time
	RevokedAt            *time.Time
	RestrictedTenantSlug *string
}

// The person's tokens, newest first, revoked and expired ones included
// (docs/adr/0035 D6); only one of them for a restricted token.
func (q *Queries) ListTokensOfUser(ctx context.Context, arg ListTokensOfUserParams) ([]ListTokensOfUserRow, error) {
	rows, err := q.db.Query(ctx, listTokensOfUser,
		arg.UserID,
		arg.OnlyID,
		arg.Before,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokensOfUserRow{}
	for rows.Next() {
		var i ListTokensOfUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.Agent,
			&i.Capabilities,
			&i.RestrictedTenantID,
			&i.RestrictedProjectID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedOn,
			&i.RevokedAt,
			&i.RestrictedTenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tokenStillUsable = `-- name: TokenStillUsable :one
SELECT EXISTS (
    SELECT 1
    FROM tokens t
    JOIN users u ON u.id = t.user_id
    WHERE t.id = $1 AND t.user_id = $2 AND t.revoked_at IS NULL
      AND t.expires_at > now() AND u.deactivated_at IS NULL
) AS usable
`

type TokenStillUsableParams struct {
	TokenID uuid.UUID
	UserID  uuid.UUID
}

// Whether a stream's token may go on: not revoked, not expired, its person
// not deactivated (docs/adr/0035 D6).
func (q *Queries) TokenStillUsable(ctx context.Context, arg TokenStillUsableParams) (bool, error) {
	row := q.db.QueryRow(ctx, tokenStillUsable, arg.TokenID, arg.UserID)
	var usable bool
	err := row.Scan(&usable)
	return usable, err
}
