/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RemoveProjectAccess$Params {

/**
 * The tenant's slug (docs/adr/0005 D4)
 */
  tenant: string;

/**
 * The project's key (docs/adr/0007 D1)
 */
  project: string;

/**
 * A person's id
 */
  person_id: string;
}

export function removeProjectAccess(http: HttpClient, rootUrl: string, params: RemoveProjectAccess$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, removeProjectAccess.PATH, 'delete');
  if (params) {
    rb.path('tenant', params.tenant, {});
    rb.path('project', params.project, {});
    rb.path('person_id', params.person_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

removeProjectAccess.PATH = '/api/v1/tenants/{tenant}/projects/{project}/access/{person_id}';
